import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useFacilityData } from '../data/FacilityDataContext';
import { EntityDialog, Field, FormFeedback } from '../components/facility/EntityDialog';
import { PageTitle } from '../components/workflow/WorkflowShared';

const storageKey = 'veyro-facility-v2:calendar-panel-width';
const startOfWeek = (value) => { const date = new Date(`${value}T12:00:00`); const day = date.getDay() || 7; date.setDate(date.getDate() - day + 1); return date; };
const dateKey = (date) => date.toISOString().slice(0, 10);
export function CalendarPage() {
  const { dataset } = useFacilityData(); const [view, setView] = useState('week'); const [anchor, setAnchor] = useState(dateKey(startOfWeek(new Date().toISOString().slice(0, 10)))); const [selectedId, setSelectedId] = useState(''); const [editing, setEditing] = useState(false); const [panelWidth, setPanelWidth] = useState(() => Number(localStorage.getItem(storageKey)) || 340); const [resourceId, setResourceId] = useState(''); const [propertyId, setPropertyId] = useState('');
  const monday = startOfWeek(anchor); const days = Array.from({ length: 5 }, (_, index) => { const date = new Date(monday); date.setDate(date.getDate() + index); return date; });
  const rows = useMemo(() => dataset.bookings.filter((item) => (!resourceId || item.resourceId === resourceId) && (!propertyId || item.propertyId === propertyId)), [dataset.bookings, propertyId, resourceId]); const selected = rows.find((item) => item.id === selectedId);
  const moveWeek = (amount) => { const date = new Date(monday); date.setDate(date.getDate() + amount * 7); setAnchor(dateKey(date)); };
  return <main className="workflow-page calendar-page"><PageTitle title="Vedligeholdelseskalender" description="Planlæg interne ressourcer og leverandørbesøg. Booking er ikke udført arbejde." action={<button className="primary-button" onClick={() => { setSelectedId(''); setEditing(true); }}>+ Opret aftale</button>} />
    <section className="card calendar-toolbar"><div><button className="secondary-button" onClick={() => moveWeek(-1)}>‹</button><button className="secondary-button" onClick={() => moveWeek(1)}>›</button><button className="secondary-button" onClick={() => setAnchor(dateKey(startOfWeek(new Date().toISOString().slice(0, 10))))}>I dag</button></div><div className="segmented">{['week', 'month', 'list'].map((item) => <button key={item} className={view === item ? 'active' : ''} onClick={() => setView(item)}>{item === 'week' ? 'Uge' : item === 'month' ? 'Måned' : 'Liste'}</button>)}</div><select aria-label="Ressource" value={resourceId} onChange={(e) => setResourceId(e.target.value)}><option value="">Alle ressourcer</option>{dataset.resources.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Ejendom" value={propertyId} onChange={(e) => setPropertyId(e.target.value)}><option value="">Alle ejendomme</option>{dataset.properties.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></section>
    <div className={`calendar-shell ${selected ? 'has-detail' : ''}`} style={{ '--calendar-detail-width': `${panelWidth}px` }}><section className="card calendar-canvas">{view === 'week' ? <WeekView days={days} rows={rows} dataset={dataset} onSelect={setSelectedId} /> : view === 'month' ? <MonthView anchor={monday} rows={rows} dataset={dataset} onSelect={setSelectedId} /> : <BookingList rows={rows} dataset={dataset} onSelect={setSelectedId} />}</section>{selected && <><div className="calendar-resizer"><input aria-label="Detaljepanelets bredde" type="range" min="280" max="500" value={panelWidth} onChange={(e) => { const value = Number(e.target.value); setPanelWidth(value); localStorage.setItem(storageKey, String(value)); }} /></div><BookingDetail booking={selected} dataset={dataset} onClose={() => setSelectedId('')} onEdit={() => setEditing(true)} /></>}</div>{editing && <BookingDialog booking={selected} onClose={() => setEditing(false)} onSaved={(item) => setSelectedId(item.id)} />}
  </main>;
}

function WeekView({ days, rows, dataset, onSelect }) { return <div className="week-grid"><div className="week-time-head" />{days.map((day) => <header key={dateKey(day)}><strong>{day.toLocaleDateString('da-DK', { weekday: 'short' })}</strong><span>{day.toLocaleDateString('da-DK', { day: 'numeric', month: 'short' })}</span></header>)}<div className="time-axis">{Array.from({ length: 10 }, (_, i) => <span key={i}>{String(7 + i).padStart(2, '0')}:00</span>)}</div>{days.map((day) => <div className="day-column" key={dateKey(day)}>{Array.from({ length: 10 }, (_, i) => <i key={i} />)}{rows.filter((item) => item.startAt.slice(0, 10) === dateKey(day)).map((booking, index, same) => { const start = new Date(booking.startAt); const end = new Date(booking.endAt); const top = ((start.getHours() + start.getMinutes() / 60) - 7) * 62; const height = Math.max(34, (end - start) / 3600000 * 62); const width = 100 / same.length; const task = dataset.tasks.find((item) => item.id === booking.taskId); return <button key={booking.id} className={`calendar-event status-${booking.status}`} style={{ top, height, left: `${index * width}%`, width: `calc(${width}% - 4px)` }} onClick={() => onSelect(booking.id)}><time>{start.toLocaleTimeString('da-DK', { hour: '2-digit', minute: '2-digit' })}</time><strong>{task?.taskNumber}</strong><span>{task?.title}</span></button>; })}</div>)}</div>; }
function MonthView({ anchor, rows, dataset, onSelect }) { const first = new Date(anchor.getFullYear(), anchor.getMonth(), 1); const start = startOfWeek(dateKey(first)); const days = Array.from({ length: 35 }, (_, i) => { const date = new Date(start); date.setDate(date.getDate() + i); return date; }); return <div className="month-grid">{days.map((day) => <div key={dateKey(day)} className={day.getMonth() !== anchor.getMonth() ? 'muted-day' : ''}><b>{day.getDate()}</b>{rows.filter((item) => item.startAt.slice(0, 10) === dateKey(day)).map((booking) => <button key={booking.id} onClick={() => onSelect(booking.id)}>{dataset.tasks.find((item) => item.id === booking.taskId)?.taskNumber}</button>)}</div>)}</div>; }
function BookingList({ rows, dataset, onSelect }) { return <div className="table-scroll"><table><thead><tr><th>Tid</th><th>Opgave</th><th>Ressource</th><th>Status</th></tr></thead><tbody>{rows.sort((a, b) => a.startAt.localeCompare(b.startAt)).map((item) => <tr key={item.id} onClick={() => onSelect(item.id)}><td>{new Date(item.startAt).toLocaleString('da-DK')} – {new Date(item.endAt).toLocaleTimeString('da-DK', { hour: '2-digit', minute: '2-digit' })}</td><td>{dataset.tasks.find((task) => task.id === item.taskId)?.title}</td><td>{dataset.resources.find((resource) => resource.id === item.resourceId)?.name || dataset.suppliers.find((supplier) => supplier.id === item.supplierId)?.name}</td><td>{item.status}</td></tr>)}</tbody></table></div>; }
function BookingDetail({ booking, dataset, onClose, onEdit }) { const task = dataset.tasks.find((item) => item.id === booking.taskId); return <aside className="card calendar-detail"><header><div><small>{task?.taskNumber}</small><h2>{task?.title}</h2></div><button className="icon-button" aria-label="Luk detaljepanel" onClick={onClose}>×</button></header><dl><div><dt>Tidspunkt</dt><dd>{new Date(booking.startAt).toLocaleString('da-DK')} – {new Date(booking.endAt).toLocaleTimeString('da-DK', { hour: '2-digit', minute: '2-digit' })}</dd></div><div><dt>Ressource</dt><dd>{dataset.resources.find((item) => item.id === booking.resourceId)?.name || 'Ikke angivet'}</dd></div><div><dt>Leverandør</dt><dd>{dataset.suppliers.find((item) => item.id === booking.supplierId)?.name || 'Ikke angivet'}</dd></div><div><dt>Kapacitet</dt><dd>{booking.capacityStatus === 'notVerified' ? 'Kapacitet ikke verificeret' : booking.capacityStatus === 'conflict' ? 'Overlap fundet' : 'Ingen overlap for konkret ressource'}</dd></div><div><dt>Bemærkning</dt><dd>{booking.note || '—'}</dd></div></dl><div className="heading-actions"><button className="primary-button" onClick={onEdit}>Rediger</button><Link className="secondary-button" to={`/facility/opgaver/${task?.id}`}>Se opgave</Link>{task?.caseId && <Link className="secondary-button" to={`/facility/sager/${task.caseId}`}>Se sag</Link>}</div></aside>; }

function BookingDialog({ booking, onClose, onSaved }) { const { dataset, runMutation } = useFacilityData(); const task = booking ? dataset.tasks.find((item) => item.id === booking.taskId) : null; const defaultTask = task ?? dataset.tasks.find((item) => !['completed', 'cancelled'].includes(item.status)); const baseDate = booking?.startAt?.slice(0, 16) ?? `${new Date().toISOString().slice(0, 10)}T08:00`; const [form, setForm] = useState({ taskId: defaultTask?.id ?? '', resourceId: booking?.resourceId ?? defaultTask?.resourceId ?? '', supplierId: booking?.supplierId ?? defaultTask?.supplierId ?? '', startAt: baseDate, endAt: booking?.endAt?.slice(0, 16) ?? `${new Date().toISOString().slice(0, 10)}T10:00`, note: booking?.note ?? '', status: booking?.status ?? 'planned', reason: '' }); const [error, setError] = useState(null); const change = (name) => (e) => setForm({ ...form, [name]: e.target.value }); async function submit(event) { event.preventDefault(); try { const result = booking ? await runMutation('updateBooking', booking.id, booking.revision, form) : await runMutation('createBooking', form); onSaved(result.entity); onClose(); } catch (reason) { setError(reason); } }
  return <EntityDialog title={booking ? 'Rediger aftale' : 'Opret aftale'} description="Overlap vurderes kun for den konkrete ressource." onClose={onClose} dirty><form className="entity-form" onSubmit={submit}><FormFeedback error={error} /><div className="form-grid"><Field label="Opgave"><select value={form.taskId} onChange={change('taskId')} disabled={Boolean(booking)}>{dataset.tasks.map((item) => <option key={item.id} value={item.id}>{item.taskNumber} · {item.title}</option>)}</select></Field><Field label="Konkret ressource"><select value={form.resourceId} onChange={change('resourceId')}><option value="">Ingen konkret ressource</option>{dataset.resources.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Start"><input type="datetime-local" value={form.startAt} onChange={change('startAt')} /></Field><Field label="Slut"><input type="datetime-local" value={form.endAt} onChange={change('endAt')} /></Field><Field label="Status"><select value={form.status} onChange={change('status')}><option value="planned">Planlagt</option><option value="cancelled">Annulleret</option></select></Field><Field label="Bemærkning"><textarea value={form.note} onChange={change('note')} /></Field>{form.status === 'cancelled' && <Field label="Begrundelse"><input value={form.reason} onChange={change('reason')} /></Field>}</div><footer className="dialog-actions"><button type="button" className="secondary-button" onClick={onClose}>Annuller</button><button className="primary-button">Gem aftale</button></footer></form></EntityDialog>; }
