import { useState } from 'react';
import { useParams } from 'react-router-dom';
import { FacilityLink as Link, useFacilityNavigate as useNavigate } from '../routing/FacilityRouting';
import { useFacilityData } from '../data/FacilityDataContext';
import { CaseBadge, EntityPath, PageTitle, PriorityBadge, RelatedDocuments, TaskBadge } from '../components/workflow/WorkflowShared';
import { TaskForm } from '../components/workflow/TaskForm';

export function CasePage() {
  const { caseId } = useParams(); const navigate = useNavigate(); const { dataset, runMutation } = useFacilityData(); const record = dataset.cases.find((item) => item.id === caseId); const [taskOpen, setTaskOpen] = useState(false); const [error, setError] = useState(''); const [confirmed, setConfirmed] = useState(false); const [mode, setMode] = useState('normal'); const [reason, setReason] = useState(''); const [restriction, setRestriction] = useState({ scope: '', reason: '', targetType: 'property', targetId: '', source: 'Manuel driftsvurdering' });
  if (!record) return <main className="workflow-page"><PageTitle title="Sagen blev ikke fundet" description="ID’et findes ikke i den aktuelle demokundes lokale data." /><button className="secondary-button" onClick={() => navigate('/facility/arbejdsko')}>Tilbage til Arbejdskø</button></main>;
  const report = dataset.reports.find((item) => item.id === record.reportId); const tasks = dataset.tasks.filter((item) => item.caseId === record.id); const restrictions = dataset.restrictions.filter((item) => item.caseId === record.id); const history = dataset.history.filter((item) => item.entityId === record.id || tasks.some((task) => task.id === item.entityId)).sort((a, b) => b.timestamp.localeCompare(a.timestamp));
  const workDone = tasks.length === 0 || tasks.every((item) => ['completed', 'cancelled'].includes(item.status));
  async function close() { setError(''); try { await runMutation('closeCase', record.id, record.revision, { mode, confirmed, reason }); } catch (e) { setError(e.message + (e.blockers?.length ? ` ${e.blockers.join(' · ')}` : '')); } }
  async function reopen() { const why = window.prompt('Begrund genåbningen'); if (!why) return; try { await runMutation('reopenCase', record.id, record.revision, why); } catch (e) { setError(e.message); } }
  async function addRestriction(event) { event.preventDefault(); try { await runMutation('addRestriction', record.id, record.revision, { ...restriction, targetId: restriction.targetId || record.propertyId }); setRestriction((value) => ({ ...value, scope: '', reason: '' })); } catch (e) { setError(e.message); } }
  return <main className="workflow-page case-folder"><div className="profile-breadcrumb"><Link to="/facility/arbejdsko">Arbejdskø</Link><span>{record.reference}</span></div><PageTitle title="Sagsmappe og lukning" description="Gennemse sagsforløb, dokumentation og luk sagen med en særskilt handling." action={<div className="heading-actions"><CaseBadge value={record.status} />{record.status === 'closed' ? <button className="primary-button" onClick={reopen}>Genåbn sag</button> : <button className="primary-button" onClick={() => setTaskOpen(true)}>+ Opret opgave</button>}</div>} />
    <div className="case-top-grid"><section className="card case-summary"><div><span className="record-reference">{record.reference}</span><h2>{record.title}</h2><p>{record.description}</p><p className="entity-path"><EntityPath dataset={dataset} record={record} /></p>{record.installationId && <Link className="row-link" to={`/facility/installationer/${record.installationId}`}>Åbn installation</Link>}</div><dl><div><dt>Kilde</dt><dd>{record.source}</dd></div><div><dt>Prioritet</dt><dd><PriorityBadge value={record.priority} /></dd></div><div><dt>Ansvarlig</dt><dd>{dataset.resources.find((item) => item.id === record.responsibleId)?.name || 'Ikke tildelt'}</dd></div><div><dt>Frist</dt><dd>{record.dueDate || 'Ikke angivet'}</dd></div><div><dt>Historisk placering</dt><dd>{record.historicalLocationSnapshot}</dd></div></dl></section>
      <section className="card status-stack"><h2>Adskilte tilstande</h2><div><span>Arbejde</span><b>{workDone ? 'Afklaret' : 'Åbent'}</b></div><div><span>Installation</span><b>{dataset.installations.find((item) => item.id === record.installationId)?.functionStatus === 'fault' ? 'Fejl registreret' : 'Ikke vurderet her'}</b></div><div><span>Område</span><b>{restrictions.some((item) => item.status === 'active') ? `${restrictions.filter((item) => item.status === 'active').length} aktiv(e) begrænsning(er)` : 'Ingen aktiv begrænsning'}</b></div><div><span>Faktura</span><b className="warning-text">Fakturacenter ikke tilsluttet</b></div><div><span>Sag</span><CaseBadge value={record.status} /></div></section></div>
    <div className="case-body-grid"><div className="case-main-stack"><section className="card workflow-section"><header><h2>Sagsforløb</h2><span>{history.length} hændelser</span></header><div className="timeline">{history.map((item) => <div key={item.id}><time>{new Date(item.timestamp).toLocaleString('da-DK')}</time><strong>{item.action}</strong><span>{item.reason}</span></div>)}</div></section>
      <section className="card workflow-section"><header><h2>Opgaver og bestillinger</h2><button className="secondary-button" onClick={() => setTaskOpen(true)}>+ Opret opgave</button></header>{tasks.length ? <div className="table-scroll"><table><thead><tr><th>Opgave</th><th>Bestilling</th><th>Tildeling</th><th>Status</th><th></th></tr></thead><tbody>{tasks.map((item) => <tr key={item.id}><td><strong>{item.taskNumber}</strong><small>{item.title}</small></td><td>{item.orderNumber || '—'}</td><td>{item.assignmentType === 'external' ? dataset.suppliers.find((s) => s.id === item.supplierId)?.name : dataset.resources.find((r) => r.id === item.resourceId)?.name}</td><td><TaskBadge value={item.status} /></td><td><Link className="row-link" to={`/facility/opgaver/${item.id}`}>Åbn</Link></td></tr>)}</tbody></table></div> : <p className="muted-copy">Sagen har endnu ingen opgaver.</p>}</section>
      <section className="card workflow-section"><header><h2>Oprindelig indberetning og bilag</h2>{report && <span>{report.reference}</span>}</header>{report ? <><p>{report.description}</p><p className="muted-copy">Oplevet alvorlighed: {report.reporterSeverity} · Observeret {new Date(report.observedAt).toLocaleString('da-DK')}</p></> : <p className="muted-copy">Manuelt oprettet sag uden indberetning.</p>}<RelatedDocuments dataset={dataset} versionIds={record.attachmentVersionIds} /></section>
      <section className="card workflow-section"><header><h2>Bekræftede driftsbegrænsninger</h2></header>{restrictions.map((item) => <div className="restriction-row" key={item.id}><div><strong>{item.scope}</strong><span>{item.reason} · {item.source}</span></div>{item.status === 'active' ? <button className="secondary-button" onClick={async () => { const why = window.prompt('Begrund afklaringen'); if (why) await runMutation('resolveRestriction', item.id, item.revision, why); }}>Afklar</button> : <span className="workflow-badge task-completed">Afklaret</span>}</div>)}<form className="inline-form" onSubmit={addRestriction}><input required placeholder="Omfang, fx Teknikrum" value={restriction.scope} onChange={(e) => setRestriction({ ...restriction, scope: e.target.value })} /><input required placeholder="Begrundelse" value={restriction.reason} onChange={(e) => setRestriction({ ...restriction, reason: e.target.value })} /><button className="secondary-button">Registrér begrænsning</button></form></section></div>
      <aside className="card closure-panel"><h2>{record.status === 'closed' ? 'Sagen er lukket' : 'Luk sag'}</h2>{record.status === 'closed' ? <><p>{record.closureReason}</p><p className="muted-copy">Lukket {new Date(record.closedAt).toLocaleString('da-DK')}</p></> : <><p>Normal lukning kræver afsluttet arbejde og fakturaafklaring. Bogføring er ikke et krav.</p><div className="closure-checks"><span className={workDone ? 'ok' : ''}>✓ Relevante opgaver afklaret</span><span>○ Fakturacenter-integration ikke tilsluttet</span></div><label><input type="radio" checked={mode === 'normal'} onChange={() => setMode('normal')} /> Normal lukning efter fakturaafklaring</label><label><input type="radio" checked={mode === 'withoutInvoice'} onChange={() => setMode('withoutInvoice')} /> Luk uden forventet faktura</label>{mode === 'withoutInvoice' && <textarea placeholder="Obligatorisk begrundelse, fx internt arbejde eller garanti" value={reason} onChange={(e) => setReason(e.target.value)} />}<label className="confirm-box"><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} /> Jeg bekræfter aktivt, at sagen skal lukkes</label>{error && <p className="form-feedback">{error}</p>}<button className="primary-button full-width" onClick={close}>Luk sag</button><p className="integration-note">FACILITY foretager ingen fakturamodtagelse, matching eller kontrol.</p></>}</aside></div>{taskOpen && <TaskForm caseRecord={record} onClose={() => setTaskOpen(false)} />}
  </main>;
}
