import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useFacilityData } from '../data/FacilityDataContext';
import { EntityDialog, Field, FormFeedback } from '../components/facility/EntityDialog';
import { Empty, PageTitle } from '../components/workflow/WorkflowShared';

const relationOptions = (dataset) => [
  ...dataset.properties.map((item) => ({ key: `property:${item.id}`, type: 'property', id: item.id, label: `Ejendom · ${item.number} ${item.name}` })),
  ...dataset.locationNodes.map((item) => ({ key: `location:${item.id}`, type: 'location', id: item.id, label: `Sted · ${item.name}` })),
  ...dataset.installations.map((item) => ({ key: `installation:${item.id}`, type: 'installation', id: item.id, label: `Installation · ${item.number}` })),
  ...dataset.reports.map((item) => ({ key: `report:${item.id}`, type: 'report', id: item.id, label: `Indberetning · ${item.reference}` })),
  ...dataset.cases.map((item) => ({ key: `case:${item.id}`, type: 'case', id: item.id, label: `Sag · ${item.reference}` })),
  ...dataset.tasks.map((item) => ({ key: `task:${item.id}`, type: 'task', id: item.id, label: `Opgave · ${item.taskNumber}` })),
  ...dataset.servicePlans.map((item) => ({ key: `servicePlan:${item.id}`, type: 'servicePlan', id: item.id, label: `Serviceplan · ${item.name}` })),
  ...dataset.serviceOccurrences.map((item) => ({ key: `serviceOccurrence:${item.id}`, type: 'serviceOccurrence', id: item.id, label: `Serviceforekomst · ${item.activity}` })),
];
export function DocumentsPage() {
  const { dataset } = useFacilityData(); const [params, setParams] = useSearchParams(); const [query, setQuery] = useState(''); const [category, setCategory] = useState(''); const [archived, setArchived] = useState(false); const [upload, setUpload] = useState(false); const relation = [...params.entries()].find(([key]) => ['property', 'location', 'installation', 'report', 'case', 'task', 'servicePlan', 'serviceOccurrence'].includes(key));
  const rows = useMemo(() => dataset.documents.filter((item) => (archived ? item.archivedAt : !item.archivedAt) && (!query || `${item.title} ${item.category} ${item.notes}`.toLowerCase().includes(query.toLowerCase())) && (!category || item.category === category) && (!relation || item.relations.some((entry) => entry.type === relation[0] && entry.id === relation[1]))).sort((a, b) => b.createdAt.localeCompare(a.createdAt)), [archived, category, dataset.documents, query, relation]);
  const selectedId = params.get('document') || rows[0]?.id; const selected = dataset.documents.find((item) => item.id === selectedId);
  return <main className="workflow-page documents-page"><PageTitle title="Dokumenter" description="Fælles FACILITY-register med konkrete versioner, relationer og bevaret filindhold." action={<button className="primary-button" onClick={() => setUpload(true)}>+ Upload flere filer</button>} />
    <div className="card workflow-toolbar"><input placeholder="Søg i dokumenter …" value={query} onChange={(e) => setQuery(e.target.value)} /><select value={category} onChange={(e) => setCategory(e.target.value)}><option value="">Alle kategorier</option>{[...new Set(dataset.documents.map((item) => item.category))].map((item) => <option key={item}>{item}</option>)}</select><label><input type="checkbox" checked={archived} onChange={(e) => setArchived(e.target.checked)} /> Vis arkiverede</label>{relation && <button className="secondary-button" onClick={() => setParams({})}>Nulstil relation: {relation[0]}</button>}</div>
    <div className="documents-layout"><section className="card document-list"><div className="table-scroll"><table><thead><tr><th>Navn</th><th>Type</th><th>Version</th><th>Tilknytninger</th><th>Gyldighed</th><th>Status</th></tr></thead><tbody>{rows.map((item) => { const version = item.versions.find((value) => value.id === item.currentVersionId); const expired = item.validUntil && item.validUntil < new Date().toLocaleDateString('sv-SE'); return <tr key={item.id} className={item.id === selectedId ? 'is-selected' : ''} onClick={() => setParams({ document: item.id })}><td><strong>{item.title}</strong><small>{version?.fileName}</small></td><td>{item.category}</td><td>v{version?.number}</td><td>{item.relations.length}</td><td>{item.validUntil || '—'}</td><td><span className={`workflow-badge ${expired ? 'priority-high' : ''}`}>{item.archivedAt ? 'Arkiveret' : expired ? 'Udløbet' : 'Aktiv'}</span></td></tr>; })}</tbody></table></div>{!rows.length && <Empty title="Ingen dokumenter matcher" text="Upload filer eller nulstil filtrene." />}</section><DocumentDetail document={selected} /></div>{upload && <UploadDialog onClose={() => setUpload(false)} />}
  </main>;
}

function useBlob(version) { const { repository } = useFacilityData(); const [url, setUrl] = useState(''); useEffect(() => { let active = true; let objectUrl = ''; if (version) repository.getBlob(version.blobId).then((blob) => { if (blob && active) { objectUrl = URL.createObjectURL(blob); setUrl(objectUrl); } }); return () => { active = false; if (objectUrl) URL.revokeObjectURL(objectUrl); }; }, [repository, version]); return url; }
function DocumentDetail({ document }) { const { runMutation } = useFacilityData(); const [versionId, setVersionId] = useState(document?.currentVersionId); const [newVersion, setNewVersion] = useState(false); useEffect(() => setVersionId(document?.currentVersionId), [document]); const version = document?.versions.find((item) => item.id === versionId); const url = useBlob(version); if (!document) return <aside className="card document-detail"><Empty title="Vælg et dokument" /></aside>; const previewable = version && (version.mimeType === 'application/pdf' || version.mimeType.startsWith('image/') || version.mimeType.startsWith('video/'));
  return <aside className="card document-detail"><header><div><small>DOKUMENT</small><h2>{document.title}</h2></div></header><div className="document-preview">{url && previewable ? version.mimeType === 'application/pdf' ? <iframe title={document.title} src={url} /> : version.mimeType.startsWith('video/') ? <video controls src={url} /> : <img src={url} alt="Dokumentforhåndsvisning" /> : <Empty title="Forhåndsvisning ikke tilgængelig" text="Filen kan stadig downloades." />}</div><dl><div><dt>Kategori</dt><dd>{document.category}</dd></div><div><dt>Version</dt><dd><select value={versionId ?? ''} onChange={(e) => setVersionId(e.target.value)}>{document.versions.map((item) => <option key={item.id} value={item.id}>v{item.number} · {item.fileName}</option>)}</select></dd></div><div><dt>Størrelse</dt><dd>{version ? `${(version.size / 1024 / 1024).toFixed(2)} MB` : '—'}</dd></div><div><dt>Gyldig til</dt><dd>{document.validUntil || 'Ikke angivet'}</dd></div><div><dt>Relationer</dt><dd>{document.relations.map((item) => `${item.type}: ${item.id}`).join(', ')}</dd></div><div><dt>Bemærkninger</dt><dd>{document.notes || '—'}</dd></div></dl><div className="heading-actions">{url && <a className="primary-button" href={url} download={version.fileName}>Download</a>}<button className="secondary-button" onClick={() => setNewVersion(true)}>Ny version</button><button className="secondary-button" onClick={() => runMutation('updateDocument', document.id, document.revision, { archivedAt: document.archivedAt ? null : new Date().toISOString(), reason: document.archivedAt ? 'Gendannet' : 'Arkiveret af bruger' })}>{document.archivedAt ? 'Gendan' : 'Arkivér'}</button></div>{newVersion && <VersionDialog document={document} onClose={() => setNewVersion(false)} />}</aside>; }

function UploadDialog({ onClose }) { const { dataset, runMutation } = useFacilityData(); const options = relationOptions(dataset); const [form, setForm] = useState({ title: '', category: 'Andet', notes: '', validUntil: '', relations: [] }); const [files, setFiles] = useState([]); const [error, setError] = useState(null); const [drag, setDrag] = useState(false); const setPicked = (list) => setFiles([...list]); async function submit(event) { event.preventDefault(); try { await runMutation('createDocuments', form, files); onClose(); } catch (reason) { setError(reason); } }
  return <EntityDialog title="Upload dokumenter" description="PDF, JPEG, PNG og WebP højst 20 MB. MP4, WebM og MOV højst 100 MB." onClose={onClose} dirty wide><form className="entity-form" onSubmit={submit}><FormFeedback error={error} /><div className="form-grid two-columns"><Field label="Fælles titel" hint="Ved multifil-upload bruges filnavnet som titel."><input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></Field><Field label="Kategori"><select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}><option>Tegning</option><option>Manual</option><option>Rapport</option><option>Certifikat</option><option>Foto</option><option>Andet</option></select></Field><Field label="Gyldig til"><input type="date" value={form.validUntil} onChange={(e) => setForm({ ...form, validUntil: e.target.value })} /></Field><Field label="Bemærkninger"><input value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></Field><Field label="Filer" className="span-two"><label className={`drop-zone ${drag ? 'is-dragging' : ''}`} onDragOver={(e) => { e.preventDefault(); setDrag(true); }} onDragLeave={() => setDrag(false)} onDrop={(e) => { e.preventDefault(); setDrag(false); setPicked(e.dataTransfer.files); }}><input type="file" multiple accept="application/pdf,image/jpeg,image/png,image/webp,video/mp4,video/webm,video/quicktime" onChange={(e) => setPicked(e.target.files)} />Slip filer her eller vælg fra computeren<strong>{files.length ? `${files.length} fil(er) valgt` : 'Ingen filer valgt'}</strong></label></Field><Field label="Relationer" className="span-two"><div className="relation-picker">{options.map((item) => <label key={item.key}><input type="checkbox" checked={form.relations.some((entry) => entry.type === item.type && entry.id === item.id)} onChange={() => setForm((value) => ({ ...value, relations: value.relations.some((entry) => entry.type === item.type && entry.id === item.id) ? value.relations.filter((entry) => !(entry.type === item.type && entry.id === item.id)) : [...value.relations, { type: item.type, id: item.id }] }))} />{item.label}</label>)}</div></Field></div><footer className="dialog-actions"><button type="button" className="secondary-button" onClick={onClose}>Annuller</button><button className="primary-button" disabled={!files.length || !form.relations.length}>Upload</button></footer></form></EntityDialog>; }
function VersionDialog({ document, onClose }) { const { runMutation } = useFacilityData(); const [file, setFile] = useState(null); const [error, setError] = useState(null); async function submit(event) { event.preventDefault(); try { await runMutation('addDocumentVersion', document.id, document.revision, file); onClose(); } catch (reason) { setError(reason); } } return <EntityDialog title="Upload ny version" description="Den tidligere version bevares, og historiske vedhæftninger ændres ikke." onClose={onClose} dirty><form className="entity-form" onSubmit={submit}><FormFeedback error={error} /><Field label="Ny fil"><input type="file" onChange={(e) => setFile(e.target.files[0])} /></Field><footer className="dialog-actions"><button type="button" className="secondary-button" onClick={onClose}>Annuller</button><button className="primary-button" disabled={!file}>Gem ny version</button></footer></form></EntityDialog>; }
