import { useMemo, useState } from 'react';
import { useLocation, useSearchParams } from 'react-router-dom';
import { FacilityLink as Link, useFacilityNavigate as useNavigate } from '../routing/FacilityRouting';
import { InstallationForm } from '../components/facility/InstallationForm';
import { ProfileImage } from '../components/facility/ImageGallery';
import { Icon } from '../components/shared/Icon';
import { useFacilityData } from '../data/FacilityDataContext';
import { FUNCTION_STATUSES, getDescendantIds, getLocationPath, INSTALLATION_TYPES, LOCATION_TYPES } from '../domain/facilityDomain';

const collator = new Intl.Collator('da-DK', { numeric: true, sensitivity: 'base' });

function BranchFilter({ dataset, propertyId, selectedNode, onSelect }) {
  if (!propertyId) return <div className="empty-state compact"><strong>Vælg en ejendom</strong></div>;
  const property = dataset.properties.find((item) => item.id === propertyId); const nodes = dataset.locationNodes.filter((item) => item.propertyId === propertyId && !item.archivedAt);
  const render = (parentId = null, level = 0) => nodes.filter((item) => item.parentId === parentId).map((node) => <li key={node.id}><button type="button" className={selectedNode === node.id ? 'is-active' : ''} style={{ '--tree-level': level }} onClick={() => onSelect(node.id)}><Icon name={node.type === 'building' ? 'building' : 'map'} size={15} /><span>{node.name}<small>{LOCATION_TYPES[node.type]}</small></span></button>{render(node.id, level + 1).length > 0 && <ul>{render(node.id, level + 1)}</ul>}</li>);
  return <ul className="branch-filter"><li><button type="button" className={!selectedNode ? 'is-active' : ''} onClick={() => onSelect('')}><Icon name="building" size={16} /><span>{property.number} · {property.name}<small>Hele ejendommen</small></span></button><ul>{render()}</ul></li></ul>;
}

export function InstallationsPage() {
  const { dataset } = useFacilityData(); const [params, setParams] = useSearchParams(); const location = useLocation(); const navigate = useNavigate(); const [showCreate, setShowCreate] = useState(false);
  const propertyId = params.get('property') ?? ''; const nodeId = params.get('node') ?? ''; const search = params.get('q') ?? ''; const type = params.get('type') ?? ''; const functionStatus = params.get('function') ?? ''; const archive = params.get('archive') ?? 'active'; const sort = params.get('sort') ?? 'number'; const direction = params.get('dir') === 'desc' ? -1 : 1;
  const set = (name, value) => { const next = new URLSearchParams(params); if (value) next.set(name, value); else next.delete(name); if (name !== 'selected') next.delete('selected'); if (name === 'property') next.delete('node'); setParams(next); };
  const branchIds = nodeId ? new Set(getDescendantIds(dataset, nodeId, { includeSelf: true })) : null;
  const rows = useMemo(() => dataset.installations.filter((item) => {
    const haystack = [item.number, item.name, item.manufacturer, item.model, item.serialNumber].join(' ').toLocaleLowerCase('da-DK');
    return (!propertyId || item.propertyId === propertyId) && (!branchIds || (item.physicalLocationId && branchIds.has(item.physicalLocationId))) && (!search || haystack.includes(search.toLocaleLowerCase('da-DK'))) && (!type || item.type === type) && (!functionStatus || item.functionStatus === functionStatus) && (archive === 'all' || (archive === 'archived' ? item.archivedAt : !item.archivedAt));
  }).sort((a, b) => collator.compare(String(a[sort] ?? ''), String(b[sort] ?? '')) * direction), [archive, branchIds, dataset.installations, direction, functionStatus, propertyId, search, sort, type]);
  const selected = rows.find((item) => item.id === params.get('selected')) ?? rows[0]; const selectedProperty = selected && dataset.properties.find((item) => item.id === selected.propertyId);
  const changeSort = (field) => { const next = new URLSearchParams(params); next.set('sort', field); next.set('dir', sort === field && direction === 1 ? 'desc' : 'asc'); setParams(next); };
  return <div className="directory-page installation-directory"><div className="page-heading"><div><span className="eyebrow">FACILITY</span><h1>Installationer</h1><p>Filtrér på hele en gren, og hold fysisk placering, funktion og betjente områder adskilt.</p></div><button type="button" className="primary-button" onClick={() => setShowCreate(true)}>+ Ny installation</button></div>
    <div className="installation-filter-bar"><label className="filter-search"><Icon name="search" size={17} /><input aria-label="Søg i installationer" value={search} onChange={(event) => set('q', event.target.value)} placeholder="Søg nummer, navn, fabrikat, model eller serienr." /></label><select aria-label="Filtrer efter ejendom" value={propertyId} onChange={(event) => set('property', event.target.value)}><option value="">Alle ejendomme</option>{dataset.properties.filter((item) => !item.archivedAt).map((item) => <option key={item.id} value={item.id}>{item.number} · {item.name}</option>)}</select><select aria-label="Installationstype" value={type} onChange={(event) => set('type', event.target.value)}><option value="">Alle typer</option>{INSTALLATION_TYPES.map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Funktionstilstand" value={functionStatus} onChange={(event) => set('function', event.target.value)}><option value="">Alle funktionstilstande</option>{Object.entries(FUNCTION_STATUSES).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="Arkivering" value={archive} onChange={(event) => set('archive', event.target.value)}><option value="active">Aktive poster</option><option value="archived">Arkiverede poster</option><option value="all">Alle poster</option></select><button className="secondary-button" type="button" onClick={() => setParams({})}>Nulstil</button></div>
    <section className="installation-layout"><aside className="card branch-panel"><div className="section-heading"><div><h2>Ejendom og struktur</h2><p>Valgt node inkluderer hele grenen.</p></div></div>{propertyId ? <BranchFilter dataset={dataset} propertyId={propertyId} selectedNode={nodeId} onSelect={(id) => set('node', id)} /> : <div className="property-filter-list"><button className={!propertyId ? 'is-active' : ''} onClick={() => set('property', '')}>Alle ejendomme</button>{dataset.properties.filter((item) => !item.archivedAt).map((item) => <button key={item.id} onClick={() => set('property', item.id)}>{item.number} · {item.name}</button>)}</div>}</aside>
      <article className="card installation-list-panel"><div className="section-heading"><div><h2>Installationer ({rows.length})</h2><p>{nodeId ? 'Viser installationer i den valgte node og alle underliggende noder.' : 'Viser installationer i hele det valgte omfang.'}</p></div></div>{rows.length ? <div className="table-scroll"><table className="directory-table"><thead><tr><th><button onClick={() => changeSort('number')}>Nummer</button></th><th><button onClick={() => changeSort('name')}>Navn</button></th><th><button onClick={() => changeSort('type')}>Type</button></th><th>Ejendom</th><th>Fysisk placering</th><th><button onClick={() => changeSort('functionStatus')}>Funktion</button></th></tr></thead><tbody>{rows.map((item) => { const property = dataset.properties.find((entry) => entry.id === item.propertyId); return <tr key={item.id} className={`${selected?.id === item.id ? 'is-selected' : ''}${item.archivedAt ? ' is-archived' : ''}`} onClick={() => set('selected', item.id)}><td><button className="table-select" type="button">{item.number}</button></td><td><strong>{item.name}</strong>{item.archivedAt && <span className="archive-badge">Arkiveret</span>}</td><td>{item.type}</td><td>{property?.number}</td><td>{getLocationPath(dataset, item.propertyId, item.physicalLocationId)}</td><td><span className={`function-badge ${item.functionStatus}`}>{FUNCTION_STATUSES[item.functionStatus]}</span></td></tr>; })}</tbody></table></div> : <div className="empty-state"><strong>Ingen installationer matcher</strong><span>Justér søgning, filtre eller valgt gren.</span></div>}</article>
      {selected && <aside className="card installation-detail-panel"><ProfileImage entity={selected} /><div className="summary-copy"><span className={`function-badge ${selected.functionStatus}`}>{FUNCTION_STATUSES[selected.functionStatus]}</span><small>{selected.number}</small><h2>{selected.name}</h2><p>{selected.type}</p><dl><div><dt>Ejendom</dt><dd>{selectedProperty?.number} · {selectedProperty?.name}</dd></div><div><dt>Fysisk placering</dt><dd>{getLocationPath(dataset, selected.propertyId, selected.physicalLocationId)}</dd></div><div><dt>Betjener</dt><dd>{selected.servedAreaIds?.length || 0} valgte områder</dd></div><div><dt>Fabrikat/model</dt><dd>{[selected.manufacturer, selected.model].filter(Boolean).join(' · ') || 'Ikke angivet'}</dd></div></dl><Link className="primary-button full-width" to={`/facility/installationer/${selected.id}`} state={{ from: `${location.pathname}${location.search}` }}>Se installationsprofil <Icon name="chevron" size={16} /></Link></div></aside>}
    </section>{showCreate && <InstallationForm initialPropertyId={propertyId || undefined} initialLocationId={nodeId || undefined} onClose={() => setShowCreate(false)} onSaved={(item) => navigate(`/facility/installationer/${item.id}`, { state: { from: `${location.pathname}${location.search}` } })} />}
  </div>;
}
