import { useState } from 'react';
import { useLocation, useParams, useSearchParams } from 'react-router-dom';
import { FacilityLink as Link } from '../routing/FacilityRouting';
import { FormFeedback } from '../components/facility/EntityDialog';
import { HistoryPanel } from '../components/facility/HistoryPanel';
import { ImageGallery, ProfileImage } from '../components/facility/ImageGallery';
import { InstallationForm } from '../components/facility/InstallationForm';
import { ReasonDialog } from '../components/facility/ReasonDialog';
import { Icon } from '../components/shared/Icon';
import { useFacilityData } from '../data/FacilityDataContext';
import { FUNCTION_STATUSES, getLocationPath } from '../domain/facilityDomain';

function ServedAreas({ dataset, installation }) {
  if (!installation.servedAreaIds?.length) return <span className="not-specified">Ikke angivet</span>;
  return <ul className="served-area-list">{installation.servedAreaIds.map((id) => <li key={id}>{id === `property:${installation.propertyId}` ? 'Hele ejendommen' : getLocationPath(dataset, installation.propertyId, id)}</li>)}</ul>;
}

export function InstallationProfilePage() {
  const { installationId } = useParams(); const location = useLocation(); const [params, setParams] = useSearchParams(); const { dataset, runMutation } = useFacilityData();
  const [edit, setEdit] = useState(false); const [historyOpen, setHistoryOpen] = useState(false); const [archiveOpen, setArchiveOpen] = useState(false); const [error, setError] = useState(null);
  const installation = dataset.installations.find((item) => item.id === installationId); const back = location.state?.from ?? '/facility/installationer';
  if (!installation) return <div className="not-found-page card"><Icon name="installation" size={38} /><h1>Installationen blev ikke fundet</h1><p>Linket kan være forkert, eller installationen findes ikke i dette datasæt.</p><Link className="primary-button" to="/facility/installationer">Tilbage til Installationer</Link></div>;
  const property = dataset.properties.find((item) => item.id === installation.propertyId); const cases = dataset.cases.filter((item) => item.installationId === installation.id); const services = dataset.serviceOccurrences.filter((item) => item.installationId === installation.id); const tab = params.get('tab') ?? 'details'; const setTab = (value) => { const next = new URLSearchParams(params); if (value === 'details') next.delete('tab'); else next.set('tab', value); setParams(next, { replace: true }); };
  async function restore() { setError(null); try { await runMutation('restoreInstallation', installation.id, installation.revision); } catch (reason) { setError(reason); } }
  return <div className="profile-page"><div className="profile-breadcrumb"><Link to={back}>← Tilbage til Installationer</Link><Link to={`/facility/ejendomme/${property?.id}`}>{property?.number} · {property?.name}</Link><span>{installation.number}</span></div><div className="page-heading profile-heading"><div><span className="eyebrow">INSTALLATIONSPROFIL</span><h1>{installation.number} · {installation.name}</h1><p>{installation.type} · {getLocationPath(dataset, installation.propertyId, installation.physicalLocationId)}</p></div><div className="heading-actions"><button type="button" className="secondary-button" onClick={() => setHistoryOpen(true)}>Historik</button>{installation.archivedAt ? <button type="button" className="primary-button" onClick={restore}>Gendan installation</button> : <><button type="button" className="primary-button" onClick={() => setEdit(true)}>Rediger installation</button><button type="button" className="text-danger-button" onClick={() => setArchiveOpen(true)}>Arkivér</button></>}</div></div><FormFeedback error={error} />{installation.archivedAt && <div className="archive-notice"><strong>Installationen er arkiveret</strong><span>Profil, relationer og historik er bevaret.</span></div>}
    <section className="installation-profile-hero"><article className="card installation-image-card"><ProfileImage entity={installation} /><div><span className={`function-badge ${installation.functionStatus}`}>{FUNCTION_STATUSES[installation.functionStatus]}</span><h2>{installation.name}</h2><p>{installation.number} · {installation.type}</p></div></article><article className="card placement-card"><div><span className="placement-icon"><Icon name="map" size={22} /></span><div><small>Fysisk placering</small><strong>{getLocationPath(dataset, installation.propertyId, installation.physicalLocationId)}</strong><span>{property?.number} · {property?.name}</span></div></div><div><span className="placement-icon"><Icon name="building" size={22} /></span><div><small>Betjener</small><ServedAreas dataset={dataset} installation={installation} /></div></div></article><article className="card function-card"><span className={`function-dot large ${installation.functionStatus}`} /><div><small>Manuel funktionsvurdering</small><h2>{FUNCTION_STATUSES[installation.functionStatus]}</h2><p>{installation.functionNote || 'Ingen bemærkning angivet.'}</p><span>{installation.functionAssessedAt ? `Vurderet ${new Intl.DateTimeFormat('da-DK', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(installation.functionAssessedAt))}` : 'Ikke vurderet endnu'}</span></div></article></section>
    <nav className="profile-tabs"><div>{[['details', 'Detaljer'], ['service', 'Service'], ['cases', 'Sager'], ['documents', 'Dokumenter']].map(([id, label]) => <button type="button" key={id} className={tab === id ? 'is-active' : ''} onClick={() => setTab(id)}>{label}</button>)}</div></nav>
    {tab === 'details' && <div className="profile-content-grid"><section className="card profile-section"><div className="section-heading"><div><h2>Stamdata</h2><p>Relationsnøgler bruger det interne ID, ikke synlige numre.</p></div></div><dl className="detail-list two-column-details"><div><dt>Installationsnummer</dt><dd>{installation.number}</dd></div><div><dt>Type</dt><dd>{installation.type}</dd></div><div><dt>Fabrikat</dt><dd>{installation.manufacturer || 'Ikke angivet'}</dd></div><div><dt>Model</dt><dd>{installation.model || 'Ikke angivet'}</dd></div><div><dt>Serienummer</dt><dd>{installation.serialNumber || 'Ikke angivet'}</dd></div><div><dt>Anskaffelsesdato</dt><dd>{installation.acquisitionDate || 'Ikke angivet'}</dd></div><div><dt>Idriftsættelsesdato</dt><dd>{installation.commissioningDate || 'Ikke angivet'}</dd></div></dl><h3>Beskrivelse</h3><p>{installation.description || 'Ingen beskrivelse angivet.'}</p><h3>Tekniske bemærkninger</h3><p>{installation.technicalNotes || 'Ingen tekniske bemærkninger.'}</p></section><section className="card profile-section"><div className="section-heading"><div><h2>Serviceleverandør</h2><p>Stamdata; ingen bestilling, mail eller accept er oprettet.</p></div></div><dl className="detail-list"><div><dt>Leverandør</dt><dd>{installation.supplierName || 'Ikke angivet'}</dd></div><div><dt>Kontaktperson</dt><dd>{installation.supplierContactName || 'Ikke angivet'}</dd></div><div><dt>E-mail</dt><dd>{installation.supplierEmail || 'Ikke angivet'}</dd></div><div><dt>Telefon</dt><dd>{installation.supplierPhone || 'Ikke angivet'}</dd></div></dl><ImageGallery entityType="installation" entity={installation} /></section></div>}
    {tab === 'service' && <section className="card profile-section"><div className="section-heading"><div><h2>Service</h2><p>Servicefrist er separat fra installationens funktion.</p></div></div>{services.length ? <ul className="read-only-list">{services.map((item) => <li key={item.id}><strong>{item.activity}</strong><span>{item.dueDate} · {item.status}</span></li>)}</ul> : <div className="empty-state"><strong>Ingen servicepunkter</strong><span>Serviceautomatik kommer i etape 5.</span></div>}</section>}
    {tab === 'cases' && <section className="card profile-section"><div className="section-heading"><div><h2>Sager</h2><p>Læsende demodata; sagsworkflow kommer i etape 3.</p></div></div>{cases.length ? <ul className="read-only-list">{cases.map((item) => <li key={item.id}><strong>{item.reference} · {item.title}</strong><span>{item.status === 'closed' ? 'Lukket' : 'Åben'}</span></li>)}</ul> : <div className="empty-state"><strong>Ingen relaterede sager</strong></div>}</section>}
    {tab === 'documents' && <section className="card profile-section"><div className="empty-state"><strong>Dokumentregister kommer i etape 6</strong><span>Profilbilleder er allerede gemt som stabile mediereferencer.</span></div></section>}
    {edit && <InstallationForm installation={installation} onClose={() => setEdit(false)} />}{historyOpen && <HistoryPanel entityType="installation" entityId={installation.id} history={dataset.history} onClose={() => setHistoryOpen(false)} />}{archiveOpen && <ReasonDialog title={`Arkivér ${installation.number}`} description="Åbne sager, opgaver eller aktive servicebindinger skal afklares først." onClose={() => setArchiveOpen(false)} onConfirm={(reason) => runMutation('archiveInstallation', installation.id, installation.revision, reason)} />}
  </div>;
}
