import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import QRCode from 'qrcode';
import { useFacilityData } from '../data/FacilityDataContext';
import { ReportForm } from '../components/workflow/ReportForm';
import { PageTitle } from '../components/workflow/WorkflowShared';

export function MobileReportPage() {
  const { dataset } = useFacilityData(); const [params] = useSearchParams(); const [targetType, setTargetType] = useState(params.get('targetType') || 'installation'); const [targetId, setTargetId] = useState(params.get('targetId') || ''); const [qr, setQr] = useState('');
  const targets = useMemo(() => targetType === 'property' ? dataset.properties.filter((item) => !item.archivedAt) : targetType === 'location' ? dataset.locationNodes.filter((item) => !item.archivedAt) : dataset.installations.filter((item) => !item.archivedAt), [dataset, targetType]); const selected = targets.find((item) => item.id === targetId); const archivedOrUnknown = params.get('targetId') && !selected;
  const context = selected ? targetType === 'property' ? { propertyId: selected.id } : targetType === 'location' ? { propertyId: selected.propertyId, locationId: selected.id } : { propertyId: selected.propertyId, locationId: selected.physicalLocationId ?? '', installationId: selected.id } : {};
  useEffect(() => { if (!selected) { setQr(''); return; } const url = `${window.location.origin}/facility/mobil-indberetning?targetType=${encodeURIComponent(targetType)}&targetId=${encodeURIComponent(selected.id)}`; QRCode.toDataURL(url, { width: 280, margin: 2, color: { dark: '#061a2a', light: '#ffffff' } }).then(setQr); }, [selected, targetType]);
  return <main className="workflow-page mobile-report-page"><PageTitle title="Mobil indberetning" description="Manuelt valg fungerer altid. QR identificerer kun et mål og er ikke adgang til private oplysninger." />{archivedOrUnknown && <p className="form-feedback">QR-målet er ukendt eller arkiveret. Vælg et aktivt mål manuelt.</p>}<div className="mobile-report-layout"><section className="card qr-panel"><header><h2>QR til stabil identifikation</h2><p>Vælg ejendom, sted eller installation. Koden indeholder kun type og stabilt ID.</p></header><div className="segmented">{[['property', 'Ejendom'], ['location', 'Sted'], ['installation', 'Installation']].map(([value, label]) => <button key={value} className={targetType === value ? 'active' : ''} onClick={() => { setTargetType(value); setTargetId(''); }}>{label}</button>)}</div><select value={targetId} onChange={(e) => setTargetId(e.target.value)}><option value="">Vælg mål</option>{targets.map((item) => <option key={item.id} value={item.id}>{item.number ?? item.type} · {item.name}</option>)}</select>{qr ? <><img className="qr-image" src={qr} alt="QR-kode til mobil indberetning" /><a className="secondary-button full-width" href={qr} download={`facility-${targetType}-${selected.id}.png`}>Download QR</a></> : <div className="empty-state compact">Vælg et mål for at generere QR</div>}<p className="integration-note">QR-koden giver ikke adgang til sager. Denne lokale IndexedDB-prototype deler ikke data mellem computer og telefon.</p></section><section className="mobile-device-frame"><ReportForm mobile context={context} /></section></div></main>;
}
