import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useFacilityData } from '../data/FacilityDataContext';
import { PropertyForm } from '../components/facility/PropertyForm';
import { PageTitle } from '../components/workflow/WorkflowShared';

export function PropertyMapPage() { const { dataset } = useFacilityData(); const [selectedId, setSelectedId] = useState(dataset.properties.find((item) => item.latitude !== null)?.id ?? ''); const [editing, setEditing] = useState(null); const located = dataset.properties.filter((item) => Number.isFinite(item.latitude) && Number.isFinite(item.longitude)); const missing = dataset.properties.filter((item) => item.latitude === null || item.longitude === null); const selected = dataset.properties.find((item) => item.id === selectedId); const latitudes = located.map((item) => item.latitude); const longitudes = located.map((item) => item.longitude); const minLat = Math.min(...latitudes, 55.5); const maxLat = Math.max(...latitudes, 57); const minLon = Math.min(...longitudes, 9.5); const maxLon = Math.max(...longitudes, 11);
  const point = (item) => ({ x: 45 + ((item.longitude - minLon) / (maxLon - minLon || 1)) * 710, y: 445 - ((item.latitude - minLat) / (maxLat - minLat || 1)) * 390 });
  return <main className="workflow-page map-page"><PageTitle title="Ejendomskort" description="Faste, manuelt registrerede koordinater. Ingen GPS-sporing, geokodning eller bevægelseshistorik." /><div className="map-layout"><section className="card local-map"><header><span>Lokalt koordinatkort</span><small>Ingen eksterne kortfliser eller nøgler · ingen data sendes ud</small></header><svg viewBox="0 0 800 500" role="img" aria-label="Manuelt registrerede ejendomsplaceringer"><defs><pattern id="grid" width="50" height="50" patternUnits="userSpaceOnUse"><path d="M50 0H0V50" fill="none" stroke="#dce8eb" /></pattern></defs><rect width="800" height="500" fill="#eef5f6" /><rect width="800" height="500" fill="url(#grid)" />{located.map((item) => { const p = point(item); return <g key={item.id} transform={`translate(${p.x} ${p.y})`} onClick={() => setSelectedId(item.id)} className="map-marker"><circle r={selectedId === item.id ? 15 : 11} /><text x="18" y="4">{item.number} {item.name}</text></g>; })}</svg><footer>Koordinaterne er manuelt registrerede og ikke verificeret mod et offentligt register.</footer></section><aside className="card map-list"><h2>Ejendomme</h2>{located.map((item) => <button key={item.id} className={item.id === selectedId ? 'active' : ''} onClick={() => setSelectedId(item.id)}><strong>{item.number} · {item.name}</strong><span>{item.latitude.toFixed(5)}, {item.longitude.toFixed(5)}</span></button>)}{selected && <div className="map-selected"><Link className="primary-button full-width" to={`/facility/ejendomme/${selected.id}`}>Åbn profil</Link><button className="secondary-button full-width" onClick={() => setEditing(selected)}>Rediger koordinater</button></div>}<h3>Mangler koordinater ({missing.length})</h3>{missing.map((item) => <button key={item.id} onClick={() => setEditing(item)}><strong>{item.number} · {item.name}</strong><span>Tilføj manuel placering</span></button>)}</aside></div>{editing && <PropertyForm property={editing} onClose={() => setEditing(null)} />}</main>; }
