import { useState } from 'react';
import { Link, useLocation, useParams, useSearchParams } from 'react-router-dom';
import { HistoryPanel } from '../components/facility/HistoryPanel';
import { ImageGallery, ProfileImage } from '../components/facility/ImageGallery';
import { LocationTree } from '../components/facility/LocationTree';
import { PropertyForm } from '../components/facility/PropertyForm';
import { ReasonDialog } from '../components/facility/ReasonDialog';
import { FormFeedback } from '../components/facility/EntityDialog';
import { PropertyIllustration } from '../components/overview/PropertyIllustration';
import { Icon } from '../components/shared/Icon';
import { useFacilityData } from '../data/FacilityDataContext';
import { formatMoney } from '../data/overviewSelectors';
import { FUNCTION_STATUSES, getLocationPath } from '../domain/facilityDomain';

const tabs = [{ id: 'overview', label: 'Overblik' }, { id: 'installations', label: 'Installationer' }, { id: 'cases', label: 'Sager' }, { id: 'service', label: 'Service' }, { id: 'documents', label: 'Dokumenter' }, { id: 'economy', label: 'Økonomi' }];

function DetailList({ property }) {
  const area = property.registeredArea === null || property.registeredArea === undefined ? 'Ikke angivet' : `${new Intl.NumberFormat('da-DK', { maximumFractionDigits: 2 }).format(property.registeredArea)} m²`;
  return <dl className="detail-list"><div><dt>Ejendomstype</dt><dd>{property.type || 'Ikke angivet'}</dd></div><div><dt>Administrativ status</dt><dd>{property.administrativeStatus === 'active' ? 'Aktiv' : 'Inaktiv'}</dd></div><div><dt>Registreret areal</dt><dd>{area}</dd></div><div><dt>Opført</dt><dd>{property.constructionYear ?? 'Ikke angivet'}</dd></div><div><dt>Energimærke</dt><dd>{property.energyLabel || 'Ikke angivet'}</dd></div><div><dt>Ejendomsansvarlig</dt><dd>{property.managerName || 'Ikke angivet'}</dd></div><div><dt>E-mail</dt><dd>{property.managerEmail || 'Ikke angivet'}</dd></div><div><dt>Telefon</dt><dd>{property.managerPhone || 'Ikke angivet'}</dd></div></dl>;
}

export function PropertyProfilePage() {
  const { propertyId } = useParams(); const location = useLocation(); const [params, setParams] = useSearchParams(); const { dataset, runMutation } = useFacilityData();
  const [edit, setEdit] = useState(false); const [historyOpen, setHistoryOpen] = useState(false); const [archiveOpen, setArchiveOpen] = useState(false); const [error, setError] = useState(null);
  const property = dataset.properties.find((item) => item.id === propertyId); const back = location.state?.from ?? '/facility/ejendomme';
  if (!property) return <div className="not-found-page card"><Icon name="building" size={38} /><h1>Ejendommen blev ikke fundet</h1><p>Linket kan være forkert, eller posten findes ikke i dette FACILITY-datasæt.</p><Link className="primary-button" to="/facility/ejendomme">Tilbage til Ejendomme</Link></div>;
  const activeTab = params.get('tab') ?? 'overview'; const setTab = (id) => { const next = new URLSearchParams(params); if (id === 'overview') next.delete('tab'); else next.set('tab', id); setParams(next, { replace: true }); };
  const nodes = dataset.locationNodes.filter((item) => item.propertyId === property.id && !item.archivedAt); const installations = dataset.installations.filter((item) => item.propertyId === property.id && !item.archivedAt); const cases = dataset.cases.filter((item) => item.propertyId === property.id); const services = dataset.serviceOccurrences.filter((item) => item.propertyId === property.id); const costs = dataset.costs.filter((item) => item.propertyId === property.id && item.kind === 'registered_demo'); const registeredCosts = costs.reduce((sum, item) => sum + item.amount, 0);
  async function restore() { setError(null); try { await runMutation('restoreProperty', property.id, property.revision); } catch (reason) { setError(reason); } }
  return <div className="profile-page"><div className="profile-breadcrumb"><Link to={back}>← Tilbage til Ejendomme</Link><span>{property.number}</span></div><div className="page-heading profile-heading"><div><span className="eyebrow">EJENDOMSPROFIL</span><h1>{property.name}</h1><p>{property.number} · {property.address || 'Adresse ikke angivet'} · {property.postalCode} {property.city}</p></div><div className="heading-actions"><button type="button" className="secondary-button" onClick={() => setHistoryOpen(true)}>Historik</button>{property.archivedAt ? <button type="button" className="primary-button" onClick={restore}>Gendan ejendom</button> : <><button type="button" className="secondary-button" onClick={() => setEdit(true)}>Rediger ejendom</button><button type="button" className="text-danger-button" onClick={() => setArchiveOpen(true)}>Arkivér</button></>}</div></div><FormFeedback error={error} />{property.archivedAt && <div className="archive-notice"><strong>Ejendommen er arkiveret</strong><span>Eksisterende links og historik er bevaret. Nye relationer kan ikke oprettes.</span></div>}
    <section className="profile-hero-grid"><article className="card property-master-card"><ProfileImage entity={property} variant={property.illustration} fallback={(variant) => <PropertyIllustration variant={variant} />} /><div className="property-master-copy"><h2>{property.number} · {property.name}</h2><p><Icon name="map" size={16} /> {property.address || 'Adresse ikke angivet'}, {property.postalCode} {property.city}</p><DetailList property={property} /></div></article><article className="card profile-kpis"><h2>Beregnede nøgletal</h2><div><span><strong>{nodes.filter((item) => item.type === 'building').length}</strong>Bygninger</span><span><strong>{nodes.length}</strong>Aktive lokationsposter</span><span><strong>{installations.length}</strong>Installationer</span><span><strong>{cases.filter((item) => item.status !== 'closed').length}</strong>Åbne sager</span></div><small>Alle tal beregnes fra relationerne i FACILITY.</small></article></section>
    <nav className="profile-tabs" aria-label="Ejendomsprofil"><div>{tabs.map((tab) => <button type="button" key={tab.id} className={activeTab === tab.id ? 'is-active' : ''} onClick={() => setTab(tab.id)}>{tab.label}</button>)}</div></nav>
    {activeTab === 'overview' && <div className="profile-content-grid"><article className="card profile-section"><LocationTree property={property} /></article><article className="card profile-section"><div className="section-heading"><div><h2>Stamdata og beskrivelse</h2><p>Manuelt registrerede oplysninger</p></div></div><p>{property.description || 'Ingen beskrivelse angivet.'}</p>{property.notes && <div className="info-box"><Icon name="info" size={17} /><span>{property.notes}</span></div>}<ImageGallery entityType="property" entity={property} /></article></div>}
    {activeTab === 'installations' && <section className="card profile-section"><div className="section-heading"><div><h2>Installationer ({installations.length})</h2><p>Fysisk placering og funktion vises separat.</p></div><Link className="secondary-button" to={`/facility/installationer?property=${property.id}`}>Åbn installationsoversigt</Link></div>{installations.length ? <div className="profile-installation-grid">{installations.map((item) => <Link className="installation-summary-card" key={item.id} to={`/facility/installationer/${item.id}`}><span className={`function-dot ${item.functionStatus}`} /><div><strong>{item.number} · {item.name}</strong><small>{item.type} · {getLocationPath(dataset, item.propertyId, item.physicalLocationId)}</small><span>{FUNCTION_STATUSES[item.functionStatus]}</span></div><Icon name="chevron" size={17} /></Link>)}</div> : <div className="empty-state"><strong>Ingen installationer</strong><span>Opret installationer fra installationsoversigten.</span></div>}</section>}
    {activeTab === 'cases' && <section className="card profile-section"><div className="section-heading"><div><h2>Sager</h2><p>Læsende eksisterende demodata; workflow kommer i etape 3.</p></div></div>{cases.length ? <ul className="read-only-list">{cases.map((item) => <li key={item.id}><strong>{item.reference} · {item.title}</strong><span>{item.status === 'closed' ? 'Lukket' : 'Åben'}</span></li>)}</ul> : <div className="empty-state"><strong>Ingen relaterede sager</strong></div>}</section>}
    {activeTab === 'service' && <section className="card profile-section"><div className="section-heading"><div><h2>Service</h2><p>Læsende servicepunkter; automatik kommer i etape 5.</p></div></div>{services.length ? <ul className="read-only-list">{services.map((item) => <li key={item.id}><strong>{item.activity}</strong><span>{item.dueDate} · {item.supplier}</span></li>)}</ul> : <div className="empty-state"><strong>Ingen servicepunkter</strong></div>}</section>}
    {activeTab === 'documents' && <section className="card profile-section"><div className="empty-state"><strong>Dokumentregister kommer i etape 6</strong><span>Billeder gemmes allerede som stabile mediereferencer uden Base64 i datasættet.</span></div></section>}
    {activeTab === 'economy' && <section className="card profile-section"><div className="section-heading"><div><h2>Registrerede demoomkostninger</h2><p>Ikke fakturakontrollerede beløb; budget og estimater indgår ikke.</p></div><strong>{formatMoney(registeredCosts, dataset.financialPeriod.currency)}</strong></div>{costs.length ? <ul className="read-only-list">{costs.map((item) => <li key={item.id}><strong>{item.category}</strong><span>{item.date} · {formatMoney(item.amount, item.currency)}</span></li>)}</ul> : <div className="empty-state"><strong>Intet økonomisk datagrundlag</strong></div>}</section>}
    {edit && <PropertyForm property={property} onClose={() => setEdit(false)} />}{historyOpen && <HistoryPanel entityType="property" entityId={property.id} history={dataset.history} onClose={() => setHistoryOpen(false)} />}{archiveOpen && <ReasonDialog title={`Arkivér ${property.name}`} description="Ejendommen kan kun arkiveres, når lokationer, installationer og åbne relationer er afklaret." onClose={() => setArchiveOpen(false)} onConfirm={(reason) => runMutation('archiveProperty', property.id, property.revision, reason)} />}
  </div>;
}
