import { useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { FacilityLink as Link } from '../routing/FacilityRouting';
import { useFacilityData } from '../data/FacilityDataContext';
import { getLocationPath } from '../domain/facilityDomain';
import { PRIORITIES } from '../domain/workflowDomain';
import { ReportForm } from '../components/workflow/ReportForm';
import { EntityPath, PageTitle, PriorityBadge, RelatedDocuments } from '../components/workflow/WorkflowShared';
import { FormFeedback } from '../components/facility/EntityDialog';

export function ReportsPage() {
  const { dataset, runMutation } = useFacilityData(); const [params, setParams] = useSearchParams(); const [create, setCreate] = useState(false); const [error, setError] = useState(null); const [success, setSuccess] = useState('');
  const query = params.get('q') ?? ''; const state = params.get('state') ?? ''; const reports = useMemo(() => dataset.reports.filter((item) => (!query || `${item.reference} ${item.title} ${item.description}`.toLocaleLowerCase('da-DK').includes(query.toLocaleLowerCase('da-DK'))) && (!state || item.status === state)).sort((a, b) => b.createdAt.localeCompare(a.createdAt)), [dataset.reports, query, state]);
  const selected = reports.find((item) => item.id === params.get('report')) ?? reports[0]; const caseRecord = selected && dataset.cases.find((item) => item.id === selected.caseId); const [form, setForm] = useState(null);
  const triage = form ?? (caseRecord ? { priority: caseRecord.priority, category: caseRecord.category, responsibleId: caseRecord.responsibleId, dueDate: caseRecord.dueDate, notes: caseRecord.notes, status: caseRecord.status, statusReason: '' } : null);
  const setTriage = (field) => (event) => setForm({ ...triage, [field]: event.target.value });
  async function save() { setError(null); setSuccess(''); try { await runMutation('updateCase', caseRecord.id, caseRecord.revision, triage); setForm(null); setSuccess('Vurderingen er gemt på den fælles sag.'); } catch (reason) { setError(reason); } }
  return <div className="workflow-page"><PageTitle title="Indberetninger og triage" description="Modtag, vurder og prioritér indberetninger fra brugere og drift." action={<button className="primary-button" onClick={() => setCreate(true)}>+ Ny indberetning</button>} />
    <div className="triage-layout"><section className="card triage-list"><h2>Indberetninger</h2><div className="compact-filters"><input aria-label="Søg indberetninger" placeholder="Søg indberetninger …" value={query} onChange={(event) => { const next = new URLSearchParams(params); event.target.value ? next.set('q', event.target.value) : next.delete('q'); setParams(next); }} /><select aria-label="Status" value={state} onChange={(event) => { const next = new URLSearchParams(params); event.target.value ? next.set('state', event.target.value) : next.delete('state'); setParams(next); }}><option value="">Alle</option><option value="received">Nye</option><option value="triaged">Vurderede</option></select></div>{reports.length ? <ul className="master-list">{reports.map((item) => <li key={item.id}><button className={selected?.id === item.id ? 'is-active' : ''} onClick={() => { const next = new URLSearchParams(params); next.set('report', item.id); setParams(next); setForm(null); }}><span><strong>{item.title}</strong><small><EntityPath dataset={dataset} record={item} /></small><small>{item.contactName ? `Af: ${item.contactName}` : 'Kontakt ikke angivet'}</small></span><time>{new Date(item.createdAt).toLocaleDateString('da-DK')}</time></button></li>)}</ul> : <div className="empty-state"><strong>Ingen indberetninger</strong><span>Opret en desktop- eller mobilindberetning.</span></div>}</section>
      <section className="card triage-detail">{selected && caseRecord ? <><header><div><span className="eyebrow">{caseRecord.reference}</span><h2>{selected.title}</h2><EntityPath dataset={dataset} record={selected} /></div><Link className="secondary-button" to={`/facility/sager/${caseRecord.id}`}>Åbn sag</Link></header><div className="detail-tabs"><span>Indberetning</span><span>Bilag ({selected.attachmentVersionIds.length})</span><span>Historik</span></div><h3>Original indberetning</h3><dl className="detail-list"><div><dt>Oplevet alvorlighed</dt><dd>{selected.reporterSeverity}</dd></div><div><dt>Observeret</dt><dd>{new Date(selected.observedAt).toLocaleString('da-DK')}</dd></div><div><dt>Kategori</dt><dd>{selected.category}</dd></div><div><dt>Placering</dt><dd>{selected.locationId ? getLocationPath(dataset, selected.propertyId, selected.locationId) : 'Ejendommen generelt'}</dd></div></dl><p className="report-description">{selected.description}</p><h3>Vedhæftede filer</h3><RelatedDocuments dataset={dataset} versionIds={selected.attachmentVersionIds} /></> : <div className="empty-state"><strong>Vælg en indberetning</strong></div>}</section>
      <aside className="card triage-editor">{caseRecord && triage ? <><h2>Triage og vurdering</h2><FormFeedback error={error} success={success} /><label>Prioritet<select value={triage.priority} onChange={setTriage('priority')}>{Object.entries(PRIORITIES).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><div className="priority-preview"><PriorityBadge value={triage.priority} /><small>Ingen faste svartidsløfter er konfigureret.</small></div><label>Kategori<input value={triage.category} onChange={setTriage('category')} /></label><label>Ansvarlig<select value={triage.responsibleId} onChange={setTriage('responsibleId')}><option value="">Ikke tildelt</option>{dataset.resources.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Frist<input type="date" value={triage.dueDate} onChange={setTriage('dueDate')} /></label><label>Status<select value={triage.status} onChange={setTriage('status')}><option value="new">Ny</option><option value="triage">Under vurdering</option><option value="ready">Klar til udførelse</option><option value="inProgress">I gang</option><option value="awaitingInvoice">Afventer fakturaafklaring</option></select></label>{triage.status !== caseRecord.status && <label>Begrund statusændring<input value={triage.statusReason} onChange={setTriage('statusReason')} /></label>}<label>Intern note<textarea rows="5" value={triage.notes} onChange={setTriage('notes')} /></label><button className="primary-button full-width" onClick={save}>Gem vurdering</button></> : <div className="empty-state"><strong>Ingen sag valgt</strong></div>}</aside></div>{create && <ReportForm onClose={() => setCreate(false)} />}
  </div>;
}
