import { useState } from 'react';
import { useParams } from 'react-router-dom';
import { FacilityLink as Link } from '../routing/FacilityRouting';
import { useFacilityData } from '../data/FacilityDataContext';
import { EntityDialog, Field, FormFeedback } from '../components/facility/EntityDialog';
import { DocumentVersionPicker, EntityPath, PageTitle, RelatedDocuments, TaskBadge } from '../components/workflow/WorkflowShared';

export function TaskPage() {
  const { taskId } = useParams(); const { dataset, runMutation } = useFacilityData(); const task = dataset.tasks.find((item) => item.id === taskId); const [dialog, setDialog] = useState(''); const [error, setError] = useState('');
  if (!task) return <main className="workflow-page"><PageTitle title="Opgaven blev ikke fundet" description="Det angivne ID findes ikke i de lokale FACILITY-data." /><Link className="secondary-button" to="/facility/opgaver">Tilbage</Link></main>;
  const caseRecord = dataset.cases.find((item) => item.id === task.caseId); const resource = dataset.resources.find((item) => item.id === task.resourceId); const supplier = dataset.suppliers.find((item) => item.id === task.supplierId); const contact = supplier?.contacts?.find((item) => item.id === task.contactId);
  async function mutate(operation, input = {}) { setError(''); try { await runMutation('appendWork', task.id, task.revision, operation, input); setDialog(''); } catch (e) { setError(e.message); } }
  return <main className="workflow-page task-execution"><div className="profile-breadcrumb"><Link to="/facility/opgaver">Opgaver</Link>{caseRecord && <Link to={`/facility/sager/${caseRecord.id}`}>{caseRecord.reference}</Link>}<span>{task.taskNumber}</span></div><PageTitle title="Opgave og udførelse" description="Registrér arbejde og dokumentation. Afslutning af arbejdet lukker ikke sagen." action={<div className="heading-actions"><TaskBadge value={task.status} />{task.status === 'planned' || task.status === 'ready' ? <button className="primary-button" onClick={() => mutate('start')}>Start arbejde</button> : task.status === 'inProgress' ? <button className="primary-button" onClick={() => setDialog('complete')}>Afslut arbejde</button> : null}</div>} />
    <section className="card task-identity-strip"><div><small>Opgave</small><strong>{task.taskNumber}</strong></div><div><small>Bestilling</small><strong>{task.orderNumber || 'Ikke relevant'}</strong></div><div><small>Sag</small><strong>{caseRecord?.reference || 'Uden sag'}</strong></div><div><small>Placering</small><strong><EntityPath dataset={dataset} record={task} /></strong></div><div><small>Tildelt</small><strong>{supplier?.name || resource?.name || 'Ikke tildelt'}</strong></div></section>
    {error && <p className="form-feedback">{error}</p>}<div className="task-work-grid"><div className="task-left-stack"><section className="card workflow-section"><header><h2>Beskrivelse</h2></header><p>{task.description || task.title}</p></section><section className="card workflow-section"><header><h2>Tjekliste</h2><span>{task.checklist.filter((item) => item.done).length} af {task.checklist.length}</span></header>{task.checklist.map((item) => <label className="check-row" key={item.id}><input type="checkbox" checked={item.done} onChange={() => mutate('check', { id: item.id })} />{item.label}</label>)}</section><section className="card workflow-section"><header><h2>Materialer</h2><button className="secondary-button" onClick={() => setDialog('material')}>+ Tilføj</button></header><table><thead><tr><th>Vare</th><th>Antal</th><th>Enhed</th><th>Enhedspris</th><th>Linje</th></tr></thead><tbody>{task.materials.map((item) => <tr key={item.id}><td>{item.name}</td><td>{item.quantity}</td><td>{item.unit}</td><td>{item.unitPrice === null ? 'Ukendt' : `${item.unitPrice.toLocaleString('da-DK')} kr.`}</td><td>{item.total === null ? 'Ukendt' : `${item.total.toLocaleString('da-DK')} kr.`}</td></tr>)}</tbody></table></section></div>
      <div className="task-middle-stack"><section className="card workflow-section"><header><h2>Tidslinje</h2></header><div className="timeline compact">{dataset.history.filter((item) => item.entityId === task.id).sort((a, b) => a.timestamp.localeCompare(b.timestamp)).map((item) => <div key={item.id}><time>{new Date(item.timestamp).toLocaleString('da-DK')}</time><strong>{item.action}</strong><span>{item.reason}</span></div>)}</div></section><section className="card workflow-section"><header><h2>Tidsforbrug</h2><button className="secondary-button" onClick={() => setDialog('time')}>+ Tid</button></header><table><thead><tr><th>Dato</th><th>Ressource</th><th>Timer</th><th>Kostsats</th></tr></thead><tbody>{task.timeEntries.map((item) => <tr key={item.id}><td>{item.date}</td><td>{dataset.resources.find((r) => r.id === item.resourceId)?.name}</td><td>{item.hours}</td><td>{item.hourlyCost === null ? 'Ukendt' : `${item.hourlyCost} kr./t.`}</td></tr>)}</tbody></table></section><section className="card workflow-section"><header><h2>Løsning</h2></header>{task.completedAt ? <><p><strong>{task.solution}</strong></p><p>{task.remainingRestrictions}</p><p className="integration-note">Arbejdet er afsluttet. Sagen er fortsat {caseRecord?.status === 'closed' ? 'lukket' : 'åben'}.</p></> : <p className="muted-copy">Løsningsbeskrivelse registreres ved afslutning.</p>}</section></div>
      <div className="task-right-stack"><section className="card workflow-section"><header><h2>Arbejdslog</h2><button className="secondary-button" onClick={() => setDialog('log')}>+ Tilføj log</button></header>{task.workLogs.map((item) => <div className="log-row" key={item.id}><time>{new Date(item.timestamp).toLocaleString('da-DK')}</time><strong>{dataset.resources.find((r) => r.id === item.resourceId)?.name || supplier?.name}</strong><span>{item.note}</span></div>)}</section><section className="card workflow-section"><header><h2>Dokumentation</h2><Link className="row-link" to={`/facility/dokumenter?task=${task.id}`}>Åbn register</Link></header><RelatedDocuments dataset={dataset} versionIds={task.attachmentVersionIds} /></section>{task.assignmentType === 'external' && <section className="card workflow-section mail-summary"><header><h2>Tildeling og mailklargøring</h2><button className="secondary-button" onClick={() => setDialog('mail')}>{task.mailDraft ? 'Rediger kladde' : 'Klargør mail'}</button></header><dl><div><dt>Leverandør</dt><dd>{supplier?.name}</dd></div><div><dt>Kontakt</dt><dd>{contact?.name || 'Ikke valgt'}</dd></div><div><dt>Status</dt><dd>{task.mailDraft ? `Kladde v${task.mailDraft.version} · Ikke afsendt` : 'Ingen kladde'}</dd></div><div><dt>Accept</dt><dd>{task.acceptance ? `${task.acceptance.source} · ${new Date(task.acceptance.recordedAt).toLocaleString('da-DK')}` : 'Ikke registreret'}</dd></div></dl>{!task.acceptance && <button className="secondary-button full-width" onClick={async () => { const source = window.prompt('Angiv reel kilde til leverandørens accept'); if (source) await runMutation('recordSupplierAcceptance', task.id, task.revision, source); }}>Registrér accept med kilde</button>}</section>}</div></div>
    {dialog === 'log' && <SimpleWorkDialog title="Tilføj arbejdslog" fields="log" task={task} onClose={() => setDialog('')} onSubmit={(input) => mutate('log', input)} />}{dialog === 'time' && <SimpleWorkDialog title="Registrér tid" fields="time" task={task} onClose={() => setDialog('')} onSubmit={(input) => mutate('time', input)} />}{dialog === 'material' && <SimpleWorkDialog title="Tilføj materiale" fields="material" task={task} onClose={() => setDialog('')} onSubmit={(input) => mutate('material', input)} />}{dialog === 'complete' && <SimpleWorkDialog title="Afslut arbejde" fields="complete" task={task} onClose={() => setDialog('')} onSubmit={(input) => mutate('complete', input)} />}{dialog === 'mail' && <MailDraftDialog task={task} caseRecord={caseRecord} supplier={supplier} contact={contact} onClose={() => setDialog('')} />}
  </main>;
}

function SimpleWorkDialog({ title, fields, task, onClose, onSubmit }) {
  const { dataset } = useFacilityData(); const [form, setForm] = useState({ note: '', resourceId: task.resourceId || dataset.resources[0]?.id, date: new Date().toISOString().slice(0, 10), hours: '1', hourlyCost: '', name: '', quantity: '1', unit: 'stk.', unitPrice: '', solution: '', restrictionDecision: '', remainingRestrictions: '' }); const [error, setError] = useState(null);
  const submit = async (event) => { event.preventDefault(); try { await onSubmit(form); } catch (reason) { setError(reason); } };
  return <EntityDialog title={title} description={fields === 'complete' ? 'Arbejdet afsluttes, men sagen forbliver åben.' : 'Registreringen indgår i opgavens historik.'} onClose={onClose} dirty><form className="entity-form" onSubmit={submit}><FormFeedback error={error} /><div className="form-grid">{fields === 'log' && <Field label="Notat" required><textarea value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} /></Field>}{fields === 'time' && <><Field label="Dato"><input type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></Field><Field label="Ressource"><select value={form.resourceId} onChange={(e) => setForm({ ...form, resourceId: e.target.value })}>{dataset.resources.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Timer"><input type="number" min="0.01" step="0.25" value={form.hours} onChange={(e) => setForm({ ...form, hours: e.target.value })} /></Field><Field label="Kostsats ekskl. moms (valgfri)"><input type="number" min="0" value={form.hourlyCost} onChange={(e) => setForm({ ...form, hourlyCost: e.target.value })} /></Field></>}{fields === 'material' && <><Field label="Materiale"><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><Field label="Antal"><input type="number" min="0.01" step="0.01" value={form.quantity} onChange={(e) => setForm({ ...form, quantity: e.target.value })} /></Field><Field label="Enhed"><input value={form.unit} onChange={(e) => setForm({ ...form, unit: e.target.value })} /></Field><Field label="Enhedspris ekskl. moms (valgfri)"><input type="number" min="0" value={form.unitPrice} onChange={(e) => setForm({ ...form, unitPrice: e.target.value })} /></Field></>}{fields === 'complete' && <><Field label="Løsningsbeskrivelse" required><textarea rows="4" value={form.solution} onChange={(e) => setForm({ ...form, solution: e.target.value })} /></Field><Field label="Resterende begrænsninger"><select value={form.restrictionDecision} onChange={(e) => setForm({ ...form, restrictionDecision: e.target.value })}><option value="">Tag stilling</option><option value="none">Ingen resterende begrænsninger</option><option value="remaining">Der er resterende begrænsninger</option></select></Field>{form.restrictionDecision === 'remaining' && <Field label="Beskriv begrænsningerne"><textarea value={form.remainingRestrictions} onChange={(e) => setForm({ ...form, remainingRestrictions: e.target.value })} /></Field>}</>}</div><footer className="dialog-actions"><button type="button" className="secondary-button" onClick={onClose}>Annuller</button><button className="primary-button">Gem</button></footer></form></EntityDialog>;
}

function MailDraftDialog({ task, caseRecord, contact, onClose }) {
  const { dataset, runMutation } = useFacilityData(); const base = task.mailDraft ?? {}; const [form, setForm] = useState({ to: base.to ?? contact?.email ?? '', cc: base.cc ?? '', subject: base.subject ?? `Bestilling ${task.orderNumber} · ${caseRecord?.reference}`, body: base.body ?? `Hej ${contact?.name ?? ''}\n\nHermed klargøres bestilling ${task.orderNumber} vedrørende ${task.title}.\nSagsreference: ${caseRecord?.reference}\nPlacering: ${caseRecord?.historicalLocationSnapshot}\n\nDette er en kladde og er ikke afsendt.`, attachmentVersionIds: base.attachmentVersionIds ?? task.attachmentVersionIds }); const [error, setError] = useState(null); const [saved, setSaved] = useState(false);
  async function save() { try { await runMutation('saveMailDraft', task.id, task.revision, form); setSaved(true); } catch (reason) { setError(reason); } }
  return <EntityDialog title="Tildeling og mailklargøring" description="Kladde og forhåndsvisning. Der sendes ingen rigtig mail." onClose={onClose} dirty wide><div className="entity-form mail-draft-grid"><div className="form-grid"><FormFeedback error={error} />{saved && <p className="form-feedback is-success">Kladde gemt. Status er fortsat Ikke afsendt.</p>}<Field label="Til"><input value={form.to} onChange={(e) => setForm({ ...form, to: e.target.value })} /></Field><Field label="Cc"><input value={form.cc} onChange={(e) => setForm({ ...form, cc: e.target.value })} /></Field><Field label="Emne"><input value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} /></Field><Field label="Besked"><textarea rows="11" value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} /></Field><Field label="Konkrete dokumentversioner"><DocumentVersionPicker dataset={dataset} selected={form.attachmentVersionIds} onChange={(attachmentVersionIds) => setForm({ ...form, attachmentVersionIds })} /></Field></div><aside className="mail-preview"><small>KLADDE · IKKE AFSENDT</small><h3>{form.subject || 'Intet emne'}</h3><p><b>Til:</b> {form.to}</p><pre>{form.body}</pre><p>{form.attachmentVersionIds.length} vedhæftede version(er)</p><button className="secondary-button" onClick={() => navigator.clipboard?.writeText(`${form.subject}\n\n${form.body}`)}>Kopiér tekst</button></aside><footer className="dialog-actions span-two"><button type="button" className="secondary-button" onClick={onClose}>Luk</button><button type="button" className="primary-button" onClick={save}>Gem kladde</button></footer></div></EntityDialog>;
}
