import { useMemo, useState } from 'react';
import { FacilityLink as Link } from '../routing/FacilityRouting';
import { useFacilityData } from '../data/FacilityDataContext';
import { EntityDialog, Field, FormFeedback } from '../components/facility/EntityDialog';
import { CaseBadge, EntityPath, PageTitle, PriorityBadge } from '../components/workflow/WorkflowShared';
import { CASE_STATUSES } from '../domain/workflowDomain';

const columns = ['new', 'triage', 'ready', 'inProgress', 'awaitingInvoice'];
const priorityOrder = { acute: 0, high: 1, normal: 2, low: 3 };
export function WorkQueuePage() {
  const { dataset } = useFacilityData(); const [view, setView] = useState('kanban'); const [query, setQuery] = useState(''); const [propertyId, setPropertyId] = useState(''); const [status, setStatus] = useState(''); const [priority, setPriority] = useState(''); const [responsibleId, setResponsibleId] = useState(''); const [sort, setSort] = useState('priority'); const [createOpen, setCreateOpen] = useState(false);
  const rows = useMemo(() => dataset.cases
    .filter((item) => item.status !== 'closed'
      && (!query || `${item.reference} ${item.title}`.toLowerCase().includes(query.toLowerCase()))
      && (!propertyId || item.propertyId === propertyId)
      && (!status || item.status === status)
      && (!priority || item.priority === priority)
      && (!responsibleId || item.responsibleId === responsibleId))
    .sort((a, b) => sort === 'due'
      ? String(a.dueDate || '9999').localeCompare(String(b.dueDate || '9999'))
      : sort === 'created'
        ? String(b.createdAt || '').localeCompare(String(a.createdAt || ''))
        : (priorityOrder[a.priority] ?? 9) - (priorityOrder[b.priority] ?? 9)), [dataset.cases, propertyId, priority, query, responsibleId, sort, status]);
  const openCases = dataset.cases.filter((item) => item.status !== 'closed');
  return <main className="workflow-page facility-queue-page"><PageTitle title="Arbejdskø" description="Følg de samme sager fra vurdering til afsluttet arbejde. Fakturaafklaring er en særskilt tilstand." action={<div className="heading-actions"><button className="secondary-button" onClick={() => setCreateOpen(true)}>+ Manuel sag</button><div className="facility-queue-view-switch" aria-label="Visning"><button aria-pressed={view === 'kanban'} onClick={() => setView('kanban')}>Kanban</button><button aria-pressed={view === 'table'} onClick={() => setView('table')}>Tabel</button></div></div>} />
    <section className="facility-queue-kpis" aria-label="Nøgletal for arbejdskø"><article><span>Samlede sager</span><strong>{openCases.length}</strong></article><article><span>Kræver handling</span><strong>{openCases.filter((item) => ['new', 'triage'].includes(item.status)).length}</strong></article><article><span>Klar til udførelse</span><strong>{openCases.filter((item) => item.status === 'ready').length}</strong></article><article><span>Afventer faktura</span><strong>{openCases.filter((item) => item.status === 'awaitingInvoice').length}</strong></article></section>
    <div className="card facility-queue-toolbar"><input aria-label="Søg i sager" placeholder="Søg i sager …" value={query} onChange={(e) => setQuery(e.target.value)} /><select aria-label="Ejendom" value={propertyId} onChange={(e) => setPropertyId(e.target.value)}><option value="">Alle ejendomme</option>{dataset.properties.map((item) => <option key={item.id} value={item.id}>{item.number} {item.name}</option>)}</select><select aria-label="Status" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Alle statusser</option>{Object.entries(CASE_STATUSES).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="Prioritet" value={priority} onChange={(e) => setPriority(e.target.value)}><option value="">Alle prioriteter</option><option value="acute">Akut</option><option value="high">Høj</option><option value="normal">Normal</option><option value="low">Lav</option></select><select aria-label="Ansvarlig" value={responsibleId} onChange={(e) => setResponsibleId(e.target.value)}><option value="">Alle ansvarlige</option>{dataset.resources.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Sortering" value={sort} onChange={(e) => setSort(e.target.value)}><option value="priority">Prioritet</option><option value="created">Oprettet</option><option value="due">Frist</option></select></div>
    {view === 'kanban' ? <div className="facility-queue-board" aria-label="Kanbanvisning">{columns.map((columnStatus) => <section key={columnStatus} className={`facility-queue-column status-${columnStatus}`}><header><strong>{CASE_STATUSES[columnStatus]}</strong><span>{rows.filter((item) => item.status === columnStatus).length}</span></header><div>{rows.filter((item) => item.status === columnStatus).map((item) => <Link className="facility-queue-card" key={item.id} to={`/facility/sager/${item.id}`}><small>{item.reference}</small><strong>{item.title}</strong><EntityPath dataset={dataset} record={item} /><footer><PriorityBadge value={item.priority} /><span>{item.dueDate || 'Ingen frist'}</span></footer></Link>)}</div></section>)}</div> : <div className="card table-scroll facility-queue-table"><table><thead><tr><th>Reference</th><th>Sag</th><th>Ejendom og placering</th><th>Prioritet</th><th>Status</th><th>Frist</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td><Link className="row-link" to={`/facility/sager/${item.id}`}>{item.reference}</Link></td><td>{item.title}</td><td><EntityPath dataset={dataset} record={item} /></td><td><PriorityBadge value={item.priority} /></td><td><CaseBadge value={item.status} /></td><td>{item.dueDate || '—'}</td></tr>)}</tbody></table></div>}
    {createOpen && <ManualCaseDialog onClose={() => setCreateOpen(false)} />}
  </main>;
}

function ManualCaseDialog({ onClose }) {
  const { dataset, runMutation } = useFacilityData(); const [form, setForm] = useState({ title: '', description: '', propertyId: dataset.properties.find((item) => !item.archivedAt)?.id ?? '', locationId: '', installationId: '', priority: 'normal', category: 'Andet' }); const [error, setError] = useState(null);
  const change = (name) => (event) => setForm((value) => ({ ...value, [name]: event.target.value }));
  async function submit(event) { event.preventDefault(); try { await runMutation('createManualCase', form); onClose(); } catch (reason) { setError(reason); } }
  const locations = dataset.locationNodes.filter((item) => item.propertyId === form.propertyId && !item.archivedAt); const installations = dataset.installations.filter((item) => item.propertyId === form.propertyId && !item.archivedAt);
  return <EntityDialog title="Opret manuel sag" description="Kilden markeres tydeligt som manuel; der oprettes ingen indberetning." onClose={onClose} dirty><form className="entity-form" onSubmit={submit}><FormFeedback error={error} /><div className="form-grid"><Field label="Titel" required><input value={form.title} onChange={change('title')} /></Field><Field label="Beskrivelse"><textarea value={form.description} onChange={change('description')} /></Field><Field label="Ejendom" required><select value={form.propertyId} onChange={change('propertyId')}>{dataset.properties.filter((item) => !item.archivedAt).map((item) => <option key={item.id} value={item.id}>{item.number} {item.name}</option>)}</select></Field><Field label="Sted"><select value={form.locationId} onChange={change('locationId')}><option value="">Direkte på ejendommen</option>{locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Installation"><select value={form.installationId} onChange={change('installationId')}><option value="">Ingen installation</option>{installations.map((item) => <option key={item.id} value={item.id}>{item.number} {item.name}</option>)}</select></Field><Field label="Prioritet"><select value={form.priority} onChange={change('priority')}><option value="acute">Akut</option><option value="high">Høj</option><option value="normal">Normal</option><option value="low">Lav</option></select></Field></div><footer className="dialog-actions"><button type="button" className="secondary-button" onClick={onClose}>Annuller</button><button className="primary-button">Opret sag</button></footer></form></EntityDialog>;
}
