import { useEffect, useState } from "react";
import { Knap, Kort, Pille } from "../../fleet/ui.jsx";
import { hentSalgsplatform, synkroniserMicrosoft365 } from "../../fleet/ejer-salgsindbakke.js";

const status = (v) => v === "aktiv" ? "Aktiv" : "Ikke tilsluttet";
export default function EjerIntegrationer() {
  const [data, setData] = useState(null); const [svar, setSvar] = useState(null); const hent = async () => setData(await hentSalgsplatform());
  useEffect(() => { hent(); }, []); const m = data?.integrationer?.microsoft365 || {}; const ai = data?.integrationer?.openai || {};
  const forbrug = Object.entries(data?.aiForbrug || {}).sort(([a], [b]) => b.localeCompare(a))[0];
  const synk = async () => { const r = await synkroniserMicrosoft365(); setSvar(r); if (r.ok) await hent(); };
  return <div className="fc-grid ejer-overblik-grid"><Kort titel="Microsoft 365" handling={<Pille>{status(m.status)}</Pille>}><div className="ejer-statuslinjer"><div><span>Salgsadresse</span><strong>info@veyrosystems.com</strong></div><div><span>Postkassetype</span><strong>{m.mailboxType || "Ikke verificeret"}</strong></div><div><span>Mailbox-id</span><strong>{m.mailboxId ? "Registreret serverkonfiguration" : "Mangler"}</strong></div><div><span>Seneste synk</span><strong>{m.senesteSuccesMs ? new Date(m.senesteSuccesMs).toLocaleString("da-DK") : "Aldrig"}</strong></div></div><p className="fc-hint">Tilbud og salgsmail går via Microsoft 365. HTTP 202 vises kun som accepteret anmodning; Sendt post dokumenterer afsendelsen.</p><Knap onClick={synk} disabled={m.status !== "aktiv"}>Synkronisér Inbox og Sendt post</Knap>{m.senesteFejl && <p className="fc-fejltekst">{m.senesteFejl}</p>}{svar && !svar.ok && <p className="fc-fejltekst">{svar.besked}</p>}</Kort><Kort titel="OpenAI" handling={<Pille>{status(ai.status)}</Pille>}><div className="ejer-statuslinjer"><div><span>Model</span><strong>{ai.model || "Ikke valgt"}</strong></div><div><span>Forbrugsgrænse</span><strong>{ai.graense ? `${ai.graense.requests || 0} kald / måned` : "Ikke konfigureret"}</strong></div><div><span>Seneste måned</span><strong>{forbrug ? `${forbrug[0]} · ${forbrug[1].requests || 0} kald · ${(forbrug[1].inputTokens || 0) + (forbrug[1].outputTokens || 0)} tokens` : "Intet forbrug"}</strong></div></div><p className="fc-hint">Kun den aktuelle sag og godkendt, versioneret Veyro-viden sendes. `store: false` bruges. Mail og CRM virker uden AI.</p></Kort><Kort titel="Dinero" handling={<Pille>Ikke tilsluttet</Pille>}><p>Fakturajob, PDF/CSV og en isoleret testport er implementeret. Virkelig bogføring eller udsendelse kræver særskilt testorganisation og credentials.</p></Kort><Kort titel="Webformular"><p>Modtageendpointet kræver HMAC-signatur, fem minutters tidsvindue, unik leverings-id og honeypotkontrol. Ukendte afsendere bliver kun henvendelser.</p><Pille>Afventer ekstern formularopsætning</Pille></Kort></div>;
}

