import { useMemo, useState } from 'react';
import { useFacilityData } from '../../data/FacilityDataContext';
import { FUNCTION_STATUSES, getLocationPath, INSTALLATION_TYPES } from '../../domain/facilityDomain';
import { EntityDialog, Field, FormFeedback } from './EntityDialog';

const empty = { number: '', name: '', type: 'Ventilation', propertyId: '', physicalLocationId: '', servedAreaIds: [], manufacturer: '', model: '', serialNumber: '', acquisitionDate: '', commissioningDate: '', description: '', technicalNotes: '', supplierName: '', supplierContactName: '', supplierEmail: '', supplierPhone: '', functionStatus: 'notAssessed', functionNote: '', functionReason: '', reason: '' };

export function InstallationForm({ installation, initialPropertyId, initialLocationId, onClose, onSaved }) {
  const { dataset, runMutation } = useFacilityData();
  const initial = useMemo(() => installation ? { ...empty, ...installation, physicalLocationId: installation.physicalLocationId ?? '' } : { ...empty, propertyId: initialPropertyId ?? dataset.properties.find((item) => !item.archivedAt)?.id ?? '', physicalLocationId: initialLocationId ?? '' }, [dataset.properties, initialLocationId, initialPropertyId, installation]);
  const [form, setForm] = useState(initial); const [baseRevision] = useState(installation?.revision); const [dirty, setDirty] = useState(false); const [error, setError] = useState(null); const [busy, setBusy] = useState(false);
  const nodes = dataset.locationNodes.filter((item) => item.propertyId === form.propertyId && !item.archivedAt);
  const change = (field) => (event) => { const value = field === 'propertyId' ? event.target.value : event.target.value; setForm((current) => ({ ...current, [field]: value, ...(field === 'propertyId' ? { physicalLocationId: '', servedAreaIds: [] } : {}) })); setDirty(true); setError(null); };
  const toggleServed = (id) => { setForm((current) => ({ ...current, servedAreaIds: current.servedAreaIds.includes(id) ? current.servedAreaIds.filter((value) => value !== id) : [...current.servedAreaIds, id] })); setDirty(true); };
  async function submit(event) { event.preventDefault(); setBusy(true); setError(null); try { const result = installation ? await runMutation('updateInstallation', installation.id, baseRevision, form) : await runMutation('createInstallation', form); setDirty(false); onSaved?.(result.entity); onClose(); } catch (reason) { setError(reason); } finally { setBusy(false); } }
  const fieldError = (name) => error?.fieldErrors?.[name]; const functionChanged = installation && installation.functionStatus !== form.functionStatus;
  return <EntityDialog title={installation ? 'Rediger installation' : 'Ny installation'} description="Fysisk placering og betjente områder er to separate relationer." onClose={onClose} dirty={dirty} wide><form className="entity-form" onSubmit={submit}><FormFeedback error={error} /><div className="form-grid two-columns">
    <Field label="Installationsnummer" required error={fieldError('number')}><input value={form.number} onChange={change('number')} autoFocus /></Field><Field label="Navn" required error={fieldError('name')}><input value={form.name} onChange={change('name')} /></Field>
    <Field label="Installationstype" required error={fieldError('type')}><select value={form.type} onChange={change('type')}>{INSTALLATION_TYPES.map((item) => <option key={item}>{item}</option>)}</select></Field>
    <Field label="Ejendom" required error={fieldError('propertyId')}><select value={form.propertyId} onChange={change('propertyId')} disabled={Boolean(installation)}>{dataset.properties.filter((item) => !item.archivedAt || item.id === form.propertyId).map((item) => <option key={item.id} value={item.id}>{item.number} · {item.name}</option>)}</select></Field>
    <Field label="Fysisk placering" error={fieldError('physicalLocationId')}><select value={form.physicalLocationId} onChange={change('physicalLocationId')}><option value="">Hele ejendommen</option>{nodes.map((item) => <option key={item.id} value={item.id}>{getLocationPath(dataset, form.propertyId, item.id)}</option>)}</select></Field>
    <Field label="Funktion (manuel vurdering)" error={fieldError('functionStatus')}><select value={form.functionStatus} onChange={change('functionStatus')}>{Object.entries(FUNCTION_STATUSES).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field>
    <Field label="Betjener" error={fieldError('servedAreaIds')} hint="Tomt betyder Ikke angivet; vælg hele ejendommen eksplicit." className="span-two"><div className="checkbox-grid"><label><input type="checkbox" checked={form.servedAreaIds.includes(`property:${form.propertyId}`)} onChange={() => toggleServed(`property:${form.propertyId}`)} /> Hele ejendommen</label>{nodes.map((item) => <label key={item.id}><input type="checkbox" checked={form.servedAreaIds.includes(item.id)} onChange={() => toggleServed(item.id)} /> {getLocationPath(dataset, form.propertyId, item.id)}</label>)}</div></Field>
    <Field label="Fabrikat"><input value={form.manufacturer} onChange={change('manufacturer')} /></Field><Field label="Model"><input value={form.model} onChange={change('model')} /></Field><Field label="Serienummer"><input value={form.serialNumber} onChange={change('serialNumber')} /></Field>
    <Field label="Anskaffelsesdato"><input type="date" value={form.acquisitionDate} onChange={change('acquisitionDate')} /></Field><Field label="Idriftsættelsesdato"><input type="date" value={form.commissioningDate} onChange={change('commissioningDate')} /></Field>
    <Field label="Funktionsbemærkning"><input value={form.functionNote} onChange={change('functionNote')} placeholder="Manuel vurdering" /></Field>
    {functionChanged && <Field label="Begrundelse for funktionsændring" required error={fieldError('reason')}><input value={form.functionReason} onChange={change('functionReason')} /></Field>}
    <Field label="Beskrivelse" className="span-two"><textarea rows="3" value={form.description} onChange={change('description')} /></Field><Field label="Tekniske bemærkninger" className="span-two"><textarea rows="3" value={form.technicalNotes} onChange={change('technicalNotes')} /></Field>
    <Field label="Serviceleverandør"><input value={form.supplierName} onChange={change('supplierName')} /></Field><Field label="Kontaktperson"><input value={form.supplierContactName} onChange={change('supplierContactName')} /></Field><Field label="Leverandørens e-mail"><input type="email" value={form.supplierEmail} onChange={change('supplierEmail')} /></Field><Field label="Leverandørens telefon"><input value={form.supplierPhone} onChange={change('supplierPhone')} /></Field>
  </div><footer className="dialog-actions"><button type="button" className="secondary-button" onClick={onClose}>Annuller</button><button type="submit" className="primary-button" disabled={busy}>{busy ? 'Gemmer …' : 'Gem installation'}</button></footer></form></EntityDialog>;
}
