import { expect, test } from "@playwright/test";

const collectBrowserErrors = (page) => { const errors = []; page.on("console", (message) => { if (message.type() === "error") errors.push(`console: ${message.text()}`); }); page.on("pageerror", (error) => errors.push(`pageerror: ${error.message}`)); return errors; };

test("sammenhængende forløb fra indberetning til afsluttet værkstedsarbejde", async ({ page }) => {
  const errors = collectBrowserErrors(page);
  await page.setViewportSize({ width: 1672, height: 941 });
  await page.goto("/vaerksted");
  await expect(page.getByRole("heading", { name: "Værksted" })).toBeVisible();
  await page.screenshot({ path: "artifacts/fleet-v2-workshop-overview-1672x941.png", fullPage: false });

  await page.goto("/indberetninger/ny");
  await page.getByRole("button", { name: /NB-001/ }).click();
  await page.getByRole("button", { name: /Fortsæt/ }).click();
  await page.getByRole("button", { name: /Teknisk fejl/ }).click();
  await page.getByLabel("Kategori").fill("Motor / drift");
  await page.getByLabel("Titel").fill("E2E værkstedsforløb");
  await page.getByLabel("Beskrivelse").fill("Motorlampen lyser, og enheden skal diagnosticeres på værksted.");
  await page.getByRole("button", { name: /Fortsæt/ }).click();
  await page.getByLabel(/^Kilometertal/).fill("124540");
  await page.getByLabel("Usikker").check();
  await page.getByRole("button", { name: /Fortsæt/ }).click();
  await page.getByRole("button", { name: "Indsend indberetning" }).click();
  await page.getByRole("button", { name: /Følg status/ }).click();
  await page.getByLabel("Ansvarlig").selectOption("demo-lars");
  await page.getByLabel("Flyt status").selectOption("assessing");
  await page.getByRole("button", { name: "Gem vurdering" }).click();
  await expect(page.getByRole("button", { name: "Gem vurdering" })).toBeEnabled();
  await page.getByLabel("Flyt status").selectOption("ready");
  await page.getByRole("button", { name: "Gem vurdering" }).click();
  await expect(page.getByRole("button", { name: "Gem vurdering" })).toBeEnabled();

  await page.getByRole("button", { name: /Arbejdskø/ }).click();
  const card = page.locator(".queue-card").filter({ hasText: "E2E værkstedsforløb" });
  await card.locator(".queue-card-main").click();
  await page.getByRole("button", { name: "Opret værkstedsopgave" }).click();
  await page.getByLabel("Opgavetitel").fill("Diagnosticér motorfejl");
  await page.getByLabel("Arbejdsbeskrivelse").fill("Læs fejlkoder, kontrollér motorstyring og dokumentér resultatet.");
  await page.getByRole("button", { name: "Opret opgave" }).click();
  await expect(page.getByRole("heading", { name: "Diagnosticér motorfejl" })).toBeVisible();
  await page.screenshot({ path: "artifacts/fleet-v2-workshop-task-1672x941.png", fullPage: false });

  await page.getByRole("button", { name: "Book tid" }).click();
  await page.getByLabel("Bookingressource").selectOption("resource-bay-1");
  await page.getByLabel("Booking start").fill("2026-09-08T10:30");
  await page.getByLabel("Booking slut").fill("2026-09-08T11:30");
  await page.getByRole("button", { name: "Gem booking" }).click();
  await expect(page.getByRole("alert")).toContainText("allerede booket");
  await page.getByLabel("Bookingressource").selectOption("resource-bay-2");
  await page.getByLabel("Booking slut").fill("2026-09-09T12:00");
  await page.getByText("Manuelt bekræftet aftale").click();
  await page.getByRole("button", { name: "Gem booking" }).click();
  await expect(page.getByRole("heading", { name: "Værkstedskalender" })).toBeVisible();
  await expect(page.getByRole("dialog", { name: "Book værkstedsopgave" })).toHaveCount(0);
  await page.screenshot({ path: "artifacts/fleet-v2-workshop-calendar-1672x941.png", fullPage: false });
  await page.locator(".calendar-booking").filter({ hasText: "Diagnosticér motorfejl" }).first().click();
  await page.getByRole("button", { name: "Åbn opgave" }).click();

  await page.getByLabel("Udført aktivitet").fill("Diagnose og funktionstest");
  await page.getByLabel("Tidsforbrug").fill("2");
  await page.getByLabel("Arbejdsløn").fill("1800");
  await page.getByLabel("Materiale", { exact: true }).fill("Motorstyringssensor");
  await page.getByLabel("Materialepris").fill("950");
  await page.getByLabel("Værkstedsstatus").selectOption("in_progress");
  await page.getByRole("button", { name: "Gem opgave" }).click();
  await expect(page.getByText("I gang", { exact: true })).toBeVisible();
  await page.getByLabel("Værkstedsstatus").selectOption("completed");
  await page.getByLabel("Beskrivelse af udført arbejde").fill("Fejlen blev diagnosticeret, sensoren udskiftet og enheden testet.");
  await page.getByLabel("Problem løst").selectOption("yes");
  await page.getByLabel("Anvendelighed efter arbejde").selectOption("usable");
  await page.getByLabel("Arbejdstype").selectOption("repair");
  await page.getByLabel("Øvrig omkostning").fill("125");
  await page.getByRole("button", { name: "Gem opgave" }).click();
  await expect(page.getByText("Afsluttet", { exact: true })).toBeVisible();
  await expect(page.getByText(/2\.875/).first()).toBeVisible();
  await page.getByRole("button", { name: "Åbn sagsmappe" }).click();
  await expect(page.getByText("Klar til lukning", { exact: true }).first()).toBeVisible();
  await expect(page.getByText("Åben", { exact: true }).first()).toBeVisible();
  await page.goto("/enheder/unit-nb-001");
  await page.getByRole("tab", { name: "Historik" }).click();
  await expect(page.getByText("Værkstedsarbejde afsluttet", { exact: true })).toBeVisible();
  await page.getByRole("tab", { name: "Økonomi" }).click();
  await expect(page.getByText("Værksted · Arbejde", { exact: true })).toBeVisible();
  await page.reload();
  await page.getByRole("tab", { name: "Økonomi" }).click();
  await expect(page.getByText("Værksted · Materialer", { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});

test("booking kan annulleres med grund, og mobil viser dagsliste uden vandret overløb", async ({ page }) => {
  const errors = collectBrowserErrors(page);
  await page.setViewportSize({ width: 1672, height: 941 });
  await page.goto("/vaerksted/kalender");
  await page.locator(".calendar-booking").filter({ hasText: "VO-00001" }).first().click();
  await page.getByLabel("Bookingannullering").fill("Ressourcen skal bruges akut andetsteds.");
  await page.getByRole("button", { name: "Annuller booking" }).click();
  await expect(page.locator(".calendar-booking").filter({ hasText: "VO-00001" })).toHaveCount(0);
  await page.goto("/vaerksted/workshop-task-demo-001");
  await expect(page.getByText("Oprettet", { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 1366, height: 768 });
  let widths = await page.evaluate(() => ({ inner: window.innerWidth, scroll: document.documentElement.scrollWidth }));
  expect(widths.scroll).toBe(widths.inner);
  await page.goto("/vaerksted");
  widths = await page.evaluate(() => ({ inner: window.innerWidth, scroll: document.documentElement.scrollWidth }));
  expect(widths.scroll).toBe(widths.inner);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/vaerksted/kalender");
  await expect(page.locator(".calendar-mobile-list")).toBeVisible();
  widths = await page.evaluate(() => ({ inner: window.innerWidth, scroll: document.documentElement.scrollWidth }));
  expect(widths.scroll).toBe(widths.inner);
  await page.goto("/vaerksted/workshop-task-demo-001");
  const taskWidths = await page.evaluate(() => ({ inner: window.innerWidth, scroll: document.documentElement.scrollWidth }));
  expect(taskWidths.scroll).toBe(taskWidths.inner);
  expect(errors).toEqual([]);
});
