import { useMemo, useState } from "react";
import { conflictsForLeave, endExclusiveForDay, LEAVE_TYPES, localDateTimeMs, toLocalDateKey } from "../domain/workforceDomain.js";
import { formatLeavePeriod } from "../domain/workforcePresentation.js";
import { Card, employeeName, Field, formatDate, formatTime, LeaveStatus, Modal, Notice, PageHeader, Pill } from "./Shared.jsx";

const hasOwn = (value, key) => Object.prototype.hasOwnProperty.call(value, key);
const requestedLeaveLabel = (leave) => LEAVE_TYPES[leave.requestedType] || "Frihedsanmodning";
const employeeNoteLabel = (leave) => hasOwn(leave, "employeeNote") ? (leave.employeeNote || "Ingen kommentar") : "Skjult";

export function LeavePage({ state, repository, actor, run, busy, calendarCategories = [] }) {
  const [registering, setRegistering] = useState(false); const [selected, setSelected] = useState(null); const pending = state.leaves.filter((item) => item.status === "pending");
  const leaves = useMemo(() => [...state.leaves].sort((a, b) => b.fromMs - a.fromMs), [state]);
  const canReadSensitiveLeave = actor.permissions.includes("workforce.leave.sensitive");
  const categoryLabels = useMemo(() => new Map(calendarCategories.map((item) => [item.id, item.navn || item.label || item.id])), [calendarCategories]);
  return <>
    <PageHeader title="Ferie & fravær" subtitle="Anmodninger, gældende fravær og berørte tildelinger" actions={<button className="wf-btn wf-btn--primary" onClick={() => setRegistering(true)}>Registrér fravær</button>} />
    {pending.length > 0 && <Card title={`Afventer behandling · ${pending.length}`}><div className="wf-request-grid">{pending.map((leave) => { const conflicts = conflictsForLeave(state, leave); return <article key={leave.id} className="wf-request"><div><strong>{employeeName(state, leave.employeeId)}</strong><span>Ønsket frihed: {requestedLeaveLabel(leave)} · {formatLeavePeriod(leave)}</span></div><Pill tone={conflicts.shifts.length || conflicts.assignments.length ? "warn" : "neutral"}>{conflicts.shifts.length + conflicts.assignments.length} berørte tildelinger</Pill><p>{employeeNoteLabel(leave)}</p><button className="wf-btn wf-btn--primary" onClick={() => setSelected(leave)}>Behandl</button></article>; })}</div></Card>}
    <Card title="Registreret fravær"><div className="wf-table-wrap"><table><thead><tr><th>Medarbejder</th><th>Periode</th><th>Omfang</th><th>Status</th><th>Registreret årsag</th><th>Konflikter</th><th /></tr></thead><tbody>{leaves.map((leave) => { const sensitive = state.sensitiveLeave[leave.id]; const conflicts = conflictsForLeave(state, leave); const reason = sensitive ? (categoryLabels.get(sensitive.type) || LEAVE_TYPES[sensitive.type] || sensitive.type) : canReadSensitiveLeave && leave.status === "pending" ? "Ikke fastlagt" : <Pill>Skjult</Pill>; return <tr key={leave.id}><td><strong>{employeeName(state, leave.employeeId)}</strong></td><td><strong>{formatLeavePeriod(leave)}</strong></td><td>{leave.partialDay ? "Delvis dag" : "Hele dage"}</td><td><LeaveStatus value={leave.status} /></td><td>{reason}</td><td>{conflicts.shifts.length + conflicts.assignments.length ? <Pill tone="warn">{conflicts.shifts.length + conflicts.assignments.length} berørt</Pill> : "Ingen"}</td><td><button className="wf-btn" onClick={() => setSelected(leave)}>Åbn</button></td></tr>; })}</tbody></table></div></Card>
    {registering && <LeaveForm state={state} categories={calendarCategories} busy={busy} onClose={() => setRegistering(false)} onSave={async (input) => { await run(() => repository.registerLeave(actor, input)); setRegistering(false); }} />}
    {selected && <LeaveDetail leave={selected} state={state} categories={calendarCategories} busy={busy} onClose={() => setSelected(null)} onDecide={async (decision, response) => { await run(() => repository.decideLeave(actor, selected.id, decision, response)); setSelected(null); }} onCancel={async (reason) => { await run(() => repository.cancelLeave(actor, selected.id, reason)); setSelected(null); }} onUpdate={async (input) => { await run(() => repository.registerLeave(actor, input)); setSelected(null); }} />}
  </>;
}

function LeaveForm({ state, categories = [], busy, onClose, onSave, leave }) {
  const [form, setForm] = useState({ employeeId: leave?.employeeId || state.employees.find((item) => item.status === "active")?.id, type: state.sensitiveLeave[leave?.id]?.type || "vacation", fromDate: leave ? toLocalDateKey(leave.fromMs) : toLocalDateKey(Date.now()), toDate: leave ? toLocalDateKey(leave.toMs - 1) : toLocalDateKey(Date.now()), partialDay: leave?.partialDay || false, fromTime: leave ? formatTime(leave.fromMs).replace(".", ":") : "08:00", toTime: leave ? formatTime(leave.toMs).replace(".", ":") : "16:00", sensitiveNote: state.sensitiveLeave[leave?.id]?.note || "", reason: "" });
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const save = () => onSave({ ...(leave || {}), employeeId: form.employeeId, type: form.type, partialDay: form.partialDay,
    fromMs: localDateTimeMs(form.fromDate, form.partialDay ? form.fromTime : "00:00"),
    toMs: form.partialDay ? localDateTimeMs(form.toDate, form.toTime) : endExclusiveForDay(form.toDate), sensitiveNote: form.sensitiveNote, reason: form.reason });
  const categoryOptions = categories.filter((item) => item.aktiv !== false).length ? categories.filter((item) => item.aktiv !== false).map((item) => [item.id, item.navn || item.label || item.id]) : Object.entries(LEAVE_TYPES);
  return <Modal title={leave ? "Redigér fravær" : "Registrér fravær"} onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); save(); }}><div className="wf-form-grid"><Field label="Medarbejder"><select value={form.employeeId} onChange={(event) => update("employeeId", event.target.value)}>{state.employees.filter((item) => item.status !== "terminated").map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field><Field label="Årsag"><select value={form.type} onChange={(event) => update("type", event.target.value)}>{categoryOptions.map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></Field><Field label="Fra dato"><input type="date" value={form.fromDate} onChange={(event) => update("fromDate", event.target.value)} /></Field><Field label="Til og med"><input type="date" value={form.toDate} onChange={(event) => update("toDate", event.target.value)} /></Field></div>
    <label className="wf-check"><input type="checkbox" checked={form.partialDay} onChange={(event) => update("partialDay", event.target.checked)} /> Delvis dag</label>{form.partialDay && <div className="wf-form-grid"><Field label="Fra kl."><input type="time" value={form.fromTime} onChange={(event) => update("fromTime", event.target.value)} /></Field><Field label="Til kl."><input type="time" value={form.toTime} onChange={(event) => update("toTime", event.target.value)} /></Field></div>}
    <Field label="Intern note"><textarea value={form.sensitiveNote} onChange={(event) => update("sensitiveNote", event.target.value)} /></Field>{leave && <Field label="Begrundelse for ændring"><input required value={form.reason} onChange={(event) => update("reason", event.target.value)} /></Field>}
    <footer className="wf-modal-actions"><button type="button" className="wf-btn" onClick={onClose}>Annuller</button><button disabled={busy} className="wf-btn wf-btn--primary">{leave ? "Gem ændring" : "Registrér fravær"}</button></footer></form></Modal>;
}

function LeaveDetail({ leave, state, categories, busy, onClose, onDecide, onCancel, onUpdate }) {
  const [response, setResponse] = useState(leave.response || ""); const [cancelReason, setCancelReason] = useState(""); const [editing, setEditing] = useState(false); const conflicts = conflictsForLeave(state, leave);
  if (editing) return <LeaveForm state={state} categories={categories} leave={leave} busy={busy} onClose={() => setEditing(false)} onSave={onUpdate} />;
  return <Modal title={`${employeeName(state, leave.employeeId)} · ${requestedLeaveLabel(leave)}`} onClose={onClose}><div className="wf-detail-list"><div><span>Status</span><LeaveStatus value={leave.status} /></div><div><span>Periode</span><strong>{formatLeavePeriod(leave)}</strong></div><div><span>Ønsket frihed</span><strong>{requestedLeaveLabel(leave)}</strong></div><div><span>Medarbejderens kommentar</span><strong>{employeeNoteLabel(leave)}</strong></div>{leave.response && <div><span>Svar til medarbejderen</span><strong>{leave.response}</strong></div>}</div>
    {(conflicts.shifts.length > 0 || conflicts.assignments.length > 0) && <Notice tone="warn"><strong>Berørte tildelinger slettes eller flyttes ikke automatisk.</strong><ul>{conflicts.shifts.map((item) => <li key={item.id}>Vagt {formatDate(item.startMs)} kl. {formatTime(item.startMs)}</li>)}{conflicts.assignments.map((item) => <li key={item.id}>Opgave: {item.title}</li>)}</ul></Notice>}
    {leave.status === "pending" && <><Field label="Svar til medarbejderen"><textarea value={response} onChange={(event) => setResponse(event.target.value)} /></Field><div className="wf-modal-actions"><button disabled={busy} className="wf-btn wf-btn--danger" onClick={() => onDecide("rejected", response)}>Afvis</button><button disabled={busy} className="wf-btn wf-btn--primary" onClick={() => onDecide("approved", response)}>Godkend</button></div></>}
    {leave.status === "approved" && <><div className="wf-actions"><button className="wf-btn" onClick={() => setEditing(true)}>Redigér periode</button></div><Field label="Begrundelse ved annullering"><input value={cancelReason} onChange={(event) => setCancelReason(event.target.value)} /></Field><div className="wf-modal-actions"><button disabled={busy || !cancelReason.trim()} className="wf-btn wf-btn--danger" onClick={() => onCancel(cancelReason)}>Annullér fravær</button></div></>}
  </Modal>;
}
