import { useState } from "react";
import { addLocalDays, endExclusiveForDay, LEAVE_TYPES, localDateTimeMs, REQUESTABLE_LEAVE_TYPES, shiftMinutes, startOfWeek, toLocalDateKey } from "../domain/workforceDomain.js";
import { formatLeavePeriod } from "../domain/workforcePresentation.js";
import { Card, Field, formatDate, formatHours, formatTime, LeaveStatus, Modal, Notice, PageHeader, Pill } from "./Shared.jsx";

export function SelfServicePage({ state, repository, actor, run, busy }) {
  const employee = state.employees.find((item) => item.id === actor.employeeId); const [requesting, setRequesting] = useState(false); const [clockingOut, setClockingOut] = useState(false);
  const week = startOfWeek(); const end = addLocalDays(week, 7); const shifts = state.shifts.filter((item) => item.employeeId === actor.employeeId && item.status === "published" && item.startMs >= week && item.startMs < end).sort((a, b) => a.startMs - b.startMs);
  const leaves = state.leaves.filter((item) => item.employeeId === actor.employeeId).sort((a, b) => b.requestedAtMs - a.requestedAtMs); const entries = state.timeEntries.filter((item) => item.employeeId === actor.employeeId).sort((a, b) => b.inMs - a.inMs); const open = entries.find((item) => !Number.isFinite(item.outMs));
  if (!employee) return <Notice tone="warn">Din bruger er ikke knyttet til et medarbejderkort. Kontakt en administrator.</Notice>;
  return <div className="wf-self"><PageHeader title={`Hej ${employee.name.split(" ")[0]}`} subtitle="Din plan, tid og frihed samlet ét sted" />
    <Card className="wf-clock-card"><div><span>Arbejdstid</span><strong>{open ? `Indstemplet kl. ${formatTime(open.inMs)}` : "Ikke indstemplet"}</strong><small>{open ? "Husk at stemple ud, når arbejdsdagen slutter" : "Planlagte timer bliver ikke registreret automatisk"}</small></div>{open ? <button className="wf-btn wf-btn--primary wf-btn--large" onClick={() => setClockingOut(true)}>Stempel ud</button> : <button disabled={busy} className="wf-btn wf-btn--primary wf-btn--large" onClick={() => run(() => repository.clockIn(actor, actor.employeeId))}>Stempel ind</button>}</Card>
    <div className="wf-self-grid"><Card title="Min offentliggjorte plan"><div className="wf-mobile-list">{shifts.map((shift) => <article key={shift.id}><div className="wf-date-badge"><strong>{formatDate(shift.startMs).split(" ")[0]}</strong><span>{new Intl.DateTimeFormat("da-DK", { weekday: "short" }).format(shift.startMs)}</span></div><div><strong>{formatTime(shift.startMs)}–{formatTime(shift.endMs)}</strong><span>{shift.workplace}</span><small>Planlagt pause {shift.breakMinutes} min · Nettoarbejdstid {formatHours(shiftMinutes(shift))}</small></div></article>)}{!shifts.length && <p className="wf-muted">Ingen offentliggjorte vagter i denne uge.</p>}</div></Card>
      <Card title="Frihed"><button className="wf-btn wf-btn--primary wf-full" onClick={() => setRequesting(true)}>Anmod om frihed</button><div className="wf-mobile-list wf-mobile-list--compact">{leaves.slice(0, 4).map((leave) => <article key={leave.id}><div><strong>{LEAVE_TYPES[leave.requestedType || leave.type]}</strong><span>{formatLeavePeriod(leave)}</span>{leave.response && <small>Svar: {leave.response}</small>}</div><LeaveStatus value={leave.status} /></article>)}</div></Card>
    </div><Card title="Mine seneste registreringer"><div className="wf-mobile-list wf-mobile-list--compact">{entries.slice(0, 5).map((entry) => <article key={entry.id}><div><strong>{formatDate(entry.inMs, { year: true })}</strong><span>{formatTime(entry.inMs)}–{Number.isFinite(entry.outMs) ? formatTime(entry.outMs) : "åben"}</span></div>{Number.isFinite(entry.outMs) ? <Pill tone="ok">{formatHours(Math.round((entry.outMs - entry.inMs) / 60_000) - entry.breakMinutes)}</Pill> : <Pill tone="warn">Åben</Pill>}</article>)}</div></Card>
    {requesting && <RequestLeave busy={busy} employeeId={actor.employeeId} onClose={() => setRequesting(false)} onSave={async (value) => { await run(() => repository.requestLeave(actor, value)); setRequesting(false); }} />}
    {clockingOut && <ClockOut busy={busy} onClose={() => setClockingOut(false)} onSave={async (breakMinutes) => { await run(() => repository.clockOut(actor, actor.employeeId, { breakMinutes })); setClockingOut(false); }} />}
  </div>;
}

function RequestLeave({ employeeId, busy, onClose, onSave }) {
  const today = toLocalDateKey(Date.now()); const [form, setForm] = useState({ requestedType: "vacation", fromDate: today, toDate: today, partialDay: false, fromTime: "08:00", toTime: "16:00", employeeNote: "" }); const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const save = () => onSave({ employeeId, requestedType: form.requestedType, partialDay: form.partialDay, employeeNote: form.employeeNote,
    fromMs: localDateTimeMs(form.fromDate, form.partialDay ? form.fromTime : "00:00"), toMs: form.partialDay ? localDateTimeMs(form.toDate, form.toTime) : endExclusiveForDay(form.toDate) });
  return <Modal title="Anmod om frihed" onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); save(); }}><Field label="Type"><select value={form.requestedType} onChange={(event) => update("requestedType", event.target.value)}>{REQUESTABLE_LEAVE_TYPES.map((type) => <option key={type} value={type}>{LEAVE_TYPES[type]}</option>)}</select></Field><div className="wf-form-grid"><Field label="Fra"><input type="date" value={form.fromDate} onChange={(event) => update("fromDate", event.target.value)} /></Field><Field label="Til og med"><input type="date" value={form.toDate} onChange={(event) => update("toDate", event.target.value)} /></Field></div><label className="wf-check"><input type="checkbox" checked={form.partialDay} onChange={(event) => update("partialDay", event.target.checked)} /> Kun en del af dagen</label>{form.partialDay && <div className="wf-form-grid"><Field label="Fra kl."><input type="time" value={form.fromTime} onChange={(event) => update("fromTime", event.target.value)} /></Field><Field label="Til kl."><input type="time" value={form.toTime} onChange={(event) => update("toTime", event.target.value)} /></Field></div>}<Field label="Kommentar"><textarea value={form.employeeNote} onChange={(event) => update("employeeNote", event.target.value)} /></Field><Notice>Din anmodning påvirker først tilgængeligheden, når den er godkendt.</Notice><footer className="wf-modal-actions"><button type="button" className="wf-btn" onClick={onClose}>Annuller</button><button disabled={busy} className="wf-btn wf-btn--primary">Send anmodning</button></footer></form></Modal>;
}

function ClockOut({ busy, onClose, onSave }) {
  const [breakMinutes, setBreakMinutes] = useState(30);
  return <Modal title="Stempel ud" onClose={onClose}><Field label="Samlet pause i minutter"><input type="number" min="0" max="240" value={breakMinutes} onChange={(event) => setBreakMinutes(event.target.value)} /></Field><Notice>Kontrollér pausen før du afslutter. Din faktiske tid gemmes separat fra vagtplanen.</Notice><div className="wf-modal-actions"><button className="wf-btn" onClick={onClose}>Annuller</button><button disabled={busy} className="wf-btn wf-btn--primary" onClick={() => onSave(Number(breakMinutes))}>Bekræft udstempling</button></div></Modal>;
}
