import { useMemo, useState } from "react";
import { addLocalDays, startOfWeek, timeRegistrationSummary, toLocalDateKey, localDateTimeMs } from "../domain/workforceDomain.js";
import { Card, employeeName, Field, formatDate, formatHours, formatTime, Modal, PageHeader, Pill } from "./Shared.jsx";

export function TimePage({ state, repository, actor, run, busy }) {
  const [week, setWeek] = useState(startOfWeek()); const [employeeFilter, setEmployeeFilter] = useState("all"); const [correcting, setCorrecting] = useState(null); const end = addLocalDays(week, 7);
  const rows = useMemo(() => state.employees.filter((item) => item.status !== "terminated" && (employeeFilter === "all" || item.id === employeeFilter)).map((employee) => ({ employee,
    summary: timeRegistrationSummary(state.shifts, state.timeEntries, employee.id, week, end) })), [state, employeeFilter, week, end]);
  const entries = state.timeEntries.filter((item) => item.inMs >= week && item.inMs < end && (employeeFilter === "all" || item.employeeId === employeeFilter)).sort((a, b) => b.inMs - a.inMs);
  return <><PageHeader title="Timer" subtitle="Registreret arbejdstid sammenholdt med den offentliggjorte plan" />
    <Card><div className="wf-schedule-toolbar"><div className="wf-week-nav"><button className="wf-btn" onClick={() => setWeek(addLocalDays(week, -7))}>←</button><button className="wf-btn" onClick={() => setWeek(startOfWeek())}>Denne uge</button><button className="wf-btn" onClick={() => setWeek(addLocalDays(week, 7))}>→</button><strong>{formatDate(week, { year: true })} – {formatDate(addLocalDays(week, 6), { year: true })}</strong></div><select value={employeeFilter} onChange={(event) => setEmployeeFilter(event.target.value)}><option value="all">Alle medarbejdere</option>{state.employees.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>
      <div className="wf-hours-overview">{rows.map(({ employee, summary }) => { const difference = summary.actualMinutes - summary.plannedMinutes; const stateLabel = summary.registrationState === "open" ? "Åben stempling" : summary.registrationState === "none" ? "Ingen registrering" : "Afsluttet registrering"; return <article key={employee.id}><div><strong>{employee.name}</strong><small>{employee.functions.join(" · ")}</small></div><div><span>Offentliggjort plan</span><strong>{formatHours(summary.plannedMinutes)}</strong></div><div><span>Kladde</span><strong>{formatHours(summary.draftMinutes)}</strong></div><div><span>Registreret</span><strong>{formatHours(summary.actualMinutes)}</strong></div><div><span>Forskel</span><strong className={difference < 0 ? "wf-negative" : ""}>{formatHours(difference)}</strong>{summary.missingShiftCount > 0 && <small className="wf-missing">{summary.missingShiftCount} {summary.missingShiftCount === 1 ? "vagt" : "vagter"} uden registrering</small>}</div><Pill tone={summary.registrationState === "completed" && summary.missingShiftCount === 0 ? "ok" : "warn"}>{stateLabel}</Pill></article>; })}</div>
    </Card><Card title="Tidsregistreringer"><div className="wf-table-wrap"><table><thead><tr><th>Medarbejder</th><th>Dato</th><th>Ind</th><th>Ud</th><th>Pause</th><th>Registreret</th><th /></tr></thead><tbody>{entries.map((entry) => <tr key={entry.id}><td><strong>{employeeName(state, entry.employeeId)}</strong></td><td>{formatDate(entry.inMs, { year: true })}</td><td>{formatTime(entry.inMs)}</td><td>{Number.isFinite(entry.outMs) ? formatTime(entry.outMs) : <Pill tone="warn">Åben</Pill>}</td><td>{entry.breakMinutes} min</td><td>{Number.isFinite(entry.outMs) ? formatHours(Math.round((entry.outMs - entry.inMs) / 60_000) - entry.breakMinutes) : "—"}</td><td>{Number.isFinite(entry.outMs) && <button className="wf-btn" onClick={() => setCorrecting(entry)}>Ret</button>}</td></tr>)}</tbody></table></div></Card>
    {correcting && <Correction entry={correcting} busy={busy} onClose={() => setCorrecting(null)} onSave={async (input, reason) => { await run(() => repository.correctTime(actor, input, reason)); setCorrecting(null); }} />}
  </>;
}

function Correction({ entry, busy, onClose, onSave }) {
  const [date, setDate] = useState(toLocalDateKey(entry.inMs)); const [inTime, setInTime] = useState(formatTime(entry.inMs).replace(".", ":")); const [outTime, setOutTime] = useState(formatTime(entry.outMs).replace(".", ":")); const [breakMinutes, setBreakMinutes] = useState(entry.breakMinutes); const [reason, setReason] = useState("");
  return <Modal title="Ret tidsregistrering" onClose={onClose}><div className="wf-form-grid"><Field label="Dato"><input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></Field><Field label="Ind"><input type="time" value={inTime} onChange={(event) => setInTime(event.target.value)} /></Field><Field label="Ud"><input type="time" value={outTime} onChange={(event) => setOutTime(event.target.value)} /></Field><Field label="Pause"><input type="number" min="0" value={breakMinutes} onChange={(event) => setBreakMinutes(event.target.value)} /></Field></div><Field label="Begrundelse"><textarea required value={reason} onChange={(event) => setReason(event.target.value)} /></Field><div className="wf-modal-actions"><button className="wf-btn" onClick={onClose}>Annuller</button><button disabled={busy || !reason.trim()} className="wf-btn wf-btn--primary" onClick={() => onSave({ ...entry, inMs: localDateTimeMs(date, inTime), outMs: localDateTimeMs(date, outTime), breakMinutes: Number(breakMinutes) }, reason)}>Gem rettelse</button></div></Modal>;
}
