import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { registerAlreadyPurchased } from "./procure-v2-adapter.js";

const requestId = () => globalThis.crypto?.randomUUID?.() || `koeb-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const today = () => new Date().toISOString().slice(0, 10);
const money = (oere) => new Intl.NumberFormat("da-DK", { style: "currency", currency: "DKK" }).format(Number(oere || 0) / 100);
const parseOere = (value) => Math.round(Number(String(value || "").replace(".", "").replace(",", ".")) * 100);

const lineFromItem = (item, departments) => ({
  id: `line-${Date.now()}-${Math.random().toString(36).slice(2)}`, itemId: item?.id || "",
  quantity: 1, unit: item?.unit || "stk.", departmentId: item?.defaultDepartmentId || departments[0]?.id || "",
  amount: "", warehouseLocation: "",
});

export default function NewPurchaseScreen({ state, setState, demo, tenant, canWrite, busy, error }) {
  const navigate = useNavigate();
  const departments = useMemo(() => Object.values(state.setup?.afdelinger || {}).filter((row) => row.active !== false), [state.setup]);
  const placements = useMemo(() => Object.values(state.setup?.lagerplaceringer || {}).filter((row) => row.active !== false), [state.setup]);
  const preferredItem = state.catalog.find((item) => !item.stocked && item.active !== false) || state.catalog[0];
  const [mode, setMode] = useState("choice"); const [step, setStep] = useState("edit");
  const [supplierId, setSupplierId] = useState(state.suppliers[0]?.id || ""); const [purchaseDate, setPurchaseDate] = useState(today());
  const [paymentMethod, setPaymentMethod] = useState("firmakort"); const [files, setFiles] = useState([]);
  const [lines, setLines] = useState(() => preferredItem ? [lineFromItem(preferredItem, departments)] : []);
  const [submissionId] = useState(requestId); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const [receipt, setReceipt] = useState(null);
  useEffect(() => { if (!supplierId && state.suppliers[0]?.id) setSupplierId(state.suppliers[0].id); }, [state.suppliers, supplierId]);
  useEffect(() => { if (!lines.length && preferredItem) setLines([lineFromItem(preferredItem, departments)]); }, [departments, lines.length, preferredItem]);
  const updateLine = (id, key, value) => setLines((current) => current.map((line) => line.id === id ? { ...line, [key]: value } : line));
  const selectItem = (line, itemId) => { const item = state.catalog.find((row) => row.id === itemId); setLines((current) => current.map((row) => row.id === line.id ? { ...row, itemId, unit: item?.unit || "stk.", departmentId: item?.defaultDepartmentId || row.departmentId, warehouseLocation: "" } : row)); };
  const validation = (() => {
    if (!supplierId) return "Vælg leverandør."; if (!purchaseDate) return "Angiv købsdato."; if (!lines.length) return "Tilføj mindst én varelinje.";
    for (const line of lines) { const item = state.catalog.find((row) => row.id === line.itemId); if (!item) return "Vælg en katalogvare på alle linjer."; if (!(Number(line.quantity) > 0)) return `Angiv antal for ${item.name}.`; if (!line.departmentId) return `Vælg afdeling for ${item.name}.`; if (!Number.isInteger(parseOere(line.amount)) || parseOere(line.amount) < 0) return `Angiv beløb for ${item.name}.`; if (item.stocked && !line.warehouseLocation) return `Vælg lagerplacering for ${item.name}; varen modtages på lager én gang.`; }
    return "";
  })();
  const payloadLines = () => lines.map((line) => { const item = state.catalog.find((row) => row.id === line.itemId); const place = placements.find((row) => `${row.lagerId}|${row.id}` === line.warehouseLocation); const locationEntry = Object.values(item?.inventoryLocations || {}).find((row) => row.warehouseId === place?.lagerId && row.locationId === place?.id); return { itemId: line.itemId, quantity: Number(line.quantity), unit: line.unit, departmentId: line.departmentId, amountOere: parseOere(line.amount), warehouseId: place?.lagerId, warehouse: state.setup?.lagre?.[place?.lagerId]?.label || place?.lagerId, locationId: place?.id, location: place?.label, expectedRevision: Number(locationEntry?.revision || 0) }; });
  const save = async () => {
    if (!canWrite || saving || validation) { if (validation) setMessage(validation); return; }
    setSaving(true); setMessage("");
    if (demo) {
      const id = `koeb-${submissionId}`; const reference = `KOB-${purchaseDate.replaceAll("-", "")}-${submissionId.slice(-6).toUpperCase()}`;
      const purchase = { id, reference, recordType: "purchase", supplierId, purchaseDate: Date.parse(`${purchaseDate}T12:00:00Z`), paymentMethod,
        status: "afventerGodkendelse", economyStatus: "ikkeBogfoert", receiptStatus: files.length ? "vedhaeftet" : "mangler", documentId: files.length ? `demo-${submissionId}` : null,
        lines: payloadLines().map((line, index) => { const item = state.catalog.find((row) => row.id === line.itemId); const department = departments.find((row) => row.id === line.departmentId); return { ...line, id: `${id}-line-${index + 1}`, name: item.name, sku: item.sku, department: department?.label, stocked: item.stocked }; }) };
      setState((current) => ({ ...current, purchases: [purchase, ...(current.purchases || [])] }));
      setReceipt({ ...purchase, vendorMailSent: false, paymentCreated: false }); setStep("done"); setSaving(false); return;
    }
    const result = await registerAlreadyPurchased({ requestId: submissionId, supplierId, purchaseDate, paymentMethod, lines: payloadLines(), attachments: files });
    setSaving(false); if (!result.ok) { setMessage(result.message); if (result.data?.purchaseId) { setReceipt(result.data); setStep("done"); } return; }
    setReceipt(result.data); setStep("done");
  };
  if (busy) return <section className="procure-v2"><div className="procure-state">Indlæser vare- og afdelingsdata …</div></section>;
  if (error) return <section className="procure-v2"><div className="procure-state error">Data kunne ikke indlæses. Intet køb er registreret.</div></section>;
  if (mode === "choice") return <section className="procure-v2 procure-purchase-entry"><header className="procure-pagehead"><div><Link className="procure-back" to="/indkoeb/bestillinger">← Tilbage</Link><h1>Ny bestilling</h1><p>Vælg om varerne skal bestilles, eller om købet allerede er foretaget.</p></div>{demo && <span className="procure-demo">Syntetiske testdata · {tenant?.navn || "demo"}</span>}</header><div className="procure-purchase-choices"><Link to="/indkoeb/mobil"><span aria-hidden="true">🛒</span><b>Bestil hos leverandør</b><small>Opret behov og send til godkendelse. Leverandøren kontaktes først ved aktiv afsendelse.</small></Link><button type="button" onClick={() => setMode("already")}><span aria-hidden="true">▤</span><b>Registrér allerede foretaget køb</b><small>Gem køb og kvittering. Ingen bestilling sendes, og ingen betaling foretages.</small></button></div></section>;
  if (step === "done") return <section className="procure-v2 procure-purchase-entry"><header className="procure-pagehead"><div><h1>Køb registreret</h1><p>Serveren har gemt købet som en sag til økonomisk opfølgning.</p></div></header><article className="procure-card procure-purchase-done"><div className="procure-success-mark">✓</div><div><h2>Købet er gemt</h2><p>Reference <b>{receipt?.reference}</b></p><span className="procure-status warn">Afventer udgiftsgodkendelse · ikke bogført</span></div><dl><dt>Varelinjer</dt><dd>{lines.length}</dd><dt>Betalingsform</dt><dd>{paymentMethod === "firmakort" ? "Firmakort" : paymentMethod}</dd><dt>Beløb</dt><dd>{money(lines.reduce((sum, line) => sum + parseOere(line.amount), 0))}</dd><dt>Kvittering</dt><dd>{receipt?.receiptStatus === "vedhaeftet" || files.length ? "Vedhæftet" : "Kvittering mangler"}</dd></dl><div className="procure-alert info"><b>Ingen leverandørbestilling er sendt</b><span>Registreringen har ikke udløst mail, ny betaling eller ekstra lagerbevægelse ved genindlæsning.</span></div><div className="procure-actions"><Link className="procure-button" to={`/indkoeb/bestillinger?sag=${encodeURIComponent(receipt?.purchaseId || receipt?.id || "")}`}>Åbn købet</Link><Link className="procure-button secondary" to="/indkoeb/bestillinger">Tilbage til bestillinger</Link></div></article></section>;
  return <section className="procure-v2 procure-purchase-entry"><header className="procure-pagehead"><div><button className="procure-back" type="button" onClick={() => step === "review" ? setStep("edit") : setMode("choice")}>← Tilbage</button><h1>{step === "review" ? "Kontrollér køb" : "Allerede foretaget køb"}</h1><p>{step === "review" ? "Kontrollér oplysninger og bilag før registrering." : "Registrér købet uden at sende en leverandørbestilling."}</p></div>{demo && <span className="procure-demo">Syntetiske testdata</span>}</header>{message && <div className="procure-alert warn" role="alert"><span>{message}</span></div>}
    <article className="procure-card procure-purchase-form"><div className="procure-form-grid"><label className="procure-field"><span>Leverandør</span><select disabled={step === "review"} value={supplierId} onChange={(event) => setSupplierId(event.target.value)}><option value="">Vælg leverandør</option>{state.suppliers.map((row) => <option value={row.id} key={row.id}>{row.name}</option>)}</select></label><label className="procure-field"><span>Købsdato</span><input disabled={step === "review"} type="date" value={purchaseDate} onChange={(event) => setPurchaseDate(event.target.value)} /></label><label className="procure-field"><span>Betalt med</span><select disabled={step === "review"} value={paymentMethod} onChange={(event) => setPaymentMethod(event.target.value)}><option value="firmakort">Firmakort</option><option value="udlaeg">Privat udlæg</option><option value="kontant">Kontant</option><option value="faktura">Faktura modtages senere</option></select></label></div>
      <section className="procure-purchase-files"><h2>Kvittering</h2>{step === "edit" && <div><label className="procure-button"><span>▣ Tag billede</span><input type="file" accept="image/jpeg,image/png" capture="environment" onChange={(event) => setFiles([...files, ...event.target.files])} /></label><label className="procure-button secondary"><span>⌕ Vælg fil</span><input type="file" accept="application/pdf,image/jpeg,image/png" multiple onChange={(event) => setFiles([...files, ...event.target.files])} /></label></div>}{files.length ? <ul>{files.map((file, index) => <li key={`${file.name}-${index}`}><span>{file.name}<small>{Math.ceil(file.size / 1024)} KB</small></span>{step === "edit" && <button type="button" aria-label={`Fjern ${file.name}`} onClick={() => setFiles(files.filter((_, fileIndex) => fileIndex !== index))}>×</button>}</li>)}</ul> : <p className="procure-hint">Købet kan gemmes uden kvittering og får da status “Kvittering mangler”. Bilaget kan tilføjes senere på samme køb.</p>}</section>
      <div className="procure-purchase-lines"><h2>Varelinjer</h2>{lines.map((line) => { const item = state.catalog.find((row) => row.id === line.itemId); return <article key={line.id}><label className="procure-field"><span>Vare og varenummer</span><select disabled={step === "review"} value={line.itemId} onChange={(event) => selectItem(line, event.target.value)}><option value="">Vælg vare</option>{state.catalog.filter((row) => row.active !== false).map((row) => <option value={row.id} key={row.id}>{row.name} · {row.sku}</option>)}</select></label><label className="procure-field"><span>Antal</span><input disabled={step === "review"} type="number" inputMode="decimal" min="0.001" step="any" value={line.quantity} onChange={(event) => updateLine(line.id, "quantity", event.target.value)} /></label><label className="procure-field"><span>Enhed</span><input value={line.unit} readOnly /></label><label className="procure-field"><span>Afdeling</span><select disabled={step === "review"} value={line.departmentId} onChange={(event) => updateLine(line.id, "departmentId", event.target.value)}><option value="">Vælg afdeling</option>{departments.map((row) => <option value={row.id} key={row.id}>{row.label}</option>)}</select></label><label className="procure-field"><span>Beløb ekskl. moms</span><input disabled={step === "review"} inputMode="decimal" value={line.amount} onChange={(event) => updateLine(line.id, "amount", event.target.value)} placeholder="0,00" /></label>{item?.stocked && <label className="procure-field span-2"><span>Modtaget på lagerplacering</span><select disabled={step === "review"} value={line.warehouseLocation} onChange={(event) => updateLine(line.id, "warehouseLocation", event.target.value)}><option value="">Vælg lager og placering</option>{placements.map((row) => <option key={`${row.lagerId}|${row.id}`} value={`${row.lagerId}|${row.id}`}>{state.setup?.lagre?.[row.lagerId]?.label || row.lagerId} · {row.label}</option>)}</select><small>Lageret øges én gang, når købet gemmes.</small></label>}{step === "edit" && lines.length > 1 && <button type="button" className="procure-iconbutton" aria-label="Fjern varelinje" onClick={() => setLines(lines.filter((row) => row.id !== line.id))}>×</button>}</article>; })}{step === "edit" && <button type="button" className="procure-linkbutton" onClick={() => setLines([...lines, lineFromItem(preferredItem, departments)])}>＋ Tilføj varelinje</button>}</div>
      <div className="procure-purchase-total"><span>Samlet beløb ekskl. moms</span><strong>{money(lines.reduce((sum, line) => sum + (Number.isInteger(parseOere(line.amount)) ? parseOere(line.amount) : 0), 0))}</strong></div><div className="procure-alert info"><b>{step === "review" ? "Klar til registrering" : "Manuel registrering"}</b><span>En vedhæftning omtales ikke som automatisk aflæst. “Køb registreret” betyder ikke godkendt, bogført eller betalt.</span></div><div className="procure-actions">{step === "edit" ? <button className="procure-button" onClick={() => validation ? setMessage(validation) : (setMessage(""), setStep("review"))}>Fortsæt</button> : <button className="procure-button" disabled={saving || !canWrite} onClick={save}>{saving ? "Gemmer på serveren …" : "Gem køb"}</button>}<button className="procure-button secondary" onClick={() => navigate("/indkoeb/bestillinger")}>Annullér</button></div></article>
  </section>;
}
