export const DEMO_SUPPLIERS = [
  { id: "nordisk", name: "Nordisk Drift ApS", orderEmail: "ordre@nordiskdrift.example", address: "Industrivej 12, 8200 Aarhus N", agreement: "Prisaftale til 31.12.2026" },
  { id: "arbejde", name: "Dansk Arbejdsbeklædning ApS", orderEmail: "ordre@arbejdstoej.example", address: "Håndværkervej 4, 2600 Glostrup", agreement: "Prisaftale til 31.03.2027" },
  { id: "kontor", name: "Kontorpartner ApS", orderEmail: "salg@kontorpartner.example", address: "Papirvej 7, 6000 Kolding", agreement: null },
];

export const DEMO_CATALOG = [
  { id: "tape", sku: "ND-1001", name: "Pakketape, klar 48 mm", category: "Emballage", supplierId: "nordisk", unit: "rulle", packageSize: "6 ruller", unitPriceOere: 2400, favorite: true, boughtBefore: true, visual: "tape" },
  { id: "film", sku: "ND-2005", name: "Strækfilm, 500 mm", category: "Emballage", supplierId: "nordisk", unit: "rulle", packageSize: "4 ruller", unitPriceOere: 7500, favorite: false, boughtBefore: true, visual: "film" },
  { id: "gloves", sku: "ND-2004", name: "Nitrilhandsker, str. L", category: "Arbejdstøj", supplierId: "nordisk", unit: "æske", packageSize: "100 stk.", unitPriceOere: 5500, favorite: true, boughtBefore: true, visual: "gloves" },
  { id: "bags", sku: "ND-3007", name: "Affaldssække, 100 L", category: "Rengøring", supplierId: "nordisk", unit: "rulle", packageSize: "10 stk.", unitPriceOere: 3800, favorite: false, boughtBefore: true, visual: "bags" },
  { id: "vest", sku: "DA-1040", name: "Sikkerhedsvest med tryk", category: "Arbejdstøj", supplierId: "arbejde", unit: "stk.", packageSize: "1 stk.", unitPriceOere: 31000, favorite: false, boughtBefore: false, visual: "vest" },
  { id: "paper", sku: "KP-0080", name: "Kopipapir A4, 80 g", category: "Kontor", supplierId: "kontor", unit: "kasse", packageSize: "5 pakker", unitPriceOere: 22900, favorite: false, boughtBefore: true, visual: "paper" },
];

export const DEMO_NEEDS = [
  { id: "BEH-0108", title: "Emballage til lageret", departmentId: "lager", department: "Lager", deliveryLocation: "Hovedlager", wantedDate: "2026-09-15", status: "new", createdBy: "Maja Larsen", note: "Til de kommende leverancer fra hovedlageret.", links: ["FLEET", "FACILITY"], lines: [{ id: "n1", itemId: "tape", name: "Pakketape, klar 48 mm", quantity: 120, unit: "ruller" }, { id: "n2", itemId: "film", name: "Strækfilm, 500 mm", quantity: 80, unit: "ruller" }] },
  { id: "BEH-0109", title: "Nitrilhandsker", departmentId: "drift", department: "Drift", deliveryLocation: "Værksted", wantedDate: "2026-09-14", status: "new", createdBy: "Henrik Nielsen", note: "", links: [], lines: [{ id: "n3", itemId: "gloves", name: "Nitrilhandsker, str. L", quantity: 8, unit: "æsker" }] },
  { id: "BEH-0110", title: "Kopipapir A4", departmentId: "kontor", department: "Kontor", deliveryLocation: "Kontor", wantedDate: "2026-09-16", status: "new", createdBy: "Sofie Jensen", note: "", links: [], lines: [{ id: "n4", itemId: "paper", name: "Kopipapir A4, 80 g", quantity: 3, unit: "kasser" }] },
  { id: "BEH-0111", title: "Rengøringsmidler", departmentId: "facility", department: "Facility", deliveryLocation: "Ejendom A", wantedDate: "2026-09-18", status: "new", createdBy: "Maja Larsen", note: "Lang dansk bemærkning, der kontrollerer at tekst ombrydes uden vandret sideoverflow på smalle skærme.", links: ["FACILITY"], lines: [{ id: "n5", name: "Miljømærket gulvrens", quantity: 10, unit: "liter" }] },
];

export const DEMO_ORDERS = [
  { id: "po-2026-0142", poNumber: "PO-2026-0142", supplierId: "nordisk", needId: "BEH-0108", title: "Emballage til lageret", departmentId: "lager", department: "Lager", deliveryLocation: "Hovedlager", wantedDate: "2026-09-15", contact: "Maja Larsen", revision: 3, approvedRevision: 3, approvalStatus: "approved", status: "sent", sendStatus: "accepted", supplierConfirmationStatus: "pending", sentAt: "2026-09-11T09:22:00", sentBy: "Dennis Christensen", lines: [{ id: "l1", itemId: "tape", sku: "ND-1001", name: "Pakketape, klar 48 mm", categorySnapshot: "Emballage", quantity: 120, unit: "ruller", unitPriceOere: 2400, priceBasis: "Aftalepris" }, { id: "l2", itemId: "film", sku: "ND-2005", name: "Strækfilm, 500 mm", categorySnapshot: "Emballage", quantity: 80, unit: "ruller", unitPriceOere: 7500, priceBasis: "Aftalepris" }], history: [{ at: "2026-09-10 10:14", actor: "Maja Larsen", action: "Behov oprettet" }, { at: "2026-09-10 13:27", actor: "Afdelingsleder", action: "Indkøb godkendt" }, { at: "2026-09-11 09:22", actor: "Dennis Christensen", action: "Bestilling sendt til mailudbyder" }] },
  { id: "po-2026-0140", poNumber: "PO-2026-0140", supplierId: "nordisk", needId: "BEH-0105", title: "Ventilationsfiltre", departmentId: "facility", department: "Facility", deliveryLocation: "Ejendom A", wantedDate: "2026-09-12", contact: "Sofie Jensen", revision: 1, approvedRevision: 1, approvalStatus: "approved", status: "sent", sendStatus: "accepted", supplierConfirmationStatus: "confirmed", lines: [{ id: "l3", itemId: "filter", name: "Ventilationsfilter G4", categorySnapshot: "Reservedele", quantity: 20, unit: "stk.", unitPriceOere: 8900 }] },
  { id: "po-2026-0144", poNumber: "PO-2026-0144", supplierId: "kontor", needId: "BEH-0110", title: "Kontorartikler til administrationen", departmentId: "kontor", department: "Kontor", deliveryLocation: "Administrationen", wantedDate: "2026-09-18", contact: "Sofie Jensen", revision: 1, approvedRevision: 1, approvalStatus: "approved", status: "approved", sendStatus: "draft", supplierConfirmationStatus: "not-sent", lines: [{ id: "l5", itemId: "paper", sku: "KP-0080", name: "Kopipapir A4, 80 g", categorySnapshot: "Kontor", quantity: 8, unit: "kasser", unitPriceOere: 22900, priceBasis: "Aftalepris" }], history: [{ at: "2026-09-10 11:05", actor: "Sofie Jensen", action: "Behov oprettet" }, { at: "2026-09-10 15:42", actor: "Afdelingsleder", action: "Indkøb godkendt" }] },
  { id: "po-2026-0146", poNumber: "PO-2026-0146", supplierId: "arbejde", needId: "BEH-0107", title: "Arbejdstøj til drift", departmentId: "drift", department: "Drift", deliveryLocation: "Værksted", wantedDate: "2026-09-20", contact: "Henrik Nielsen", revision: 2, approvedRevision: null, approvalStatus: "pending", status: "pending-approval", sendStatus: "draft", supplierConfirmationStatus: "not-sent", lines: [{ id: "l4", itemId: "vest", name: "Sikkerhedsvest med tryk", categorySnapshot: "Arbejdstøj", quantity: 40, unit: "stk.", unitPriceOere: 31000 }] },
];

export const DEMO_RECEIPTS = [
  { id: "receipt-1", orderId: "po-2026-0142", receivedDate: "2026-09-15", receivedBy: "Maja Larsen", deliveryNote: "FS-4482", lines: [{ orderLineId: "l1", deliveredQuantity: 72, acceptedQuantity: 72, damagedQuantity: 0, rejectedQuantity: 0, unit: "ruller" }, { orderLineId: "l2", deliveredQuantity: 80, acceptedQuantity: 80, damagedQuantity: 0, rejectedQuantity: 0, unit: "ruller" }], note: "48 ruller pakketape leveres senere.", attachments: [{ name: "følgeseddel-FS-4482.pdf", testOnly: true }] },
];

export const DEMO_APPROVALS = [
  { id: "app-1", orderId: "po-2026-0146", needId: "BEH-0107", title: "Arbejdstøj til drift", requester: "Henrik Nielsen", department: "Drift", submittedAt: "2026-09-09", reason: "Nyt arbejdstøj før vintersæsonen.", rule: "Drift · køb over 5.000 kr. → Afdelingsleder", status: "pending", history: [{ at: "09.09.2026 kl. 14.10", actor: "Henrik Nielsen", action: "Indsendte behovet" }] },
  { id: "app-2", orderId: "po-2026-0142", needId: "BEH-0108", title: "Emballage til lageret", requester: "Maja Larsen", department: "Lager", submittedAt: "2026-09-10", reason: "Emballage til de kommende leverancer fra hovedlageret.", rule: "Lager · køb over 5.000 kr. → Afdelingsleder", status: "approved", history: [{ at: "10.09.2026 kl. 09.14", actor: "Maja Larsen", action: "Indsendte behovet" }, { at: "10.09.2026 kl. 13.27", actor: "Dennis Christensen", action: "Godkendte indkøbet" }] },
];

export const DEMO_INVOICES = [
  { id: "invoice-8841", invoiceNumber: "ND-8841", supplierId: "nordisk", poNumber: "PO-2026-0142", orderId: "po-2026-0142", departmentId: "lager", approvalStatus: "pending", approvedAt: Date.parse("2026-09-16"), type: "invoice", lines: [{ orderLineId: "l1", itemId: "tape", categorySnapshot: "Emballage", quantity: 72, unit: "ruller", unitPriceOere: 2600 }, { orderLineId: "l2", itemId: "film", categorySnapshot: "Emballage", quantity: 80, unit: "ruller", unitPriceOere: 7500 }] },
  { id: "invoice-aug-1", invoiceNumber: "ND-8700", supplierId: "nordisk", departmentId: "lager", approvalStatus: "approved", approvedAt: Date.parse("2026-09-02"), type: "invoice", lines: [{ itemId: "tape", categorySnapshot: "Emballage", quantity: 400, unit: "ruller", unitPriceOere: 2400 }, { itemId: "film", categorySnapshot: "Emballage", quantity: 80, unit: "ruller", unitPriceOere: 7500 }] },
  { id: "invoice-aug-2", invoiceNumber: "DA-2011", supplierId: "arbejde", departmentId: "drift", approvalStatus: "approved", approvedAt: Date.parse("2026-09-04"), type: "invoice", lines: [{ itemId: "vest", categorySnapshot: "Arbejdstøj", quantity: 40, unit: "stk.", unitPriceOere: 31000 }] },
  { id: "credit-1", invoiceNumber: "KN-0021", supplierId: "nordisk", departmentId: "lager", approvalStatus: "approved", approvedAt: Date.parse("2026-09-05"), type: "credit-note", lines: [{ itemId: "tape", categorySnapshot: "Emballage", quantity: 10, unit: "ruller", unitPriceOere: 2400 }] },
];

export const DEMO_RULES = [{ id: "lager-5000", active: true, departmentId: "lager", thresholdOere: 500000, approverRole: "Afdelingsleder" }, { id: "drift-5000", active: true, departmentId: "drift", thresholdOere: 500000, approverRole: "Afdelingsleder" }];
