import { useEffect, useMemo, useState } from 'react';
import { useFacilityData } from '../../data/FacilityDataContext';
import { getLocationPath } from '../../domain/facilityDomain';
import { EntityDialog, Field, FormFeedback, useUnsavedGuard } from '../facility/EntityDialog';
import { FacilityLink } from '../../routing/FacilityRouting';

function initialForm(dataset, source, context = {}) {
  const propertyId = context.propertyId || dataset.properties.find((item) => !item.archivedAt)?.id || '';
  return { submissionKey: `report-${crypto.randomUUID()}`, source, propertyId, locationId: context.locationId || '', installationId: context.installationId || '', title: '', description: '', category: 'Tekniske installationer', reporterSeverity: 'medium', observedAt: new Date().toISOString().slice(0, 16), affectedAreaIds: [], contactName: '', contactEmail: '', contactPhone: '', attachmentVersionIds: [] };
}
export function ReportForm({ source = 'desktop', mobile = false, context = {}, onClose, onSuccess }) {
  const { dataset, runMutation } = useFacilityData(); const draftKey = `veyro:facility-v2:${dataset.tenantId}:report-draft:${source}`;
  const [form, setForm] = useState(() => { try { const saved = JSON.parse(localStorage.getItem(draftKey)); return saved?.submissionKey ? { ...initialForm(dataset, source, context), ...saved, ...context } : initialForm(dataset, source, context); } catch { return initialForm(dataset, source, context); } });
  const [files, setFiles] = useState([]); const [dirty, setDirty] = useState(Boolean(form.title || form.description)); const [error, setError] = useState(null); const [success, setSuccess] = useState(null); const [busy, setBusy] = useState(false);
  useUnsavedGuard(mobile && dirty && !success);
  useEffect(() => { if (dirty && !success) localStorage.setItem(draftKey, JSON.stringify(form)); }, [dirty, draftKey, form, success]);
  const nodes = useMemo(() => dataset.locationNodes.filter((item) => item.propertyId === form.propertyId && !item.archivedAt), [dataset.locationNodes, form.propertyId]);
  const installations = dataset.installations.filter((item) => item.propertyId === form.propertyId && !item.archivedAt);
  const set = (field) => (event) => { const value = event.target.value; setForm((current) => ({ ...current, [field]: value, ...(field === 'propertyId' ? { locationId: '', installationId: '', affectedAreaIds: [] } : {}) })); setDirty(true); setError(null); };
  const toggleArea = (id) => { setForm((current) => ({ ...current, affectedAreaIds: current.affectedAreaIds.includes(id) ? current.affectedAreaIds.filter((item) => item !== id) : [...current.affectedAreaIds, id] })); setDirty(true); };
  async function submit(event) { event.preventDefault(); setBusy(true); setError(null); try { const result = await runMutation('submitReport', form, files); localStorage.removeItem(draftKey); setDirty(false); setSuccess(result); onSuccess?.(result); } catch (reason) { setError(reason); } finally { setBusy(false); } }
  function discard() { localStorage.removeItem(draftKey); setDirty(false); setForm(initialForm(dataset, source, context)); setFiles([]); }
  const content = success ? <div className="report-success"><span>✓</span><h2>Indberetningen er modtaget</h2><p>Der er atomisk oprettet én indberetning og én sag.</p><strong>{success.caseRecord.reference} · {success.caseRecord.title}</strong><div><FacilityLink className="primary-button" to={`/facility/sager/${success.caseRecord.id}`}>Åbn sag</FacilityLink>{mobile && <button className="secondary-button" type="button" onClick={discard}>Ny indberetning</button>}</div><small>Der er ikke sendt mail til en leverandør.</small></div> : <form className="entity-form report-form" onSubmit={submit}><FormFeedback error={error} /><div className="form-grid two-columns">
    <Field label="Ejendom" required error={error?.fieldErrors?.propertyId}><select value={form.propertyId} onChange={set('propertyId')}>{dataset.properties.filter((item) => !item.archivedAt).map((item) => <option key={item.id} value={item.id}>{item.number} · {item.name}</option>)}</select></Field>
    <Field label="Sted"><select value={form.locationId} onChange={set('locationId')}><option value="">Ejendommen generelt</option>{nodes.map((item) => <option key={item.id} value={item.id}>{getLocationPath(dataset, form.propertyId, item.id)}</option>)}</select></Field>
    <Field label="Installation"><select value={form.installationId} onChange={set('installationId')}><option value="">Ingen installation</option>{installations.map((item) => <option key={item.id} value={item.id}>{item.number} · {item.name}</option>)}</select></Field>
    <Field label="Observationstidspunkt"><input type="datetime-local" value={form.observedAt} onChange={set('observedAt')} /></Field>
    <Field label="Kort titel" required error={error?.fieldErrors?.title} className="span-two"><input value={form.title} onChange={set('title')} placeholder="Hvad er problemet?" /></Field>
    <Field label="Beskrivelse" required error={error?.fieldErrors?.description} className="span-two"><textarea rows="4" value={form.description} onChange={set('description')} placeholder="Beskriv hvad du har observeret" /></Field>
    <Field label="Kategori"><select value={form.category} onChange={set('category')}><option>Tekniske installationer</option><option>Bygning</option><option>El</option><option>Vand</option><option>Adgang</option><option>Andet</option></select></Field>
    <Field label="Oplevet alvorlighed" hint="Vurderes separat i triage"><select value={form.reporterSeverity} onChange={set('reporterSeverity')}><option value="high">Høj</option><option value="medium">Middel</option><option value="low">Lav</option></select></Field>
    <Field label="Påvirkede områder" className="span-two" hint="Observation – bekræftede driftsbegrænsninger registreres i sagen"><div className="checkbox-grid"><label><input type="checkbox" checked={form.affectedAreaIds.includes(`property:${form.propertyId}`)} onChange={() => toggleArea(`property:${form.propertyId}`)} /> Hele ejendommen opleves påvirket</label>{nodes.map((item) => <label key={item.id}><input type="checkbox" checked={form.affectedAreaIds.includes(item.id)} onChange={() => toggleArea(item.id)} /> {getLocationPath(dataset, form.propertyId, item.id)}</label>)}</div></Field>
    <Field label="Billeder og dokumentation" className="span-two" hint="PDF, JPEG, PNG og WebP maks. 20 MB; video maks. 100 MB"><input type="file" multiple accept="application/pdf,image/jpeg,image/png,image/webp,video/mp4,video/webm,video/quicktime" onChange={(event) => { setFiles([...event.target.files]); setDirty(true); }} />{files.length > 0 && <small>{files.length} fil(er) valgt</small>}</Field>
    <Field label="Navn (valgfrit)"><input value={form.contactName} onChange={set('contactName')} /></Field><Field label="E-mail (valgfrit)"><input type="email" value={form.contactEmail} onChange={set('contactEmail')} /></Field><Field label="Telefon (valgfrit)"><input value={form.contactPhone} onChange={set('contactPhone')} /></Field>
  </div><footer className="dialog-actions"><button type="button" className="secondary-button" onClick={discard}>Kassér kladde</button>{onClose && <button type="button" className="secondary-button" onClick={onClose}>Annuller</button>}<button type="submit" className="primary-button" disabled={busy}>{busy ? 'Indsender …' : 'Indsend indberetning'}</button></footer></form>;
  if (mobile) return <section className="mobile-report-card">{content}</section>;
  return <EntityDialog title="Ny indberetning" description="Indsendelsen opretter én indberetning og én tilknyttet sag – uden automatisk mail." onClose={onClose} dirty={dirty && !success} wide>{content}</EntityDialog>;
}
