import { useMemo, useState } from "react";
import { useFleetData } from "../data/FleetDataContext";
import { CASE_STATUSES, DEMO_ACTORS, REPORT_TYPES, SEVERITIES, USABILITY, deriveUnitUsability } from "../data/caseWorkflow";
import { CASE_CLOSURE_STATES, INVOICE_RESOLUTION_STATES, actualExternalCost, invoiceResolutionForCase } from "../data/caseFolderWorkflow";
import { WORKSHOP_TASK_STATUSES } from "../data/workshopWorkflow";
import { formatCurrency, formatMeter, modelLabel } from "../data/unitSelectors";
import { Icon } from "./Icon";
import { ReportImage } from "./ReportImage";
import { UnitThumbnail } from "./UnitThumbnail";
import { documentsForRelation } from "../data/documentWorkflow";

const tabs = ["Overblik", "Indberetning", "Bestilling og mails", "Billeder og video", "Enhedsdata", "Omkostninger", "Historik"];
const dateTime = (value) => value ? new Date(value).toLocaleString("da-DK", { dateStyle: "medium", timeStyle: "short" }) : "Ikke oplyst";

export function CaseFolder({ caseId, onNavigate }) {
  const { units, relations, closeCase, reopenCase, loading } = useFleetData();
  const [tab, setTab] = useState("Overblik");
  const [closeMode, setCloseMode] = useState("normal");
  const [confirmed, setConfirmed] = useState(false);
  const [reason, setReason] = useState("");
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const caseItem = (relations.cases || []).find((item) => item.id === caseId);
  const report = (relations.reports || []).find((item) => item.id === caseItem?.reportId);
  const unit = units.find((item) => item.id === caseItem?.unitId);
  const tasks = (relations.workshopTasks || []).filter((item) => item.caseId === caseId);
  const orders = (relations.workshopOrders || []).filter((item) => item.caseId === caseId);
  const vendor = (relations.workshops || []).find((item) => item.id === caseItem?.vendorId || item.id === tasks.at(-1)?.workshopId);
  const usability = deriveUnitUsability(caseItem?.unitId, relations.reports || [], relations.cases || [], relations.workshopTasks || []);
  const invoiceStatus = caseItem ? invoiceResolutionForCase({ relations }, caseItem) : "disconnected";
  const timeline = useMemo(() => [...(relations.caseEvents || []), ...(relations.workshopEvents || []), ...(relations.serviceEvents || []), ...(relations.orderEvents || []), ...(relations.invoiceEvents || [])].filter((item) => item.caseId === caseId).sort((a, b) => b.at?.localeCompare(a.at || "") || b.receivedAt?.localeCompare(a.receivedAt || "")), [relations, caseId]);
  if (loading) return <main className="workspace-page loading-state" id="main-content"><span className="loading-spinner" /></main>;
  if (!caseItem || !unit) return <main className="workspace-page not-found-state" id="main-content"><Icon name="warning" size={38} /><span className="eyebrow">FLEET v2 · lokal prototype</span><h1>Sagen findes ikke</h1><p>ID’et <code>{caseId}</code> findes ikke i det lokale datasæt.</p><button className="primary-button" onClick={() => onNavigate("/arbejdsko")} type="button">Til Arbejdskø</button></main>;
  const close = async () => { setBusy(true); setMessage(""); try { await closeCase(caseId, { mode: closeMode, confirmClosure: confirmed, reason }, DEMO_ACTORS[1]); setMessage("Sagen er lukket og hændelsen er gemt lokalt."); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const reopen = async () => { setBusy(true); setMessage(""); try { await reopenCase(caseId, reason, DEMO_ACTORS[1]); setMessage("Sagen er genåbnet med historik."); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const latestTask = tasks.at(-1);
  const workStatus = latestTask ? WORKSHOP_TASK_STATUSES[latestTask.status] : "Ikke oprettet";
  return <main className="workspace-page case-folder-page" id="main-content">
    <div className="profile-breadcrumb"><button onClick={() => onNavigate("/arbejdsko")} type="button">Arbejdskø</button><Icon name="chevron" size={13} /><span>{caseItem.reference}</span><em>Lokal prototype</em></div>
    <header className="case-folder-hero"><div><span className="eyebrow">Sagsmappe · {caseItem.number}</span><h1>{caseItem.reference}</h1><p>{report?.title || caseItem.title} · {unit.number} · {modelLabel(unit)}</p></div><div className="page-actions"><button className="secondary-button" type="button" onClick={() => onNavigate(`/indberetninger/${report?.id}`)} disabled={!report}>Åbn indberetning</button><button className="primary-button" type="button" onClick={() => onNavigate(`/sager/${caseId}/bestilling`)}><Icon name="document" size={16} />Tildel værksted</button></div></header>
    <section className="case-status-strip"><article><span>Arbejde</span><strong>{workStatus}</strong></article><article><span>Anvendelighed</span><strong className={usability.tone}>{usability.label}</strong></article><article><span>Fakturaafklaring</span><strong>{INVOICE_RESOLUTION_STATES[invoiceStatus]}</strong></article><article><span>Sag</span><strong>{CASE_CLOSURE_STATES[caseItem.closureStatus || "open"]}</strong></article><article><span>Leverandør</span><strong>{vendor?.name || "Ikke valgt"}</strong></article></section>
    <nav className="case-folder-tabs" aria-label="Sagsmapper"><div>{tabs.map((item) => <button aria-current={tab === item ? "page" : undefined} type="button" key={item} onClick={() => setTab(item)}>{item}</button>)}</div></nav>
    <div className="case-folder-content">{tab === "Overblik" ? <OverviewTab caseItem={caseItem} report={report} unit={unit} tasks={tasks} orders={orders} onNavigate={onNavigate} /> : null}{tab === "Indberetning" ? <ReportTab report={report} /> : null}{tab === "Bestilling og mails" ? <OrdersTab orders={orders} onNavigate={() => onNavigate(`/sager/${caseId}/bestilling`)} /> : null}{tab === "Billeder og video" ? <MediaTab report={report} tasks={tasks} documents={documentsForRelation(relations.documents, "case", caseId)} onNavigate={onNavigate} /> : null}{tab === "Enhedsdata" ? <UnitTab caseId={caseId} unit={unit} report={report} relations={relations} /> : null}{tab === "Omkostninger" ? <CostsTab caseItem={caseItem} tasks={tasks} relations={relations} /> : null}{tab === "Historik" ? <Timeline events={timeline} /> : null}
      <aside className="case-close-panel"><h2>Afslutning af sag</h2><p>Afsluttet arbejde frigiver ikke automatisk sagen. Fakturaafklaring påvirker ikke enhedens nedetid.</p>{caseItem.closureStatus === "closed" ? <><div className="closure-result"><Icon name="check" /><strong>Lukket {dateTime(caseItem.closedAt)}</strong><span>{caseItem.closureReason}</span></div><label>Begrundelse for genåbning<textarea rows="3" value={reason} onChange={(event) => setReason(event.target.value)} /></label><button className="secondary-button full" type="button" disabled={busy} onClick={reopen}>Genåbn sag</button></> : <><div className="closure-mode"><label><input type="radio" checked={closeMode === "normal"} onChange={() => setCloseMode("normal")} />Normal lukning</label><label><input type="radio" checked={closeMode === "no_invoice"} onChange={() => setCloseMode("no_invoice")} />Luk uden faktura</label></div>{closeMode === "no_invoice" ? <label>Hvorfor mangler eller forventes fakturaen ikke?<textarea aria-label="Begrundelse for lukning uden faktura" rows="3" value={reason} onChange={(event) => setReason(event.target.value)} /></label> : <div className={`invoice-readiness ${invoiceStatus === "cleared" ? "ready" : "blocked"}`}><strong>{invoiceStatus === "cleared" ? "Fakturagrundlaget er afklaret" : "Normal lukning er blokeret"}</strong><span>{INVOICE_RESOLUTION_STATES[invoiceStatus]}</span></div>}<label className="confirm-close"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} />Jeg bekræfter, at sagen kan lukkes</label><button className="primary-button full" type="button" disabled={busy} onClick={close}>Luk sag</button></>}{message ? <div className="form-alert warning" role="status">{message}</div> : null}<small>Fakturacenter er ikke tilsluttet. Ingen match-, kontrol- eller godkendelseshandlinger findes i FLEET.</small></aside>
    </div>
  </main>;
}

function OverviewTab({ caseItem, report, unit, tasks, orders, onNavigate }) { return <section className="folder-tab-content"><div className="folder-card case-unit-card"><UnitThumbnail unit={unit} /><div><span className="eyebrow">Enhed</span><h2>{unit.number} · {modelLabel(unit)}</h2><p>{unit.registration || "Ingen registrering"} · {formatMeter(unit)}</p><button className="link-button" onClick={() => onNavigate(`/enheder/${unit.id}`)} type="button">Åbn enhedsprofil</button></div></div><div className="folder-card"><h2>Problem og næste handling</h2><p>{report?.description || caseItem.description || "Ingen beskrivelse."}</p><dl className="detail-list"><div><dt>Status</dt><dd>{CASE_STATUSES[caseItem.status]}</dd></div><div><dt>Næste handling</dt><dd>{caseItem.nextAction || "Ikke oplyst"}</dd></div><div><dt>Værkstedsopgaver</dt><dd>{tasks.length}</dd></div><div><dt>Bestillinger/kladder</dt><dd>{orders.length}</dd></div></dl></div></section>; }
function ReportTab({ report }) { if (!report) return <section className="folder-tab-content"><div className="folder-card empty-inline"><h2>Manuel sag</h2><p>Sagen har ingen forudgående indberetning.</p></div></section>; return <section className="folder-tab-content"><div className="folder-card"><span className="eyebrow">{report.number} · {REPORT_TYPES[report.type]}</span><h2>{report.title}</h2><p>{report.description}</p><dl className="detail-list"><div><dt>Oplevet alvorlighed</dt><dd>{SEVERITIES[report.severity]}</dd></div><div><dt>Oplevet anvendelighed</dt><dd>{USABILITY[report.usability]}</dd></div><div><dt>Indberetter</dt><dd>{report.reporterName}</dd></div><div><dt>Oprettet</dt><dd>{dateTime(report.createdAt)}</dd></div></dl>{report.incident ? <div className="incident-summary"><h3>Skadeshændelse</h3><p>{report.incident.description || "Ingen særskilt hændelsesbeskrivelse."}</p><span>{report.incident.timeUnknown ? "Tidspunkt ukendt" : dateTime(report.incident.occurredAt)} · {report.incident.location}</span><span>Områder: {report.incident.damagedAreas?.join(", ") || "Ikke oplyst"}</span></div> : null}</div></section>; }
function OrdersTab({ orders, onNavigate }) { return <section className="folder-tab-content"><div className="folder-card"><header className="card-action-head"><h2>Bestillinger og mailudkast</h2><button className="primary-button" type="button" onClick={onNavigate}>Nyt udkast</button></header>{orders.length ? orders.map((item) => <article className="order-row" key={item.id}><span className="integration-badge">Kladde · ikke sendt</span><strong>{item.reference} · v{item.version}</strong><p>{item.subject}</p><small>{item.recipient || "Gemt uden mail"} · {dateTime(item.updatedAt)}</small></article>) : <div className="empty-inline"><p>Ingen bestilling eller mailkladde endnu.</p></div>}</div></section>; }
function MediaTab({ report, tasks, documents, onNavigate }) { const images = [...(report?.images || []), ...tasks.flatMap((item) => [...(item.beforeImages || []), ...(item.afterImages || [])])]; const media = report?.media || []; return <section className="folder-tab-content"><div className="folder-card"><header className="card-action-head"><h2>Billeder, video og dokumenter</h2><button className="secondary-button compact" type="button" onClick={() => onNavigate("/dokumenter")}>Åbn dokumentregister</button></header>{images.length ? <div className="folder-gallery">{images.map((image, index) => <ReportImage image={image} alt={`Sagsbillede ${index + 1}`} key={image.id} />)}</div> : <p className="muted">Ingen billeder.</p>}{media.map((item) => <article className="order-row" key={item.id}><strong>{item.name}</strong><span>{item.kind === "video" ? "Manuelt videoklip" : "Dokument"}</span></article>)}{documents.length ? <div className="case-document-links"><h3>Dokumentregister · {documents.length}</h3>{documents.map((document) => <button className="link-button" type="button" key={document.id} onClick={() => onNavigate(`/dokumenter/${document.id}`)}><Icon name="document" size={14} />{document.title}</button>)}</div> : null}</div><div className="folder-card integration-empty"><Icon name="gps" /><div><strong>OBD og dashcam er ikke tilsluttet</strong><p>Kun faktisk modtagne snapshots vises. Senest kendte data fremstilles ikke som ulykkesdata.</p></div></div></section>; }
function UnitTab({ caseId, unit, report, relations }) { const snapshot = (relations.evidenceSnapshots || []).find((item) => item.caseId === caseId); return <section className="folder-tab-content"><div className="folder-card"><h2>Enhedsdata</h2><dl className="detail-list"><div><dt>Enhed</dt><dd>{unit.number}</dd></div><div><dt>Mærke/model</dt><dd>{modelLabel(unit)}</dd></div><div><dt>Registrering</dt><dd>{unit.registration || "Ikke oplyst"}</dd></div><div><dt>VIN/serienummer</dt><dd>{unit.serialNumber || "Ikke oplyst"}</dd></div><div><dt>Aktuel målerstand</dt><dd>{formatMeter(unit)}</dd></div><div><dt>Indberettet observation</dt><dd>{report?.meterObservation?.value ?? "Ikke oplyst"} {report?.meterObservation?.unit === "hours" ? "t" : "km"}</dd></div></dl></div>{snapshot ? <div className="folder-card"><h2>Evidenssnapshot</h2><p>Kilde: {snapshot.source} · målt {dateTime(snapshot.measuredAt)} · modtaget {dateTime(snapshot.receivedAt)}</p></div> : null}</section>; }
function CostsTab({ caseItem, tasks, relations }) { const local = (relations.costs || []).filter((item) => item.caseId === caseItem.id); const external = actualExternalCost({ relations }, caseItem.id); return <section className="folder-tab-content"><div className="folder-card"><h2>Omkostninger ekskl. moms</h2><div className="cost-summary"><article><span>Internt faktisk</span><strong>{formatCurrency.format(local.filter((item) => item.actual).reduce((sum, item) => sum + item.amount, 0))}</strong></article><article><span>Eksternt foreløbigt</span><strong>{formatCurrency.format(local.filter((item) => !item.actual).reduce((sum, item) => sum + item.amount, 0))}</strong></article><article><span>Eksternt kontrolleret</span><strong>{formatCurrency.format(external)}</strong></article></div><p className="muted">Estimater tæller ikke som faktiske omkostninger. Kontrollerede kreditnotaer trækkes fra. Gentagne adapterhændelser deduplikeres.</p>{tasks.map((task) => <article className="order-row" key={task.id}><strong>{task.number}</strong><span>{task.workshopKind === "external" ? "Eksterne registreringer er foreløbige" : "Interne registreringer"}</span></article>)}</div></section>; }
function Timeline({ events }) { return <section className="folder-tab-content"><div className="folder-card"><h2>Fælles tidslinje</h2><div className="compact-timeline">{events.map((event) => <article key={event.id}><span><Icon name="clock" size={14} /></span><div><strong>{event.title || `Fakturahændelse · ${event.controlStatus}`}</strong><p>{event.text || `${event.documentId} · ${(event.netAmountMinor / 100).toLocaleString("da-DK")} DKK`}</p><small>{dateTime(event.at || event.receivedAt)} · {event.actorName || "Lokal adapterfixture"}</small></div></article>)}</div></div></section>; }
