import { useState } from "react";
import { DEMO_ACTORS, CASE_PRIORITIES } from "../data/caseWorkflow";
import { modelLabel } from "../data/unitSelectors";

export function ManualCaseDialog({ units, onCreate, onClose, onNavigate }) {
  const [values, setValues] = useState({ unitId: units[0]?.id || "", title: "", description: "", priority: "normal", nextAction: "Vurder manuel sag", noMailReason: "Aftale håndteres uden mail" });
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const save = async () => { setBusy(true); setError(""); try { const result = await onCreate(values, DEMO_ACTORS[1]); onNavigate(`/sager/${result.caseItem.id}`); } catch (cause) { setError(cause.message); } finally { setBusy(false); } };
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Ny manuel sag"><section className="unit-form-dialog compact-dialog"><header><div><span className="eyebrow">Lokal prototype</span><h2>Ny manuel sag</h2><p>Oprettes uden forudgående indberetning og kan gemmes uden mail.</p></div><button type="button" onClick={onClose}>×</button></header><div className="form-two-cols"><label className="span-all">Enhed<select value={values.unitId} onChange={(event) => setValues({ ...values, unitId: event.target.value })}>{units.map((unit) => <option key={unit.id} value={unit.id}>{unit.number} · {modelLabel(unit)}</option>)}</select></label><label className="span-all">Sagstitel<input aria-label="Manuel sagstitel" value={values.title} onChange={(event) => setValues({ ...values, title: event.target.value })} /></label><label className="span-all">Beskrivelse<textarea rows="4" value={values.description} onChange={(event) => setValues({ ...values, description: event.target.value })} /></label><label>Prioritet<select value={values.priority} onChange={(event) => setValues({ ...values, priority: event.target.value })}>{Object.entries(CASE_PRIORITIES).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><label>Næste handling<input value={values.nextAction} onChange={(event) => setValues({ ...values, nextAction: event.target.value })} /></label></div>{error ? <div className="form-alert danger">{error}</div> : null}<footer><button className="secondary-button" onClick={onClose} type="button">Annuller</button><button className="primary-button" disabled={busy} onClick={save} type="button">{busy ? "Gemmer …" : "Opret sag"}</button></footer></section></div>;
}
