import { useMemo, useRef, useState } from "react";
import { useFleetData } from "../data/FleetDataContext";
import { DEMO_ACTORS } from "../data/caseWorkflow";
import { SERVICE_CATEGORIES, SERVICE_REQUIREMENT_STATUSES, evaluateServiceRequirement, serviceRequirementCounts } from "../data/serviceWorkflow";
import { currentServiceOccurrence } from "../data/serviceAutomation";
import { formatMeter, modelLabel } from "../data/unitSelectors";
import { Icon } from "./Icon";
import { documentsForUnit } from "../data/documentWorkflow";

const dateLabel = (value) => value ? new Date(`${String(value).slice(0, 10)}T12:00:00`).toLocaleDateString("da-DK", { day: "numeric", month: "short", year: "numeric" }) : "—";
const meterLabel = (value, unit) => Number.isFinite(value) ? `${value.toLocaleString("da-DK")} ${unit === "hours" ? "t" : "km"}` : "—";
const statusOrder = { overdue: 0, upcoming: 1, planned: 2, missing_basis: 3, okay: 4, inactive: 5 };

const months = ["Januar", "Februar", "Marts", "April", "Maj", "Juni", "Juli", "August", "September", "Oktober", "November", "December"];

function RequirementDialog({ requirement, units, relations, onSave, onClose }) {
  const initialUnit = units.find((item) => item.id === requirement?.unitId) || units[0];
  const [values, setValues] = useState({ id: requirement?.id, unitId: initialUnit?.id || "", unitIds: initialUnit ? [initialUnit.id] : [], useAsTemplate: false, title: requirement?.title || "", description: requirement?.description || "", equipmentLabel: requirement?.equipmentLabel || "", category: requirement?.category || "maintenance", firstDueDate: requirement?.firstDueDate || requirement?.fixedDueDate || "", annualMonth: requirement?.annualMonth ?? "", annualDay: requirement?.annualDay ?? 1, intervalMonths: requirement?.intervalMonths ?? "", intervalMeter: requirement?.intervalMeter ?? "", baselineDate: requirement?.baselineDate || "", baselineMeter: requirement?.baselineMeter ?? "", warningDays: requirement?.warningDays ?? 30, warningMeter: requirement?.warningMeter ?? "", responsibleId: requirement?.responsibleId || "demo-lars", vendorId: requirement?.vendorId || "", vendorContact: requirement?.vendorContact || "", instructions: requirement?.instructions || "", documentIds: requirement?.documentIds || [], notes: requirement?.notes || "", active: requirement?.active !== false });
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const selectedUnit = units.find((item) => item.id === (values.useAsTemplate ? values.unitIds[0] : values.unitId));
  const set = (key, value) => setValues((current) => ({ ...current, [key]: value }));
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(""); try { await onSave(values.useAsTemplate && !requirement ? { ...values, unitId: undefined } : { ...values, unitIds: undefined }, DEMO_ACTORS[1]); onClose(); } catch (cause) { setError(cause.message); } finally { setBusy(false); } };
  const toggleUnit = (id) => set("unitIds", values.unitIds.includes(id) ? values.unitIds.filter((item) => item !== id) : [...values.unitIds, id]);
  const availableDocuments = (relations.documents || []).filter((item) => [...values.unitIds, values.unitId].filter(Boolean).some((unitId) => documentsForUnit([item], unitId).length));
  return <div className="modal-backdrop"><form className="workshop-dialog service-dialog" role="dialog" aria-modal="true" aria-labelledby="service-requirement-title" onSubmit={submit}>
    <header><div><span className="eyebrow">Lokal serviceprototypelagring</span><h2 id="service-requirement-title">{requirement ? "Redigér servicekrav" : "Opret servicekrav"}</h2><p>Kombiner dato, måneder og målerinterval. Den først nåede grænse udløser behovet.</p></div><button className="dialog-close" type="button" onClick={onClose} aria-label="Luk"><Icon name="close" /></button></header>
    <div className="workshop-form-grid">
      {!requirement ? <label className="checkbox-field span-2"><input type="checkbox" checked={values.useAsTemplate} onChange={(event) => set("useAsTemplate", event.target.checked)} />Fælles skabelon til flere enheder</label> : null}
      {!values.useAsTemplate || requirement ? <label>Enhed<select aria-label="Serviceenhed" value={values.unitId} onChange={(event) => set("unitId", event.target.value)} disabled={Boolean(requirement)}>{units.map((item) => <option key={item.id} value={item.id}>{item.number} · {modelLabel(item)}</option>)}</select></label> : <fieldset className="service-unit-picker span-2"><legend>Vælg enheder til skabelonen</legend>{units.map((item) => <label key={item.id}><input type="checkbox" checked={values.unitIds.includes(item.id)} onChange={() => toggleUnit(item.id)} />{item.number}<small>{modelLabel(item)} · {item.meterType === "hours" ? "driftstimer" : "km"}</small></label>)}</fieldset>}
      <label>Kategori<select aria-label="Servicekategori" value={values.category} onChange={(event) => set("category", event.target.value)}>{Object.entries(SERVICE_CATEGORIES).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>
      <label className="span-2">Titel<input aria-label="Servicekravets titel" value={values.title} onChange={(event) => set("title", event.target.value)} placeholder="Fx Årligt serviceeftersyn" /></label>
      <label className="span-2">Beskrivelse<textarea aria-label="Serviceplanens beskrivelse" rows="2" value={values.description} onChange={(event) => set("description", event.target.value)} /></label>
      <label className="span-2">Bestemt monteret udstyr, hvis relevant<input aria-label="Monteret udstyr" value={values.equipmentLabel} onChange={(event) => set("equipmentLabel", event.target.value)} placeholder="Fx Condair-klimaanlæg" /></label>
      <fieldset className="service-basis span-2"><legend>Gentagelse og første frist</legend><label>Første frist<input aria-label="Fast servicefrist" type="date" value={values.firstDueDate} onChange={(event) => set("firstDueDate", event.target.value)} /></label><label>Fast årlig måned<select aria-label="Årlig servicemåned" value={values.annualMonth} onChange={(event) => set("annualMonth", event.target.value)}><option value="">Ikke årlig kalenderopgave</option>{months.map((month, index) => <option key={month} value={index + 1}>{month}</option>)}</select></label>{values.annualMonth ? <label>Dag i måneden<input aria-label="Årlig servicedag" type="number" min="1" max="31" value={values.annualDay} onChange={(event) => set("annualDay", event.target.value)} /></label> : null}<label>Interval i måneder<input aria-label="Serviceinterval måneder" type="number" min="1" value={values.intervalMonths} onChange={(event) => set("intervalMonths", event.target.value)} placeholder="Fx 12" /></label><label>Interval i {selectedUnit?.meterType === "hours" ? "driftstimer" : "kilometer"}<input aria-label="Serviceinterval måler" type="number" min="1" value={values.intervalMeter} onChange={(event) => set("intervalMeter", event.target.value)} placeholder={selectedUnit?.meterType === "hours" ? "Fx 500" : "Fx 40.000"} /></label></fieldset>
      <label>Grunddato<input aria-label="Service grunddato" type="date" value={values.baselineDate} onChange={(event) => set("baselineDate", event.target.value)} /></label><label>Grundmåler ({selectedUnit?.meterType === "hours" ? "timer" : "km"})<input aria-label="Service grundmåler" type="number" min="0" value={values.baselineMeter} onChange={(event) => set("baselineMeter", event.target.value)} /></label>
      <label>Varsel før dato (dage)<input aria-label="Servicevarsel dage" type="number" min="0" value={values.warningDays} onChange={(event) => set("warningDays", event.target.value)} /></label><label>Varsel før målergrænse<input aria-label="Servicevarsel måler" type="number" min="0" value={values.warningMeter} onChange={(event) => set("warningMeter", event.target.value)} /></label>
      <label>Ansvarlig<select aria-label="Serviceansvarlig" value={values.responsibleId} onChange={(event) => set("responsibleId", event.target.value)}>{DEMO_ACTORS.slice(1).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="checkbox-field"><input type="checkbox" checked={values.active} onChange={(event) => set("active", event.target.checked)} />Aktivt krav</label>
      <label>Leverandør<select aria-label="Serviceleverandør" value={values.vendorId} onChange={(event) => set("vendorId", event.target.value)}><option value="">Vælges senere</option>{(relations.workshops || []).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Kontaktperson<input aria-label="Leverandørkontakt" value={values.vendorContact} onChange={(event) => set("vendorContact", event.target.value)} placeholder="Navn eller mail" /></label>
      <label className="span-2">Instruktioner<textarea aria-label="Serviceinstruktioner" rows="3" value={values.instructions} onChange={(event) => set("instructions", event.target.value)} /></label>
      {availableDocuments.length ? <fieldset className="service-document-picker span-2"><legend>Relevante dokumentrelationer</legend>{availableDocuments.map((document) => <label key={document.id}><input type="checkbox" checked={values.documentIds.includes(document.id)} onChange={(event) => set("documentIds", event.target.checked ? [...values.documentIds, document.id] : values.documentIds.filter((id) => id !== document.id))} />{document.title}</label>)}</fieldset> : null}
      <label className="span-2">Noter<textarea aria-label="Servicekrav noter" rows="3" value={values.notes} onChange={(event) => set("notes", event.target.value)} /></label>
    </div>{error ? <div className="form-alert danger" role="alert">{error}</div> : null}<footer><button className="secondary-button" type="button" onClick={onClose}>Annuller</button><button className="primary-button" type="submit" disabled={busy}>{busy ? "Gemmer …" : "Gem servicekrav"}</button></footer>
  </form></div>;
}

function PlanDialog({ requirement, unit, relations, onPlan, onClose, onNavigate }) {
  const [values, setValues] = useState({ workshopId: requirement.vendorId || relations.workshops?.[0]?.id || "", assigneeId: requirement.responsibleId || "demo-lars", priority: "normal", dueDate: "", expectedCompletionAt: "", expectedCost: "", workDescription: requirement.instructions || `Udfør ${requirement.title} og registrér målerstand samt resultat.` });
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const set = (key, value) => setValues((current) => ({ ...current, [key]: value }));
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(""); try { const result = await onPlan(requirement.id, values, DEMO_ACTORS[1]); onClose(); onNavigate(`/vaerksted/${result.task.id}`); } catch (cause) { setError(cause.message); setBusy(false); } };
  return <div className="modal-backdrop"><form className="workshop-dialog" role="dialog" aria-modal="true" aria-labelledby="plan-service-title" onSubmit={submit}><header><div><span className="eyebrow">{unit.number} · {requirement.title}</span><h2 id="plan-service-title">Planlæg service</h2><p>Der oprettes én servicesag og én værkstedsopgave med samme Veyro-reference — ingen indberetning.</p></div><button className="dialog-close" type="button" onClick={onClose} aria-label="Luk"><Icon name="close" /></button></header><div className="workshop-form-grid"><label>Værksted<select aria-label="Serviceværksted" value={values.workshopId} onChange={(event) => set("workshopId", event.target.value)}>{relations.workshops.map((item) => <option value={item.id} key={item.id}>{item.name} · {item.kind === "internal" ? "Internt" : "Eksternt"}</option>)}</select></label><label>Ansvarlig<select aria-label="Planlægningsansvarlig" value={values.assigneeId} onChange={(event) => set("assigneeId", event.target.value)}>{DEMO_ACTORS.slice(1).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Sagens frist<input aria-label="Servicesagens frist" type="date" value={values.dueDate} onChange={(event) => set("dueDate", event.target.value)} /></label><label>Forventet færdig<input aria-label="Service forventet færdig" type="datetime-local" value={values.expectedCompletionAt} onChange={(event) => set("expectedCompletionAt", event.target.value)} /></label><label className="span-2">Arbejdsbeskrivelse<textarea aria-label="Service arbejdsbeskrivelse" rows="4" value={values.workDescription} onChange={(event) => set("workDescription", event.target.value)} /></label><label>Estimat ekskl. moms<input aria-label="Serviceestimat" inputMode="decimal" value={values.expectedCost} onChange={(event) => set("expectedCost", event.target.value.replace(",", "."))} placeholder="Ukendt" /></label></div>{error ? <div className="form-alert danger" role="alert">{error}</div> : null}<footer><button className="secondary-button" type="button" onClick={onClose}>Annuller</button><button className="primary-button" type="submit" disabled={busy}>{busy ? "Planlægger …" : "Opret sag og opgave"}</button></footer></form></div>;
}

function HistoricalDialog({ units, requirements, initialUnitId, onSave, onClose }) {
  const clientId = useRef(crypto.randomUUID());
  const [values, setValues] = useState({ clientId: clientId.current, unitId: initialUnitId || units[0]?.id || "", requirementId: "", title: "Serviceeftersyn", date: "", meter: "", result: "Udført", notes: "", advanceRequirement: true });
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const selectedUnit = units.find((item) => item.id === values.unitId);
  const matchingRequirements = requirements.filter((item) => item.unitId === values.unitId);
  const set = (key, value) => setValues((current) => ({ ...current, [key]: value }));
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(""); try { await onSave(values, DEMO_ACTORS[1]); onClose(); } catch (cause) { setError(cause.message); setBusy(false); } };
  return <div className="modal-backdrop"><form className="workshop-dialog" role="dialog" aria-modal="true" aria-labelledby="historical-service-title" onSubmit={submit}><header><div><span className="eyebrow">Eksisterende fælles servicebog</span><h2 id="historical-service-title">Registrér historisk service</h2><p>Posten gemmes lokalt og kan flytte næste frist, hvis den knyttes til et krav.</p></div><button className="dialog-close" type="button" onClick={onClose} aria-label="Luk"><Icon name="close" /></button></header><div className="workshop-form-grid"><label>Enhed<select aria-label="Historisk serviceenhed" value={values.unitId} onChange={(event) => setValues((current) => ({ ...current, unitId: event.target.value, requirementId: "" }))}>{units.map((item) => <option key={item.id} value={item.id}>{item.number} · {modelLabel(item)}</option>)}</select></label><label>Servicekrav<select aria-label="Historisk servicekrav" value={values.requirementId} onChange={(event) => set("requirementId", event.target.value)}><option value="">Ingen specifik frist</option>{matchingRequirements.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label className="span-2">Titel<input aria-label="Historisk servicetitel" value={values.title} onChange={(event) => set("title", event.target.value)} /></label><label>Dato<input aria-label="Historisk servicedato" type="date" value={values.date} onChange={(event) => set("date", event.target.value)} /></label><label>Målerstand ({selectedUnit?.meterType === "hours" ? "timer" : "km"})<input aria-label="Historisk servicemåler" type="number" min="0" value={values.meter} onChange={(event) => set("meter", event.target.value)} /></label><label className="span-2">Resultat<input aria-label="Historisk serviceresultat" value={values.result} onChange={(event) => set("result", event.target.value)} /></label><label className="span-2">Noter<textarea aria-label="Historisk servicenote" rows="3" value={values.notes} onChange={(event) => set("notes", event.target.value)} /></label>{values.requirementId ? <label className="checkbox-field span-2"><input type="checkbox" checked={values.advanceRequirement} onChange={(event) => set("advanceRequirement", event.target.checked)} />Brug posten som nyt beregningsgrundlag</label> : null}</div>{error ? <div className="form-alert danger" role="alert">{error}</div> : null}<footer><button className="secondary-button" type="button" onClick={onClose}>Annuller</button><button className="primary-button" type="submit" disabled={busy}>{busy ? "Gemmer …" : "Gem i servicebogen"}</button></footer></form></div>;
}

function AutomationDialog({ settings, onRun, onSave, onClose }) {
  const [testDate, setTestDate] = useState(new Date().toISOString().slice(0, 10));
  const [values, setValues] = useState({ autoMailEntitled: settings.autoMailEntitled, autoMailRuleEnabled: settings.autoMailRuleEnabled });
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const run = async () => { setBusy(true); setMessage(""); try { const result = await onRun({ now: `${testDate}T10:00:00.000Z` }); setMessage(result.created.length ? `${result.created.length} ny(e) automatisk(e) indberetning(er) og sag(er) blev oprettet.` : "Kontrollen fandt ingen nye varsler. Eksisterende forekomster blev ikke duplikeret."); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const save = async () => { setBusy(true); setMessage(""); try { await onSave(values); setMessage("Indstillingen er gemt lokalt. Ingen mail kan afsendes fra prototypen."); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  return <div className="modal-backdrop"><section className="workshop-dialog automation-dialog" role="dialog" aria-modal="true" aria-labelledby="service-automation-title"><header><div><span className="eyebrow">Lokal og kontrollerbar demotid</span><h2 id="service-automation-title">Serviceautomatik</h2><p>Varsler kontrolleres ved appstart og hvert minut, mens appen er åben.</p></div><button className="dialog-close" type="button" onClick={onClose} aria-label="Luk"><Icon name="close" /></button></header><div className="automation-settings"><section><h3>Afprøv varsling uden at ændre computerens ur</h3><label>Kontrollér som dato<input aria-label="Demodato for servicevarsling" type="date" value={testDate} onChange={(event) => setTestDate(event.target.value)} /></label><button className="primary-button" type="button" disabled={busy} onClick={run}>Kør varslingskontrol</button><small>Kun den aktuelle forekomst indhentes. Oversprungne historiske perioder oprettes ikke som en bunke sager.</small></section><section><h3>Automatisk mail · betalt tilvalg</h3><label className="checkbox-field"><input type="checkbox" checked={values.autoMailEntitled} onChange={(event) => setValues((current) => ({ ...current, autoMailEntitled: event.target.checked, autoMailRuleEnabled: event.target.checked ? current.autoMailRuleEnabled : false }))} />Mailtilvalg registreret i demoen</label><label className="checkbox-field"><input type="checkbox" disabled={!values.autoMailEntitled} checked={values.autoMailRuleEnabled} onChange={(event) => setValues((current) => ({ ...current, autoMailRuleEnabled: event.target.checked }))} />Automatisk mailregel konfigureret</label><button className="secondary-button" type="button" disabled={busy} onClick={save}>Gem mailindstilling</button><small>Selv når begge indstillinger er aktive, sender denne prototype aldrig mail. Manuel mailklargøring er fortsat tilgængelig.</small></section></div>{message ? <div className="form-alert warning" role="status">{message}</div> : null}<footer><span>Mens appen er lukket, kan der ikke oprettes noget. Produktionsdrift kræver en serverbaseret planlagt kørsel.</span><button className="secondary-button" type="button" onClick={onClose}>Luk</button></footer></section></div>;
}

export function ServiceOverview({ onNavigate }) {
  const { units, relations, loading, saveServiceRequirement, planService, saveHistoricalService, runServiceAutomation, saveServiceSettings } = useFleetData();
  const params = new URLSearchParams(window.location.search);
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [editing, setEditing] = useState(null); const [planning, setPlanning] = useState(null); const [historyOpen, setHistoryOpen] = useState(params.get("action") === "history"); const [automationOpen, setAutomationOpen] = useState(false);
  const requirements = relations.serviceRequirements || [];
  const evaluated = useMemo(() => requirements.map((requirement) => ({ requirement, unit: units.find((item) => item.id === requirement.unitId), evaluation: evaluateServiceRequirement(requirement, units.find((item) => item.id === requirement.unitId), relations) })).sort((a, b) => statusOrder[a.evaluation.status] - statusOrder[b.evaluation.status] || a.requirement.title.localeCompare(b.requirement.title, "da")), [requirements, units, relations]);
  const counts = serviceRequirementCounts(requirements, units, relations);
  const filtered = evaluated.filter((item) => (status === "all" || item.evaluation.status === status) && (!query || `${item.unit?.number} ${modelLabel(item.unit || {})} ${item.requirement.title}`.toLocaleLowerCase("da").includes(query.toLocaleLowerCase("da"))));
  if (loading) return <main className="workspace-page loading-state" id="main-content"><span className="loading-spinner" /><p>Indlæser servicekrav …</p></main>;
  return <main className="workspace-page service-page" id="main-content">
    <header className="page-heading-row"><div><span className="eyebrow">FLEET v2 · lokale serviceplaner</span><h1>Service og compliance</h1><p>Følg egne kalender-, måneds- og målerplaner. Varsling opretter én sammenhængende indberetning og sag.</p></div><div className="page-actions"><button className="secondary-button" type="button" onClick={() => setAutomationOpen(true)}><Icon name="service" size={16} />Serviceautomatik</button><button className="secondary-button" type="button" onClick={() => setHistoryOpen(true)}><Icon name="clock" size={16} />Historisk service</button><button className="primary-button" type="button" onClick={() => setEditing({})}><Icon name="plus" size={16} />Opret servicekrav</button></div></header>
    <section className="service-kpis"><button type="button" onClick={() => setStatus("overdue")}><span className="service-kpi-icon danger"><Icon name="warning" /></span><span>Overskredet<strong>{counts.overdue || 0}</strong><small>kræver handling nu</small></span></button><button type="button" onClick={() => setStatus("upcoming")}><span className="service-kpi-icon warning"><Icon name="clock" /></span><span>Kommende<strong>{counts.upcoming || 0}</strong><small>inden for varslet</small></span></button><button type="button" onClick={() => setStatus("planned")}><span className="service-kpi-icon info"><Icon name="service" /></span><span>Planlagt<strong>{counts.planned || 0}</strong><small>sag og opgave findes</small></span></button><button type="button" onClick={() => setStatus("missing_basis")}><span className="service-kpi-icon neutral"><Icon name="info" /></span><span>Mangler grundlag<strong>{counts.missing_basis || 0}</strong><small>kan ikke beregnes sikkert</small></span></button></section>
    <section className="service-reminder-card"><div><Icon name="info" /><span><strong>Automatisk varsling inde i FLEET</strong><small>Kontrollen kører ved appstart og hvert minut. Indberetning og sag oprettes atomisk; automatisk mail er {relations.serviceSettings?.[0]?.autoMailRuleEnabled ? "konfigureret, men ikke tilsluttet" : "slået fra"}.</small></span></div><button className="integration-badge" type="button" onClick={() => setAutomationOpen(true)}>Senest: {relations.serviceSettings?.[0]?.lastAutomationRunAt ? dateLabel(relations.serviceSettings[0].lastAutomationRunAt) : "ikke kørt"}</button></section>
    <section className="service-table-card"><header className="service-toolbar"><div className="catalog-search"><Icon name="search" size={16} /><input aria-label="Søg i servicekrav" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Søg på enhed, model eller krav …" /></div><select aria-label="Filtrér servicestatus" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">Alle statusser</option>{Object.entries(SERVICE_REQUIREMENT_STATUSES).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><button className="link-button" type="button" onClick={() => { setQuery(""); setStatus("all"); }}>Nulstil filtre</button><strong>{filtered.length} krav</strong></header>
      <div className="service-requirement-table"><div className="service-requirement-head"><span>Status</span><span>Serviceplan</span><span>Enhed</span><span>Næste dato</span><span>Næste måler</span><span>Grundlag</span><span>Handling</span></div>{filtered.map(({ requirement, unit, evaluation }) => { const occurrence = currentServiceOccurrence(relations, requirement.id); return <article key={requirement.id} className="service-requirement-row"><span><i className={`service-status-pill ${evaluation.status}`}>{SERVICE_REQUIREMENT_STATUSES[evaluation.status]}</i>{occurrence?.origin === "service_automation" ? <small>Automatisk varslet</small> : evaluation.status === "planned" ? <small>{SERVICE_REQUIREMENT_STATUSES[evaluation.underlyingStatus]}</small> : null}</span><span><strong>{requirement.title}</strong><small>{SERVICE_CATEGORIES[requirement.category]} · {requirement.annualMonth ? `${months[requirement.annualMonth - 1]} årligt` : "først nåede grænse"}</small>{requirement.templateId ? <em>Fælles skabelon</em> : null}</span><button className="service-unit-link" type="button" onClick={() => onNavigate(`/enheder/${unit.id}`)}><strong>{unit.number}</strong><small>{modelLabel(unit)}</small></button><span><strong>{dateLabel(evaluation.dueDate)}</strong>{evaluation.dateDays != null ? <small>{evaluation.dateDays < 0 ? `${Math.abs(evaluation.dateDays)} dage overskredet` : `${evaluation.dateDays} dage tilbage`}</small> : null}</span><span><strong>{meterLabel(evaluation.dueMeter, requirement.meterUnit)}</strong>{evaluation.meterRemaining != null ? <small>{evaluation.meterRemaining <= 0 ? `${Math.abs(evaluation.meterRemaining).toLocaleString("da-DK")} over` : `${evaluation.meterRemaining.toLocaleString("da-DK")} tilbage`}</small> : null}</span><span>{evaluation.missing.length ? <em>{evaluation.missing.join(" og ")}</em> : <small>Aktuel: {formatMeter(unit)}</small>}{occurrence?.orderReference ? <small>{occurrence.orderReference} · ikke sendt</small> : null}</span><span className="service-row-actions">{evaluation.task ? <button className="primary-button compact" type="button" onClick={() => onNavigate(`/vaerksted/${evaluation.task.id}`)}>Åbn opgave</button> : <>{occurrence?.reportId ? <button className="secondary-button compact" type="button" onClick={() => onNavigate(`/indberetninger/${occurrence.reportId}`)}>Indberetning</button> : null}{requirement.active ? <button className="primary-button compact" type="button" onClick={() => setPlanning(requirement)}>Planlæg</button> : null}</>}<button className="icon-button" type="button" onClick={() => setEditing(requirement)} aria-label={`Redigér ${requirement.title}`}><Icon name="edit" size={15} /></button></span></article>; })}{!filtered.length ? <div className="empty-inline"><h2>Ingen serviceplaner matcher</h2><p>Tilpas filtre eller opret en ny serviceplan.</p></div> : null}</div>
    </section>
    {editing ? <RequirementDialog requirement={editing.id ? editing : null} units={units} relations={relations} onSave={saveServiceRequirement} onClose={() => setEditing(null)} /> : null}
    {planning ? <PlanDialog requirement={planning} unit={units.find((item) => item.id === planning.unitId)} relations={relations} onPlan={planService} onNavigate={onNavigate} onClose={() => setPlanning(null)} /> : null}
    {historyOpen ? <HistoricalDialog units={units} requirements={requirements} initialUnitId={params.get("unit")} onSave={saveHistoricalService} onClose={() => setHistoryOpen(false)} /> : null}
    {automationOpen ? <AutomationDialog settings={relations.serviceSettings?.[0] || { autoMailEntitled: false, autoMailRuleEnabled: false }} onRun={runServiceAutomation} onSave={saveServiceSettings} onClose={() => setAutomationOpen(false)} /> : null}
  </main>;
}
